# Generated by Django 5.2.8 on 2026-01-25 09:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0010_ledger_core"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('academic_year', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('DECIDED', 'Decided')], db_index=True, default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_applications', to='households.household')),
            ],
            options={
                'db_table': 'aid_application',
            },
        ),
        migrations.CreateModel(
            name='AidAward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied')], max_length=16)),
                ('amount_annual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aid_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='financial_aid.aidapplication')),
            ],
            options={
                'db_table': 'aid_award',
            },
        ),
        migrations.CreateModel(
            name='AidDisbursement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursed_on', models.DateField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='financial_aid.aidaward')),
            ],
            options={
                'db_table': 'aid_disbursement',
            },
        ),
        migrations.CreateModel(
            name='AidEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('aid_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='financial_aid.aidapplication')),
            ],
            options={
                'db_table': 'aid_event',
            },
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['school_id', 'academic_year'], name='aid_applica_school__08ff95_idx'),
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['school_id', 'status'], name='aid_applica_school__860762_idx'),
        ),
        migrations.AddIndex(
            model_name='aidaward',
            index=models.Index(fields=['school_id', 'status'], name='aid_award_school__729c45_idx'),
        ),
        migrations.AddIndex(
            model_name='aiddisbursement',
            index=models.Index(fields=['school_id', 'disbursed_on'], name='aid_disburs_school__7e06f7_idx'),
        ),
        migrations.AddIndex(
            model_name='aidevent',
            index=models.Index(fields=['school_id', 'event_type'], name='aid_event_school__70d852_idx'),
        ),
        migrations.AddIndex(
            model_name='aidevent',
            index=models.Index(fields=['school_id', 'aid_application', 'created_at'], name='aid_event_school__9abc43_idx'),
        ),
    ]
