# Generated by Django 5.2.8 on 2026-01-25 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0040_billing_core"),
        ("financial_aid", "0020_financial_aid_core"),
        ("ledger", "0060_ledger_payment_source"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAidDisbursement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_disbursements",
                        to="financial_aid.aidaward",
                    ),
                ),
                (
                    "billing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aid_disbursements",
                        to="billing.billingrun",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aid_disbursements",
                        to="billing.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aid_disbursements",
                        to="ledger.payment",
                    ),
                ),
            ],
            options={
                "db_table": "financial_aid_disbursement",
                "indexes": [
                    models.Index(fields=["school_id", "billing_run"], name="financial_a_school__88c9d1_idx"),
                    models.Index(fields=["school_id", "invoice"], name="financial_a_school__93ce7d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("award", "billing_run"),
                        name="uniq_award_billingrun_disbursement",
                    )
                ],
            },
        ),
    ]
