# Generated by Django 5.2.8 on 2026-02-26 12:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('to', models.TextField()),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed (retrying)'), ('DEAD', 'Dead (max retries)')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='comms_outbo_status_27778c_idx'), models.Index(fields=['school_id', 'created_at'], name='comms_outbo_school__6c696c_idx')],
            },
        ),
    ]
