# Generated by Django 5.2.17 on 2026-10-02 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_outbox_message'),
        ('households', '0010_student_account'),
        ('reenrollment', '0002_reenrollmentsession_communication_timezone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version', models.PositiveIntegerField(default=1, editable=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('blocks', models.JSONField(default=list)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('approved_fingerprint', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_content_releases', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_releases', to='reenrollment.reenrollmentsession')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='comms.contentrelease')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(blank=True, choices=[('', 'No response'), ('returning', 'Returning'), ('declining', 'Declining'), ('undecided', 'Undecided')], max_length=16)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.guardian')),
                ('outbox', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comms.outboxmessage')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='comms.contentrelease')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release', 'guardian'), name='unique_release_guardian')],
            },
        ),
    ]
