# Generated by Django 5.2.8 on 2026-02-28 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.JSONField(blank=True, default=dict)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('comms', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_settings', to='core.school')),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('plan_code', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=32)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe Connect'), ('manual', 'Manual / Invoice'), ('none', 'None')], default='none', max_length=32)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('offboarded', 'Offboarded')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='core.school')),
            ],
            options={
                'verbose_name': 'Tenant Profile',
                'verbose_name_plural': 'Tenant Profiles',
            },
        ),
    ]
