# Generated by Django 5.2 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantprofile",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("manual", "Manual / Invoice"),
                    ("none", "None / Disabled"),
                ],
                default="none",
                max_length=32,
            ),
        ),
    ]
