# Generated by Django 5.2.8 on 2026-02-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('academic_year', models.CharField(db_index=True, max_length=9)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('school_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ExtendedCarePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports_annual', models.BooleanField(default=False)),
                ('supports_monthly', models.BooleanField(default=True)),
                ('supports_weekly', models.BooleanField(default=False)),
                ('supports_drop_in_daily', models.BooleanField(default=True)),
                ('supports_hybrid', models.BooleanField(default=True)),
                ('late_pickup_grace_minutes', models.IntegerField(default=5)),
                ('late_pickup_fee_cents', models.IntegerField(default=0)),
                ('late_pickup_per_minute_cents', models.IntegerField(default=0)),
                ('post_to_ledger', models.BooleanField(default=True)),
                ('include_in_tuition_plan', models.BooleanField(default=False)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_care', to='finance_setup.financepolicyversion')),
            ],
            options={
                'verbose_name': 'Extended Care Policy',
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts_apply_to', models.CharField(default='tuition_only', max_length=16)),
                ('stacking_enabled', models.BooleanField(default=True)),
                ('sibling_discount_enabled', models.BooleanField(default=True)),
                ('sibling_discount_percent_bp', models.IntegerField(default=1000)),
                ('sibling_discount_applies_from_child', models.IntegerField(default=2)),
                ('staff_discount_enabled', models.BooleanField(default=True)),
                ('staff_discount_percent_bp', models.IntegerField(default=0)),
                ('ministry_discount_enabled', models.BooleanField(default=False)),
                ('ministry_discount_percent_bp', models.IntegerField(default=0)),
                ('max_discount_percent_bp', models.IntegerField(default=10000)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance_setup.financepolicyversion')),
            ],
            options={
                'verbose_name': 'Discount Policy',
            },
        ),
        migrations.CreateModel(
            name='FinancialAidPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_fee_cents', models.IntegerField(default=5500)),
                ('aid_applies_to', models.CharField(default='tuition_only', max_length=16)),
                ('distribute_aid_evenly', models.BooleanField(default=True)),
                ('max_aid_per_student_cents', models.IntegerField(default=0)),
                ('max_aid_per_family_cents', models.IntegerField(default=0)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='finance_setup.financepolicyversion')),
            ],
            options={
                'verbose_name': 'Financial Aid Policy',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_pay_in_full', models.BooleanField(default=True)),
                ('allow_semi_annual', models.BooleanField(default=True)),
                ('allow_quarterly', models.BooleanField(default=True)),
                ('allow_10_month', models.BooleanField(default=True)),
                ('allow_12_month', models.BooleanField(default=True)),
                ('ach_required_for_installments', models.BooleanField(default=True)),
                ('pay_in_full_discount_percent_bp', models.IntegerField(default=0)),
                ('late_fee_grace_days', models.IntegerField(default=5)),
                ('late_fee_flat_cents', models.IntegerField(default=0)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='finance_setup.financepolicyversion')),
            ],
            options={
                'verbose_name': 'Payment Plan Policy',
            },
        ),
        migrations.CreateModel(
            name='TuitionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_mode', models.CharField(default='grade_based', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('flat_annual_tuition_cents', models.IntegerField(default=0)),
                ('fees_apply_to_aid', models.BooleanField(default=False)),
                ('fees_apply_to_discounts', models.BooleanField(default=False)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to='finance_setup.financepolicyversion')),
            ],
            options={
                'verbose_name': 'Tuition Policy',
            },
        ),
    ]
