# Generated by Django 5.2.14 on 2026-05-24 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpolicy',
            name='max_discount_percent_bp',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='discountpolicy',
            name='ministry_discount_percent_bp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='discountpolicy',
            name='sibling_discount_applies_from_child',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='discountpolicy',
            name='sibling_discount_percent_bp',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='discountpolicy',
            name='staff_discount_percent_bp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='extendedcarepolicy',
            name='late_pickup_fee_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extendedcarepolicy',
            name='late_pickup_grace_minutes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extendedcarepolicy',
            name='late_pickup_per_minute_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialaidpolicy',
            name='application_fee_cents',
            field=models.IntegerField(default=5500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialaidpolicy',
            name='max_aid_per_family_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financialaidpolicy',
            name='max_aid_per_student_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplanpolicy',
            name='late_fee_flat_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplanpolicy',
            name='late_fee_grace_days',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplanpolicy',
            name='pay_in_full_discount_percent_bp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='tuitionpolicy',
            name='flat_annual_tuition_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
