# Generated by Django 5.2.8 on 2026-02-28 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('resource_kind', models.CharField(blank=True, default='', max_length=128)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='platform_op_action_46c541_idx'), models.Index(fields=['school_id'], name='platform_op_school__e9051a_idx'), models.Index(fields=['actor_user_id'], name='platform_op_actor_u_2e2ff1_idx'), models.Index(fields=['created_at'], name='platform_op_created_73ecfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='core.school')),
            ],
            options={
                'verbose_name': 'Provisioning Job',
                'verbose_name_plural': 'Provisioning Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state'], name='platform_op_state_0babc3_idx'), models.Index(fields=['school_id'], name='platform_op_school__50d9d9_idx')],
            },
        ),
    ]
