# Generated by Django 5.2.8 on 2026-02-06 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0032_rename_teacher_ass_school__7df83a_idx_teacher_ass_school__e963a3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_maps', to='academics.course')),
            ],
            options={
                'db_table': 'curriculum_map',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('curriculum_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curricula.curriculummap')),
            ],
            options={
                'db_table': 'curriculum_unit',
                'ordering': ['curriculum_map', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('sequence', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curricula.unit')),
            ],
            options={
                'db_table': 'curriculum_lesson',
                'ordering': ['unit', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculummap',
            index=models.Index(fields=['school_id', 'course'], name='curriculum__school__b0f5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['school_id', 'curriculum_map', 'sequence'], name='curriculum__school__4ad46d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school_id', 'unit', 'sequence'], name='curriculum__school__182fd0_idx'),
        ),
    ]
