# Generated by Django 5.2.8 on 2026-02-06 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_rename_teacher_ass_school__7df83a_idx_teacher_ass_school__e963a3_idx_and_more'),
        ('curricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummap',
            name='grade_band',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='curriculummap',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='unit',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculummap',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_maps', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.TextField(blank=True, default=''),
        ),
    ]
