import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("journal", "0005_journalline_accounting_dimensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("restriction", models.CharField(choices=[("UNRESTRICTED", "Unrestricted"), ("RESTRICTED", "Restricted"), ("BOARD_DESIGNATED", "Board designated")], default="UNRESTRICTED", max_length=24)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"db_table": "accounting_fund", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="AccountingDimension",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("DEPARTMENT", "Department"), ("PROGRAM", "Program"), ("CAMPUS", "Campus"), ("PROJECT", "Project")], max_length=16)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"db_table": "accounting_dimension", "ordering": ["kind", "code"]},
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("legal_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                ("active", models.BooleanField(default=True)),
                ("default_expense_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="default_vendors", to="journal.glaccount")),
            ],
            options={"db_table": "accounting_vendor", "ordering": ["display_name", "legal_name"]},
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("fiscal_start", models.DateField()),
                ("fiscal_end", models.DateField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("APPROVED", "Approved"), ("CLOSED", "Closed")], default="DRAFT", max_length=16)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "accounting_budget", "ordering": ["-fiscal_start", "name"]},
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=48)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=16)),
                ("ordered_on", models.DateField(default=django.utils.timezone.localdate)),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("memo", models.TextField(blank=True)),
                ("created_by", models.UUIDField()),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="accounting.vendor")),
            ],
            options={"db_table": "accounting_purchase_order", "ordering": ["-ordered_on", "number"]},
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="journal.glaccount")),
                ("dimension", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="accounting.accountingdimension")),
                ("fund", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="accounting.fund")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="accounting.purchaseorder")),
            ],
            options={"db_table": "accounting_purchase_order_line", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="PayableBill",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_number", models.CharField(max_length=64)),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("APPROVED", "Approved"), ("POSTED", "Posted"), ("PAID", "Paid"), ("VOID", "Void")], default="DRAFT", max_length=16)),
                ("memo", models.TextField(blank=True)),
                ("created_by", models.UUIDField()),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("journal_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payable_bills", to="journal.journalentry")),
                ("liability_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payable_bills", to="journal.glaccount")),
                ("purchase_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bills", to="accounting.purchaseorder")),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bills", to="accounting.vendor")),
            ],
            options={"db_table": "accounting_payable_bill", "ordering": ["due_date", "bill_date"]},
        ),
        migrations.CreateModel(
            name="PayableBillLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="accounting.payablebill")),
                ("dimension", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payable_bill_lines", to="accounting.accountingdimension")),
                ("expense_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payable_bill_lines", to="journal.glaccount")),
                ("fund", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payable_bill_lines", to="accounting.fund")),
            ],
            options={"db_table": "accounting_payable_bill_line", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="budget_lines", to="journal.glaccount")),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="accounting.budget")),
                ("dimension", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="budget_lines", to="accounting.accountingdimension")),
                ("fund", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="budget_lines", to="accounting.fund")),
            ],
            options={"db_table": "accounting_budget_line", "ordering": ["account__code", "created_at"]},
        ),
        migrations.AddConstraint(model_name="fund", constraint=models.UniqueConstraint(fields=("tenant_id", "code"), name="accounting_fund_tenant_code_uq")),
        migrations.AddConstraint(model_name="accountingdimension", constraint=models.UniqueConstraint(fields=("tenant_id", "kind", "code"), name="accounting_dimension_tenant_kind_code_uq")),
        migrations.AddConstraint(model_name="vendor", constraint=models.UniqueConstraint(fields=("tenant_id", "code"), name="accounting_vendor_tenant_code_uq")),
        migrations.AddConstraint(model_name="budget", constraint=models.UniqueConstraint(fields=("tenant_id", "name", "fiscal_start", "fiscal_end"), name="accounting_budget_period_name_uq")),
        migrations.AddConstraint(model_name="purchaseorder", constraint=models.UniqueConstraint(fields=("tenant_id", "number"), name="accounting_po_tenant_number_uq")),
        migrations.AddConstraint(model_name="payablebill", constraint=models.UniqueConstraint(fields=("tenant_id", "vendor", "bill_number"), name="accounting_bill_tenant_vendor_number_uq")),
    ]
