# Generated by Django 6.0 on 2026-01-25 14:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0030_academics_core"),
        ("ledger", "0010_ledger_core"),
        ("households", "0008_households_guardians_students"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('term', models.CharField(db_index=True, max_length=24)),
                ('run_type', models.CharField(db_index=True, default='TUITION', max_length=32)),
                ('description', models.CharField(default='Tuition Billing Run', max_length=200)),
                ('amount_per_student', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'db_table': 'billing_run',
                'indexes': [models.Index(fields=['school_id', 'term'], name='billing_run_school__e9ce9a_idx'), models.Index(fields=['school_id', 'run_type'], name='billing_run_school__4f0495_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ledger_charge_id', models.UUIDField(blank=True, null=True)),
                ('billing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingrun')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='households.household')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('description', models.CharField(default='Tuition', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='households.student')),
            ],
            options={
                'db_table': 'invoice_line',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school_id', 'billing_run'], name='invoice_school__024d06_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school_id', 'household'], name='invoice_school__962dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['school_id', 'invoice'], name='invoice_lin_school__043276_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['school_id', 'student'], name='invoice_lin_school__7cfba5_idx'),
        ),
    ]
