# Generated by Django 6.0 on 2026-01-25 15:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0040_billing_core"),
        ("households", "0008_households_guardians_students"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("term", models.CharField(db_index=True, max_length=24)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("installment_count", models.PositiveIntegerField(default=1)),
                ("first_due_on", models.DateField()),
                ("cadence_days", models.PositiveIntegerField(default=30)),
            ],
            options={
                "db_table": "installment_plan",
            },
        ),
        migrations.CreateModel(
            name="InstallmentScheduleItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("sequence", models.PositiveIntegerField()),
                ("due_on", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_schedule_items",
                        to="households.household",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installment_items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.installmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "installment_schedule_item",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["school_id", "due_on"], name="invoice_school__7bb08e_idx"),
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(fields=["school_id", "term"], name="installment_school__51aafa_idx"),
        ),
        migrations.AddIndex(
            model_name="installmentplan",
            index=models.Index(fields=["school_id", "name"], name="installment_school__e971ab_idx"),
        ),
        migrations.AddIndex(
            model_name="installmentscheduleitem",
            index=models.Index(fields=["school_id", "plan"], name="installment_school__35748b_idx"),
        ),
        migrations.AddIndex(
            model_name="installmentscheduleitem",
            index=models.Index(fields=["school_id", "household"], name="installment_school__ce1c02_idx"),
        ),
        migrations.AddIndex(
            model_name="installmentscheduleitem",
            index=models.Index(fields=["school_id", "due_on"], name="installment_school__3a7c7c_idx"),
        ),
        migrations.AddConstraint(
            model_name="installmentscheduleitem",
            constraint=models.UniqueConstraint(
                fields=("plan", "household", "sequence"),
                name="uniq_plan_household_sequence",
            ),
        ),
    ]
