# Generated by Django 6.0 on 2026-01-25 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0080_billing_installments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(max_length=24)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'entity_type', 'entity_id'], name='billing_bil_school__a22caf_idx'), models.Index(fields=['school_id', 'timestamp'], name='billing_bil_school__11ac4a_idx'), models.Index(fields=['school_id', 'action'], name='billing_bil_school__d1eff3_idx')],
            },
        ),
    ]
