# Generated by Django 5.2.8 on 2026-01-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0081_billingauditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingauditevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
