# Generated by Django 6.0 on 2026-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0082_alter_billingauditevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingauditevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
