# Generated by Django 5.2.8 on 2026-02-28 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_alter_billingauditevent_id'),
        ('households', '0008_households_guardians_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdDelinquency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('delinquent_since', models.DateField(blank=True, db_index=True, null=True)),
                ('suspended', models.BooleanField(db_index=True, default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delinquency_record', to='households.household')),
            ],
            options={
                'db_table': 'household_delinquency',
                'indexes': [models.Index(fields=['school_id', 'suspended'], name='household_d_school__9905be_idx'), models.Index(fields=['school_id', 'delinquent_since'], name='household_d_school__2f48eb_idx')],
            },
        ),
    ]
