# Generated by Django 5.2 on 2026-10-05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0084_stage2_household_delinquency"),
        ("households", "0008_households_guardians_students"),
        ("ledger", "0063_student_account_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPayer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("payer_type", models.CharField(choices=[("GUARDIAN", "Guardian"), ("THIRD_PARTY", "Third party"), ("ORGANIZATION", "Organization")], default="GUARDIAN", max_length=20)),
                ("display_name", models.CharField(blank=True, default="", max_length=160)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="billing_payer_profiles", to=settings.AUTH_USER_MODEL)),
                ("guardian", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="billing_payer_profiles", to="households.guardian")),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="billing_payers", to="households.household")),
            ],
            options={
                "db_table": "billing_payer",
                "indexes": [
                    models.Index(fields=["school_id", "household", "is_active"], name="billing_pay_school__d32d57_idx"),
                    models.Index(fields=["school_id", "account", "is_active"], name="billing_pay_school__b09b75_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("school_id", "household", "guardian"), name="uniq_billing_payer_household_guardian"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingResponsibilityRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("charge_type", models.CharField(db_index=True, default="TUITION", max_length=32)),
                ("percentage_bps", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="billing_responsibility_rules", to="households.household")),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="responsibility_rules", to="billing.billingpayer")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="billing_responsibility_rules", to="households.student")),
            ],
            options={
                "db_table": "billing_responsibility_rule",
                "indexes": [
                    models.Index(fields=["school_id", "household", "charge_type", "is_active"], name="billing_res_school__8853ca_idx"),
                    models.Index(fields=["school_id", "student", "charge_type", "is_active"], name="billing_res_school__d19f7d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("student__isnull", True)), fields=("school_id", "household", "payer", "charge_type"), name="uniq_household_payer_charge_rule"),
                    models.UniqueConstraint(condition=models.Q(("student__isnull", False)), fields=("school_id", "student", "payer", "charge_type"), name="uniq_student_payer_charge_rule"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayerShare",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("waived_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payer_shares", to="billing.invoice")),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_shares", to="billing.billingpayer")),
            ],
            options={
                "db_table": "invoice_payer_share",
                "indexes": [
                    models.Index(fields=["school_id", "payer"], name="invoice_pay_school__f9bd7c_idx"),
                    models.Index(fields=["school_id", "invoice"], name="invoice_pay_school__a6db58_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("invoice", "payer"), name="uniq_invoice_payer_share"),
                    models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="payer_share_amount_nonnegative"),
                    models.CheckConstraint(condition=models.Q(("waived_amount__gte", 0)), name="payer_share_waived_nonnegative"),
                    models.CheckConstraint(condition=models.Q(("waived_amount__lte", models.F("amount"))), name="payer_share_waived_lte_amount"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayerAllocationAttribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("allocation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payer_attributions", to="ledger.allocation")),
                ("share", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_attributions", to="billing.invoicepayershare")),
            ],
            options={
                "db_table": "payer_allocation_attribution",
                "indexes": [
                    models.Index(fields=["school_id", "share"], name="payer_alloc_school__53e532_idx"),
                    models.Index(fields=["school_id", "allocation"], name="payer_alloc_school__6c6b39_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("share", "allocation"), name="uniq_payer_share_allocation"),
                    models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="payer_attribution_amount_positive"),
                ],
            },
        ),
    ]
