# Generated by Django 5.2.17 on 2026-10-05 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0085_split_payer_billing'),
        ('ledger', '0063_student_account_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerRefundAttribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_attributions', to='billing.payerallocationattribution')),
                ('refund_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_refund_attributions', to='ledger.charge')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attribution', 'refund_charge'), name='uniq_payer_attribution_refund'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payer_refund_amount_positive')],
            },
        ),
    ]
