# Generated by Django 6.0 on 2026-02-03 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0032_rename_teacher_ass_school__7df83a_idx_teacher_ass_school__e963a3_idx_and_more'),
        ('households', '0008_households_guardians_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('assignment_name', models.CharField(max_length=255)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('points_possible', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_entries', to='households.student')),
            ],
            options={
                'db_table': 'grade_entry',
                'indexes': [models.Index(fields=['school_id', 'section'], name='grade_entry_school__9645c2_idx'), models.Index(fields=['school_id', 'student'], name='grade_entry_school__3b15f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'student', 'assignment_name'), name='uniq_grade_entry_section_student_assignment')],
            },
        ),
    ]
