# Generated by CROWN sandbox implementation pack.

from django.db import migrations, models
import django.db.models.deletion
import sandbox_demo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SandboxInvite",
            fields=[
                ("id", models.CharField(default=sandbox_demo.models.make_invite_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ("organization_label", models.CharField(max_length=180)),
                ("track", models.CharField(default="school", max_length=32)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("allowed_seed_packs", models.JSONField(blank=True, default=list)),
                ("default_guidance", models.CharField(default="guided", max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.useraccount")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["track", "expires_at"], name="sandbox_dem_track_f3f4d5_idx"),
                    models.Index(fields=["revoked_at"], name="sandbox_dem_revoked_4fd23e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SandboxEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=80)),
                ("track", models.CharField(max_length=32)),
                ("guidance", models.CharField(max_length=32)),
                ("persona", models.CharField(max_length=64)),
                ("school", models.CharField(max_length=100)),
                ("tour", models.CharField(blank=True, default="", max_length=180)),
                ("step", models.IntegerField(blank=True, null=True)),
                ("route", models.CharField(blank=True, default="", max_length=180)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("invite", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sandbox_demo.sandboxinvite")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event", "occurred_at"], name="sandbox_dem_event_d14ac3_idx"),
                    models.Index(fields=["track", "persona", "occurred_at"], name="sandbox_dem_track_80f9ed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SandboxFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("track", models.CharField(max_length=32)),
                ("guidance", models.CharField(max_length=32)),
                ("persona", models.CharField(max_length=64)),
                ("school", models.CharField(max_length=100)),
                ("scenario", models.CharField(max_length=180)),
                ("step", models.IntegerField(blank=True, null=True)),
                ("rating", models.CharField(choices=[("clear", "Clear"), ("unclear", "Unclear"), ("not_relevant", "Not Relevant"), ("blocked", "Blocked")], max_length=24)),
                ("note", models.TextField(blank=True, default="")),
                ("follow_up_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invite", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sandbox_demo.sandboxinvite")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["rating", "created_at"], name="sandbox_dem_rating_8ff55a_idx"),
                    models.Index(fields=["track", "persona", "created_at"], name="sandbox_dem_track_cf54a8_idx"),
                ],
            },
        ),
    ]
