# Generated by Django 5.2.8 on 2026-01-25 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crown_api', '0007_messagethread_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('address1', models.CharField(blank=True, default='', max_length=160)),
                ('address2', models.CharField(blank=True, default='', max_length=160)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=40)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'household',
                'indexes': [models.Index(fields=['school_id', 'is_active'], name='household_school__c98910_idx'), models.Index(fields=['school_id', 'name'], name='household_school__4360f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='households.household')),
            ],
            options={
                'db_table': 'guardian',
                'indexes': [models.Index(fields=['school_id', 'household'], name='guardian_school__b564eb_idx'), models.Index(fields=['school_id', 'last_name', 'first_name'], name='guardian_school__ffe63a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade_level', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='households.household')),
            ],
            options={
                'db_table': 'student',
                'indexes': [models.Index(fields=['school_id', 'is_active'], name='student_school__ec9e90_idx'), models.Index(fields=['school_id', 'last_name', 'first_name'], name='student_school__c7b520_idx'), models.Index(fields=['school_id', 'grade_level'], name='student_school__d035ae_idx')],
            },
        ),
    ]
