# Generated by Django 5.2.8 on 2026-02-28 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('pricing_currency', models.CharField(default='USD', max_length=3)),
                ('base_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_student_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
            },
        ),
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('limit_int', models.IntegerField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='subscriptions.feature')),
            ],
            options={
                'verbose_name': 'Entitlement Override',
                'unique_together': {('school_id', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('limit_int', models.IntegerField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Plan Entitlement',
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('period_yyyymm', models.CharField(db_index=True, max_length=6)),
                ('used_int', models.IntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='subscriptions.feature')),
            ],
            options={
                'verbose_name': 'Usage Counter',
                'unique_together': {('school_id', 'feature', 'period_yyyymm')},
            },
        ),
    ]
