# Generated by Django 5.2.8 on 2026-03-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsubscription',
            name='school_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
