# Generated by Django 5.2.12 on 2026-03-31 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_backfill_household_family_link"),
        ("subscriptions", "0002_remove_tenant_subscription_school_id_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        choices=[
                            ("financial_aid", "Financial Aid Processing"),
                            ("chapel_tracking", "Chapel & Devotional Tracking"),
                            ("gradebook_pro", "Advanced Gradebook"),
                            ("curriculum_mgmt", "Curriculum Management"),
                            ("parent_portal_plus", "Enhanced Parent Portal"),
                            ("hr_staff", "HR & Staff Management"),
                            ("little_lambs", "Little Lambs Daycare"),
                            ("transportation", "Transportation & Bus Routing"),
                            ("health_office", "Health Office & Nurse Records"),
                            ("alumni", "Alumni Tracking"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("trial", "Trial (30-day)"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("annual", "Annual"), ("monthly", "Monthly")],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("purchased_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal Crown admin notes"
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_activated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Module",
                "verbose_name_plural": "School Modules",
                "ordering": ["school", "module_key"],
                "unique_together": {("school", "module_key")},
            },
        ),
    ]
