# Generated by Django 5.2.8 on 2026-02-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('event_id', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_provider_event')],
            },
        ),
    ]
