# Generated by Django 5.2.8 on 2026-02-17 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seedrun'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsPreviewAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_preview_audits', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'event_type', 'created_at'], name='integration_school__cfe3d7_idx')],
            },
        ),
    ]
