# Generated by Django 6.0 on 2026-01-25 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_name', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('school_id', models.CharField(blank=True, default='', max_length=64)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
