# Generated by Django 5.2.17 on 2026-10-04 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_marketing_edit_permission'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('training', 'Training'), ('certification', 'Certification'), ('clearance', 'Clearance'), ('acknowledgment', 'Acknowledgment')], max_length=24)),
                ('due_date', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='core.staff')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffRequirementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField()),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hr.staffrequirement')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='staffrequirement',
            index=models.Index(fields=['school', 'staff', 'due_date'], name='hr_staffreq_school__6e363c_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirementevent',
            constraint=models.UniqueConstraint(fields=('school', 'actor', 'request_key'), name='hr_requirement_retry'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirementevent',
            constraint=models.UniqueConstraint(fields=('requirement', 'version'), name='hr_requirement_event_version'),
        ),
    ]
