$ErrorActionPreference = "Stop"

code .\docs\Crown_Master_Binder\00_TABLE_OF_CONTENTS.md
code .\docs\Crown_Master_Binder\03_Operations_and_Delivery\03_Phase_Progress_Scorecard.csv
code .\docs\Crown_Master_Binder\03_Operations_and_Delivery\05_Approval_Gates.md
code .\docs\Crown_Master_Binder\03_Operations_and_Delivery\07_Phase_Gate_Review_Packet.md
code .\docs\Crown_Master_Binder\03_Operations_and_Delivery\09_Phase_Gate_Register.csv
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\02_Build_Sequence.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\06_Phase_1_Inventory_and_Canon_Lock.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\07_Phase_2_Classification_and_Approval.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\08_Phase_3_Archive_and_Purge_Readiness.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\09_Phase_4_Controlled_Purge_and_Clean_Bootstrap.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\10_Phase_5_Core_Build.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\11_Phase_6_First_Wave_Modules.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\12_Phase_7_Hardening_Integration_and_Release_Readiness.md
code .\docs\Crown_Master_Binder\05_Runbooks_and_Checklists\13_Completion_Gate_Master_Checklist.md
