# Generated by Django 5.2.8 on 2026-02-27 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_schedule_wizard', '0001_initial'),
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bellschedulewizardsession',
            name='label',
        ),
        migrations.RemoveField(
            model_name='bellschedulewizardsession',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='bellschedulewizardsession',
            name='school_year',
        ),
        migrations.AddField(
            model_name='bellschedulewizardsession',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bell_schedule_wizard_sessions', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='bellschedulewizardsession',
            name='blocks_config',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bellschedulewizardsession',
            name='schedule_mode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bellschedulewizardsession',
            name='schedule_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bellschedulewizardsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('blocks_set', 'Blocks Set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('schedule_mode', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_schedules', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_schedules', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=20)),
                ('ordering', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='bell_schedule_wizard.bellschedule')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='PeriodBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ordering', models.IntegerField(default=0)),
                ('is_instructional', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bell_schedule_wizard.daytemplate')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddIndex(
            model_name='bellschedule',
            index=models.Index(fields=['school', 'is_active'], name='bell_schedu_school__debd8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='bellschedule',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='uniq_bell_schedule_school_year_name'),
        ),
        migrations.AddConstraint(
            model_name='daytemplate',
            constraint=models.UniqueConstraint(fields=('schedule', 'template_code'), name='uniq_day_template_code'),
        ),
        migrations.AddConstraint(
            model_name='periodblock',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_period_block_code'),
        ),
        migrations.AddConstraint(
            model_name='periodblock',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='chk_period_block_start_lt_end'),
        ),
    ]
