# Generated by Django 5.2.8 on 2026-01-04 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_aiddocument_aid_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_INFO', 'Needs Info'), ('ACCEPTED', 'Accepted'), ('WAITLISTED', 'Waitlisted'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=24)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('test_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('essay_received', models.BooleanField(default=False)),
                ('recommendations_received', models.PositiveSmallIntegerField(default=0)),
                ('transcript_received', models.BooleanField(default=False)),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_applications', to='core.academicyear')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_applications', to='core.family')),
                ('last_contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_contacts_initiated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_applications', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions_applications', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('APPLICATION', 'Application'), ('REVIEW', 'Review'), ('DECISION', 'Decision')], max_length=24)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions_audit_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_audit_events', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WAITLISTED', 'Waitlisted'), ('DENIED', 'Denied')], max_length=16)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_letter_sent', models.BooleanField(default=False)),
                ('decision_letter_sent_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_decisions', to='core.academicyear')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='admissions.admissionsapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_decisions', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_score', models.PositiveSmallIntegerField(default=0)),
                ('character_score', models.PositiveSmallIntegerField(default=0)),
                ('mission_fit_score', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('WAITLIST', 'Waitlist'), ('DENY', 'Deny')], default='', max_length=24)),
                ('recommendation_notes', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='admissions.admissionsapplication')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_reviews', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_reviews', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='admissionsapplication',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='admissions__school__679329_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsapplication',
            index=models.Index(fields=['school', 'family'], name='admissions__school__fb34f2_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsauditevent',
            index=models.Index(fields=['school', 'entity_type', 'entity_id'], name='admissions__school__386aff_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsauditevent',
            index=models.Index(fields=['school', 'timestamp'], name='admissions__school__c3018f_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsauditevent',
            index=models.Index(fields=['school', 'action'], name='admissions__school__853ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionsdecision',
            index=models.Index(fields=['school', 'academic_year', 'decision_status'], name='admissions__school__aae55c_idx'),
        ),
    ]
