# Generated by Django 6.0 on 2026-01-25 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('crown_api', '0003_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsapplication',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='crown_api.household'),
        ),
        migrations.AddField(
            model_name='admissionsapplication',
            name='sis_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='crown_api.student'),
        ),
    ]
