# Generated by Django 5.2.8 on 2026-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_link_household_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_INFO', 'Needs Info'), ('ACCEPTED', 'Accepted'), ('WAITLISTED', 'Waitlisted'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn'), ('ENROLLED', 'Enrolled')], default='DRAFT', max_length=24),
        ),
    ]
