# Generated by Django 5.2.8 on 2026-01-25 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_aid", "0020_financial_aid_core"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'course',
                'indexes': [models.Index(fields=['school_id', 'code'], name='course_school__cf208f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('term', models.CharField(db_index=True, max_length=24)),
                ('teacher_name', models.CharField(blank=True, default='', max_length=120)),
                ('grade_band', models.CharField(blank=True, default='', max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.course')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='households.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section')),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school_id', 'term'], name='section_school__9a89ba_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school_id', 'course'], name='section_school__f82e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school_id', 'section'], name='enrollment_school__495123_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school_id', 'student'], name='enrollment_school__a219b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('section', 'student'), name='uniq_section_student'),
        ),
    ]
