# Generated by Django 5.2.8 on 2026-02-03 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0030_academics_core"),
        ("core", "0004_seedrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(db_index=True, max_length=24)),
                ("name", models.CharField(max_length=80)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_terms",
                        to="core.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "academic_term",
            },
        ),
        migrations.AddField(
            model_name="section",
            name="term_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="academics.term",
            ),
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_assignment",
            },
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["school_id", "academic_year"], name="academic_te_school__b3a636_idx"),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["school_id", "code"], name="academic_te_school__4f0355_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(fields=["school_id", "section"], name="teacher_ass_school__e963a3_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(fields=["school_id", "staff"], name="teacher_ass_school__a331ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="teacherassignment",
            constraint=models.UniqueConstraint(fields=("section", "staff"), name="uniq_section_staff"),
        ),
    ]
