# Generated by Django 5.2.11 on 2026-02-06 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_rename_teacher_ass_school__7df83a_idx_teacher_ass_school__e963a3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_categories', to='academics.section')),
            ],
            options={
                'db_table': 'assignment_category',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=7)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.section')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.assignmentcategory')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.AddIndex(
            model_name='assignmentcategory',
            index=models.Index(fields=['school_id', 'section'], name='assignment__school__bcee69_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentcategory',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniq_category_section_name'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school_id', 'section'], name='assignment_school__8e1bec_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['section', 'category'], name='assignment_section_209889_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniq_assignment_section_name'),
        ),
    ]
