# Generated by Django 5.2.11 on 2026-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0033_assignmentcategory_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="course",
            name="grading_scale_ref",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="term",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="term",
            name="school_year",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
