# Generated by Django 5.2.11 on 2026-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0034_course_term_spine_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="teacher_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
