# Generated by Django 5.2.8 on 2026-02-18 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_remove_section_teacher_id_section_teacher'),
        ('households', '0008_households_guardians_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('instructional_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='CurriculumSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='publisher', max_length=32)),
                ('reference_link', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'curriculum_source',
                'indexes': [models.Index(fields=['school_id'], name='curriculum__school__5f44d8_idx')],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.lesson'),
        ),
        migrations.CreateModel(
            name='PublisherObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('objective_code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='academics.lesson')),
            ],
            options={
                'db_table': 'publisher_objective',
            },
        ),
        migrations.CreateModel(
            name='MasteryRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('mastery_level', models.PositiveSmallIntegerField(default=1)),
                ('last_demonstrated_at', models.DateTimeField(auto_now=True)),
                ('evidence_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_evidence', to='academics.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='households.student')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='academics.publisherobjective')),
            ],
            options={
                'db_table': 'mastery_record',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.publisherobjective'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('late', 'Late'), ('missing', 'Missing'), ('graded', 'Graded')], default='assigned', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.enrollment')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('numeric_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('letter_grade', models.CharField(default='F', max_length=2)),
                ('teacher_feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.submission')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('credit_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_letter_grade', models.CharField(default='', max_length=2)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gpa_points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('dual_enrollment_label', models.CharField(blank=True, default='', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='households.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_entries', to='academics.term')),
            ],
            options={
                'db_table': 'transcript_entry',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence_order', models.PositiveSmallIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.course')),
                ('curriculum_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='academics.curriculumsource')),
            ],
            options={
                'db_table': 'unit',
                'ordering': ['sequence_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.unit'),
        ),
        migrations.AddIndex(
            model_name='publisherobjective',
            index=models.Index(fields=['school_id', 'lesson'], name='publisher_o_school__1a3cac_idx'),
        ),
        migrations.AddConstraint(
            model_name='publisherobjective',
            constraint=models.UniqueConstraint(fields=('lesson', 'objective_code'), name='uniq_objective_lesson_code'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['school_id', 'student'], name='mastery_rec_school__efd27b_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['school_id', 'objective'], name='mastery_rec_school__faf719_idx'),
        ),
        migrations.AddConstraint(
            model_name='masteryrecord',
            constraint=models.UniqueConstraint(fields=('student', 'objective'), name='uniq_mastery_student_objective'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['school_id', 'assignment'], name='submission_school__c71c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['school_id', 'enrollment'], name='submission_school__9d03bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'enrollment'), name='uniq_submission_assignment_enrollment'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school_id', 'submission'], name='grade_school__cdd622_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptentry',
            index=models.Index(fields=['school_id', 'student'], name='transcript__school__00a4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptentry',
            index=models.Index(fields=['school_id', 'course'], name='transcript__school__8e8034_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptentry',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'term'), name='uniq_transcript_student_course_term'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['school_id', 'course'], name='unit_school__7ca39a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school_id', 'unit'], name='lesson_school__aafb20_idx'),
        ),
    ]
