# Generated by Django 5.2.8 on 2026-02-25 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_lesson_curriculumsource_assignment_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('plan_date', models.DateField(db_index=True)),
                ('lesson_ids', models.JSONField(blank=True, default=list)),
                ('objectives', models.TextField(blank=True, default='')),
                ('materials', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='')),
                ('teacher_notes_private', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.section')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_plan',
                'indexes': [models.Index(fields=['school_id', 'section', 'plan_date'], name='lesson_plan_school__06dcc2_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'section', 'plan_date'), name='uniq_lesson_plan_school_section_date')],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('link', 'Link'), ('file', 'File'), ('video', 'Video'), ('doc', 'Document')], default='link', max_length=32)),
                ('url', models.URLField(blank=True, default='')),
                ('file_ref', models.CharField(blank=True, default='', max_length=128)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.lesson')),
            ],
            options={
                'db_table': 'lesson_resource',
                'indexes': [models.Index(fields=['school_id', 'lesson'], name='lesson_reso_school__4a7fd3_idx')],
            },
        ),
    ]
