# Generated by Django 5.2.8 on 2026-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0038_lesson_plan_and_resource'),
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='uniq_term_year_code'),
        ),
    ]
