# Generated by Django 5.2.17 on 2026-10-01 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_assignment_home_support_assignment_instructions_and_more'),
        ('households', '0010_student_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('home_support', 'Home Support'), ('practice', 'Practice'), ('formative_check', 'Formative Check'), ('group_project', 'Group Project'), ('positive_observation', 'Positive Observation'), ('accommodation', 'Accommodation'), ('support_plan', 'Support Plan'), ('service', 'Service'), ('resource', 'Resource'), ('coaching', 'Coaching'), ('interruption', 'Interruption'), ('help_request', 'Help Request'), ('goal', 'Goal'), ('reflection', 'Reflection'), ('portfolio', 'Portfolio'), ('absence_explanation', 'Absence Explanation')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('class', 'Class'), ('family', 'Family'), ('staff', 'Staff'), ('private', 'Private')], max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('state', models.CharField(default='open', max_length=16)),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_classroom_records', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_records', to='academics.section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='households.student')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='households.student')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='academics.classroomrecord')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('state', models.CharField(default='submitted', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='academics.classroomrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='classroomrecord',
            index=models.Index(fields=['school_id', 'section', 'state'], name='academics_c_school__2756e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomrecord',
            constraint=models.UniqueConstraint(fields=('school_id', 'created_by', 'request_key'), name='unique_classroom_record_retry'),
        ),
        migrations.AddConstraint(
            model_name='classroomevent',
            constraint=models.UniqueConstraint(fields=('record', 'request_key'), name='unique_classroom_event_retry'),
        ),
        migrations.AddConstraint(
            model_name='classroomresponse',
            constraint=models.UniqueConstraint(fields=('record', 'student'), name='unique_classroom_response'),
        ),
    ]
