# Generated by Django 5.2.17 on 2026-10-01 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0043_classroomconferenceslot_classroomfamilythread_and_more'),
        ('households', '0010_student_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAttendanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='academics.classroomattendancesession')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEmergencySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('drill', 'Drill'), ('incident', 'Incident')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('completion_note', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomEmergencyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='unknown', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='academics.classroomemergencysession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomOperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSubstituteGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_grants', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classroomattendancesession',
            constraint=models.UniqueConstraint(fields=('school_id', 'section', 'date'), name='unique_attendance_session'),
        ),
        migrations.AddConstraint(
            model_name='classroomattendanceaudit',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='unique_attendance_audit_version'),
        ),
        migrations.AddConstraint(
            model_name='classroomemergencycheck',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_emergency_student'),
        ),
        migrations.AddConstraint(
            model_name='classroomoperationevent',
            constraint=models.UniqueConstraint(fields=('school_id', 'actor', 'request_key'), name='unique_classroom_operation_retry'),
        ),
    ]
