# Generated by Django 5.2.17 on 2026-10-01 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0044_classroomattendancesession_classroomattendanceaudit_and_more'),
        ('households', '0010_student_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='accessible_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='alternative_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ClassroomMasteryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.assignment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_history', to='academics.masteryrecord')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=160)),
                ('criteria', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.classroomrubric'),
        ),
        migrations.CreateModel(
            name='ClassroomDeadlineAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('due_date', models.DateField()),
                ('instructions', models.TextField()),
                ('reason_private', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_adjustments', to='academics.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.student')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school_id', 'assignment', 'student'), name='unique_classroom_deadline')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomInstructionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school_id', 'actor', 'request_key'), name='unique_classroom_instruction_retry')],
            },
        ),
    ]
