# Generated by Django 5.2.17 on 2026-10-01 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0045_lessonresource_accessible_description_and_more'),
        ('discipline', '0003_alter_disciplineaction_action_type'),
        ('households', '0010_student_account'),
        ('signals', '0004_interventionaction_created_by_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomInterventionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_links', to='signals.interventioncase')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'case'), name='unique_classroom_intervention')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomRestorativeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('review_at', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_links', to='discipline.disciplineincident')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'incident'), name='unique_classroom_restorative')],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSupportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.section')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school_id', 'actor', 'request_key'), name='unique_classroom_support_retry')],
            },
        ),
    ]
