# Generated by Django 5.2.17 on 2026-10-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0046_classroominterventionlink_classroomrestorativelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomrecord',
            name='kind',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('home_support', 'Home Support'), ('practice', 'Practice'), ('formative_check', 'Formative Check'), ('group_project', 'Group Project'), ('positive_observation', 'Positive Observation'), ('accommodation', 'Accommodation'), ('support_plan', 'Support Plan'), ('service', 'Service'), ('resource', 'Resource'), ('coaching', 'Coaching'), ('interruption', 'Interruption'), ('help_request', 'Help Request'), ('goal', 'Goal'), ('reflection', 'Reflection'), ('portfolio', 'Portfolio'), ('absence_explanation', 'Absence Explanation'), ('family_service', 'Family Service')], max_length=32),
        ),
    ]
