# Generated by Django 5.2.17 on 2026-10-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0047_alter_classroomrecord_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattendancesession',
            name='expected_roster',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
