# Generated by Django 5.2.13 on 2026-04-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0010_backfill_household_family_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('input_snapshot_date', models.DateField()),
                ('output_json', models.JSONField()),
                ('confidence_interval_low', models.FloatField(blank=True, null=True)),
                ('confidence_interval_high', models.FloatField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_model_runs', to='core.school')),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
    ]
