# Generated by Django 5.2.8 on 2026-02-16 23:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seedrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('room', models.CharField(blank=True, default='', max_length=40)),
                ('grade_level', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homerooms', to='core.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSeatingChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_chart', to='classroom.classroom')),
            ],
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'is_active', 'created_at'], name='classroom_c_school__9ecb01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='classroomannouncement',
            index=models.Index(fields=['classroom', '-created_at'], name='classroom_c_classro_c9017b_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomassignment',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='classroom_c_classro_14eec6_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomenrollment',
            index=models.Index(fields=['classroom', 'student'], name='classroom_c_classro_d0724b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomenrollment',
            unique_together={('classroom', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroomseatingchart',
            index=models.Index(fields=['classroom'], name='classroom_c_classro_d00970_idx'),
        ),
    ]
