# Generated by Django 5.2.8 on 2026-02-27 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('reenroll_close_date', models.DateField(blank=True, null=True)),
                ('reenroll_first', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_periods', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_periods', to='core.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year'), name='uniq_enrollment_period_school_year')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPeriodWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_date', models.CharField(blank=True, default='', max_length=10)),
                ('close_date', models.CharField(blank=True, default='', max_length=10)),
                ('reenroll_close_date', models.CharField(blank=True, default='', max_length=10)),
                ('reenroll_first', models.BooleanField(default=False)),
                ('capacities_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('capacities_set', 'Capacities Set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_period_wizard_sessions', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_period_wizard_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_period_wizard_sessions', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='enrollment__school__7b703b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_code', models.CharField(max_length=3)),
                ('target_seats', models.IntegerField(default=0)),
                ('new_students_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_capacities', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_capacities', to='core.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'grade_code'), name='uniq_grade_capacity_year_grade'), models.CheckConstraint(condition=models.Q(('target_seats__gte', 0)), name='chk_grade_capacity_seats_gte_0')],
            },
        ),
    ]
