# Generated by Django 6.0 on 2026-01-03 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_aiddocument_aid_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_INFO', 'Needs Info'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=24)),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('income_annual_cents', models.IntegerField(default=0)),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_applications', to='core.academicyear')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_applications', to='core.family')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_applications', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AidAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('APPLICATION', 'Application'), ('REVIEW', 'Review'), ('AWARD', 'Award')], max_length=24)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aid_audit_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_audit_events', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AidAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_type', models.CharField(choices=[('NEED', 'Need'), ('MISSION', 'Mission'), ('MERIT', 'Merit'), ('HARDSHIP', 'Hardship')], default='NEED', max_length=16)),
                ('awarded_cents', models.IntegerField(default=0)),
                ('decision_status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='OFFERED', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_awards', to='core.academicyear')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aid_awards_decided', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aid_award', to='core.ledgerentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_awards', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_awards', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='AidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('W2', 'W-2'), ('TAX_RETURN', 'Tax Return'), ('PAY_STUB', 'Pay Stub'), ('OTHER', 'Other')], max_length=24)),
                ('received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('aid_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='aid.aidapplication')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_documents', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AidReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_cents', models.IntegerField(default=0)),
                ('recommendation_notes', models.TextField(blank=True, default='')),
                ('aid_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='aid.aidapplication')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_reviews', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_reviews', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='aid_aidappl_school__accc53_idx'),
        ),
        migrations.AddIndex(
            model_name='aidapplication',
            index=models.Index(fields=['school', 'family'], name='aid_aidappl_school__10f1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='aidauditevent',
            index=models.Index(fields=['school', 'entity_type', 'entity_id'], name='aid_aidaudi_school__b60018_idx'),
        ),
        migrations.AddIndex(
            model_name='aidauditevent',
            index=models.Index(fields=['school', 'timestamp'], name='aid_aidaudi_school__e0ec89_idx'),
        ),
        migrations.AddIndex(
            model_name='aidauditevent',
            index=models.Index(fields=['school', 'action'], name='aid_aidaudi_school__096c55_idx'),
        ),
        migrations.AddIndex(
            model_name='aidaward',
            index=models.Index(fields=['school', 'academic_year', 'award_type'], name='aid_aidawar_school__8a417a_idx'),
        ),
        migrations.AddIndex(
            model_name='aidaward',
            index=models.Index(fields=['school', 'student'], name='aid_aidawar_school__9eca13_idx'),
        ),
    ]
