# Generated by Django 6.0 on 2026-01-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidapplication',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='last_contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_contacts_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='last_contacted_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
