# Generated by Django 5.2.8 on 2026-02-25 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_aidapplication_last_contacted_at_and_more'),
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidapplication',
            name='assets_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='church_involvement_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='family_values_survey_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='liabilities_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='pastoral_reference_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='pog_preassessment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='statement_of_faith_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='aid_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='aid.aidapplication'),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='explanation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='mas_modifier_bps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='mas_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='recommended_award_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aidaward',
            name='award_type',
            field=models.CharField(choices=[('NEED', 'Need'), ('MISSION', 'Mission'), ('MERIT', 'Merit'), ('HARDSHIP', 'Hardship'), ('MARKETING', 'Marketing')], default='NEED', max_length=16),
        ),
        migrations.CreateModel(
            name='AidBudgetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(choices=[('NEED', 'Need'), ('MISSION', 'Mission'), ('MERIT', 'Merit'), ('HARDSHIP', 'Hardship'), ('MARKETING', 'Marketing')], max_length=16)),
                ('allocated_cents', models.BigIntegerField(default=0)),
                ('awarded_cents', models.BigIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_budget_trackers', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_budget_trackers', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year', 'bucket')},
            },
        ),
        migrations.CreateModel(
            name='AidPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_income_floor_cents', models.BigIntegerField(default=0, help_text='Income below this floor is treated as $0 for need calculation.')),
                ('max_award_percent', models.IntegerField(default=60, help_text='Maximum award as % of gross tuition (0-100).')),
                ('min_award_percent', models.IntegerField(default=0, help_text='Minimum award as % of gross tuition (0-100).')),
                ('bucket_need_bps', models.IntegerField(default=6000)),
                ('bucket_mission_bps', models.IntegerField(default=1500)),
                ('bucket_marketing_bps', models.IntegerField(default=800)),
                ('bucket_merit_bps', models.IntegerField(default=800)),
                ('bucket_hardship_bps', models.IntegerField(default=900)),
                ('mas_weight_statement_of_faith', models.IntegerField(default=25)),
                ('mas_weight_church_involvement', models.IntegerField(default=20)),
                ('mas_weight_family_values', models.IntegerField(default=20)),
                ('mas_weight_pastoral_reference', models.IntegerField(default=15)),
                ('mas_weight_pog_preassessment', models.IntegerField(default=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_policies', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_policies', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
