$ErrorActionPreference = "Continue"

# tools/audit/make_workspace_index.ps1
# Generates an evidence-based workspace index pack for Crown2026.
# Safe-by-design: no secret values are emitted.

function Write-File($path, $content) {
  $dir = Split-Path -Parent $path
  if ($dir -and !(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $content | Out-File -FilePath $path -Encoding UTF8
}

function Add-File($path, $content) {
  $dir = Split-Path -Parent $path
  if ($dir -and !(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $content | Add-Content -Path $path -Encoding UTF8
}

$ts = Get-Date -Format "yyyyMMdd_HHmmss"
$pack = Join-Path $PWD ("AUDIT_PACK_{0}" -f $ts)
New-Item -ItemType Directory -Force -Path $pack | Out-Null

# 00 Overview
Write-File (Join-Path $pack "00_OVERVIEW.txt") @"
Crown2026 Audit Evidence Pack
Timestamp: $ts
Repo Root: $PWD
Generated by: tools/audit/make_workspace_index.ps1
Safety: No secret values are printed; secret findings are metadata-only.
"@

Add-File (Join-Path $pack "00_OVERVIEW.txt") "`n--- GIT STATUS ---"
try { Add-File (Join-Path $pack "00_OVERVIEW.txt") (git status -sb 2>&1 | Out-String) }
catch { Add-File (Join-Path $pack "00_OVERVIEW.txt") "git status failed" }

Add-File (Join-Path $pack "00_OVERVIEW.txt") "`n--- HEAD SHA ---"
try { Add-File (Join-Path $pack "00_OVERVIEW.txt") ((git rev-parse HEAD 2>&1 | Out-String).Trim()) }
catch { Add-File (Join-Path $pack "00_OVERVIEW.txt") "git rev-parse failed" }

Add-File (Join-Path $pack "00_OVERVIEW.txt") "`n--- LAST 20 COMMITS ---"
try { Add-File (Join-Path $pack "00_OVERVIEW.txt") (git --no-pager log --oneline -20 2>&1 | Out-String) }
catch { Add-File (Join-Path $pack "00_OVERVIEW.txt") "git log failed" }

# 01 Tree (exclude big/generated dirs)
Add-File (Join-Path $pack "01_TREE.txt") "Repo tree (excluding .git, .venv, node_modules, dist/build/coverage):"
$exclude = @('\\\.git\\', '\\\.venv\\', '\\node_modules\\', '\\dist\\', '\\build\\', '\\coverage\\')
Get-ChildItem -Recurse -File | Where-Object {
  $p = $_.FullName
  foreach ($x in $exclude) { if ($p -match $x) { return $false } }
  return $true
} | Sort-Object FullName | ForEach-Object {
  $_.FullName.Substring($PWD.Path.Length + 1)
} | Out-File (Join-Path $pack "01_TREE.txt") -Encoding UTF8

# 02 Workflows index
$wfDir = Join-Path $PWD ".github\workflows"
if (Test-Path $wfDir) {
  Get-ChildItem $wfDir -Filter "*.yml" | Sort-Object Name |
  ForEach-Object { $_.Name } | Out-File (Join-Path $pack "02_WORKFLOWS_INDEX.txt") -Encoding UTF8
}
else {
  Write-File (Join-Path $pack "02_WORKFLOWS_INDEX.txt") "No .github/workflows directory found."
}

# 03 Workflow triggers (raw grep â€” name only, no secret lines)
if (Test-Path $wfDir) {
  Select-String "$wfDir\*.yml" -Pattern '^(name:\s|on:\s)|pull_request:|push:|workflow_dispatch:|schedule:' |
  ForEach-Object { "$($_.Filename):$($_.LineNumber): $($_.Line.Trim())" } |
  Out-File (Join-Path $pack "03_WORKFLOWS_TRIGGERS.txt") -Encoding UTF8
}

# 04 Job-level IF (potential skip-neutral hazards)
if (Test-Path $wfDir) {
  Select-String "$wfDir\*.yml" -Pattern '^\s{4}if:\s' |
  ForEach-Object { "$($_.Filename):$($_.LineNumber): $($_.Line.Trim())" } |
  Out-File (Join-Path $pack "04_JOB_LEVEL_IF.txt") -Encoding UTF8
}

# 05 Branch protection (main) via GitHub API
$bp = Join-Path $pack "05_BRANCH_PROTECTION_MAIN.json"
$env:GH_PAGER = "cat"
try {
  $json = gh api repos/tcmegahan/Crown2026/branches/main/protection 2>&1
  Write-File $bp $json
}
catch {
  Write-File $bp "gh api branch protection failed."
}

# 06 Backend URLs
$urlsOut = Join-Path $pack "06_BACKEND_URLS.txt"
try {
  $urlCmdOutput = & ".venv\Scripts\python.exe" backend/manage.py show_urls 2>&1 | Out-String
  if ($urlCmdOutput -match "Unknown command:\s*'show_urls'" -or $urlCmdOutput -match "django-extensions") {
    Write-File $urlsOut "show_urls unavailable: django-extensions is not installed in the active venv."
  }
  elseif ([string]::IsNullOrWhiteSpace($urlCmdOutput)) {
    Write-File $urlsOut "show_urls produced no output."
  }
  else {
    Write-File $urlsOut $urlCmdOutput
  }
}
catch {
  Write-File $urlsOut "backend/manage.py show_urls failed (django-extensions may not be installed)."
}

# 07 Migrations
$migOut = Join-Path $pack "07_MIGRATIONS.txt"
try {
  & ".\.venv\Scripts\python.exe" backend/manage.py showmigrations --list 2>&1 | Out-File $migOut -Encoding UTF8
}
catch {
  Write-File $migOut "showmigrations failed."
}

# 08 Python deps
$pyDeps = Join-Path $pack "08_PY_DEPS.txt"
try {
  & ".\.venv\Scripts\python.exe" -m pip freeze 2>&1 | Out-File $pyDeps -Encoding UTF8
}
catch {
  Write-File $pyDeps "pip freeze failed."
}

# 09 Node deps (names only â€” no lockfile content)
$nodeDeps = Join-Path $pack "09_NODE_DEPS.txt"
$pkg = Join-Path $PWD "frontend\dashboards\package.json"
if (Test-Path $pkg) {
  Add-File $nodeDeps "--- package.json path ---"
  Add-File $nodeDeps $pkg
  Add-File $nodeDeps "`n--- lockfiles present ---"
  @("package-lock.json", "pnpm-lock.yaml", "yarn.lock") | ForEach-Object {
    $lf = Join-Path "frontend\dashboards" $_
    if (Test-Path $lf) { Add-File $nodeDeps $lf }
  }
  Add-File $nodeDeps "`n--- dependencies (names only) ---"
  try {
    $j = Get-Content $pkg -Raw | ConvertFrom-Json
    ($j.dependencies.PSObject.Properties.Name    | Sort-Object) | ForEach-Object { "dep:    $_" } | Add-Content $nodeDeps
    ($j.devDependencies.PSObject.Properties.Name | Sort-Object) | ForEach-Object { "devDep: $_" } | Add-Content $nodeDeps
  }
  catch { Add-File $nodeDeps "Failed to parse package.json" }
}
else {
  Write-File $nodeDeps "No frontend/dashboards/package.json found."
}

# 10 Secrets scan â€” metadata ONLY, never print values
$secOut = Join-Path $pack "10_SECRET_SCAN_FINDINGS.txt"
Write-File $secOut "Secret scan findings (metadata-only). No matched values are included.`n"

$patterns = @(
  @{ name = "PrivateKeyHeader"; re = "BEGIN (RSA|OPENSSH|EC|DSA|PRIVATE) KEY" },
  @{ name = "DjangoSecretKeyLiteral"; re = "SECRET_KEY\s*=\s*['""]" },
  @{ name = "DatabaseUrl"; re = "DATABASE_URL\s*=" },
  @{ name = "PasswordAssignment"; re = "password\s*=\s*['""]" },
  @{ name = "ApiKeyLike"; re = "api[_-]?key\s*=\s*['""]" },
  @{ name = "TokenLike"; re = "(token|jwt)\s*=\s*['""]" }
)

$scanExclude = '[/\\](\.git|\.venv|node_modules|dist|build|coverage|AUDIT_PACK_)[/\\]'
$textExts = @('.py', '.js', '.jsx', '.ts', '.tsx', '.json', '.yml', '.yaml', '.env', '.cfg', '.ini', '.toml', '.txt', '.md', '.sh', '.ps1', '.conf', '.html', '.css')
$allFiles = Get-ChildItem -Recurse -File -ErrorAction SilentlyContinue |
Where-Object { $_.FullName -notmatch $scanExclude -and $textExts -contains $_.Extension.ToLower() }

foreach ($p in $patterns) {
  $hits = 0
  foreach ($f in $allFiles) {
    try {
      $m = Select-String -Path $f.FullName -Pattern $p.re -AllMatches -Encoding UTF8 -ErrorAction SilentlyContinue
      if ($m) {
        foreach ($h in $m) {
          $rel = $h.Path.Substring($PWD.Path.Length + 1)
          # File + line + rule ONLY â€” no matched string, no line content
          Add-File $secOut ("- rule={0} file={1} line={2}" -f $p.name, $rel, $h.LineNumber)
          $hits++
        }
      }
    }
    catch { }
  }
  if ($hits -eq 0) { Add-File $secOut ("(0 hits) rule={0}" -f $p.name) }
  Add-File $secOut ""
}

# gitleaks (if installed) â†’ pipe through redact_gitleaks.py
$glCmd = Get-Command gitleaks -ErrorAction SilentlyContinue
Add-File $secOut "--- gitleaks ---"
if ($null -ne $glCmd) {
  $tmp = Join-Path $pack "gitleaks_raw.json"
  try {
    & gitleaks detect --source . --report-format json --report-path $tmp --no-git 2>$null | Out-Null
    $red = Get-Content $tmp -Raw | & ".\.venv\Scripts\python.exe" tools/audit/redact_gitleaks.py 2>&1
    Add-File $secOut $red
  }
  catch {
    Add-File $secOut "gitleaks installed but execution failed."
  }
}
else {
  Add-File $secOut "gitleaks not installed; pattern scan above is the only coverage."
}

# 11 Tracked binaries
$binOut = Join-Path $pack "11_TRACKED_BINARIES.txt"
$tracked = git ls-files 2>$null
if ($tracked) {
  $tracked | Where-Object {
    $_ -match '\.zip$|\.sqlite3$|\.db$|\.pem$|\.p12$|\.key$|\.crt$|\.cer$'
  } | Sort-Object | Out-File $binOut -Encoding UTF8
  if ((Get-Content $binOut -ErrorAction SilentlyContinue | Measure-Object -Line).Lines -le 1) {
    Add-File $binOut "(none found)"
  }
}
else {
  Write-File $binOut "git ls-files failed or empty."
}

# 12 Untracked artifacts (porcelain â€” no content, paths only)
$untrackedOut = Join-Path $pack "12_UNTRACKED_ARTIFACTS.txt"
try { git status --porcelain 2>&1 | Out-File $untrackedOut -Encoding UTF8 }
catch { Write-File $untrackedOut "git status --porcelain failed." }

# 13 Health probe (prod endpoint)
$healthOut = Join-Path $pack "13_HEALTH_PROBE.txt"
$healthUrl = "https://crown-api-prod.azurewebsites.net/api/health/"
Write-File $healthOut "Health probe: $healthUrl`n"
try {
  $ts2 = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  $resp = & curl.exe -sS --max-time 10 "$healthUrl`?nocache=$ts2" 2>&1
  Add-File $healthOut $resp
}
catch {
  Add-File $healthOut "curl health probe failed."
}

# Also probe /api/integrity/ while we're here
$integrityUrl = "https://crown-api-prod.azurewebsites.net/api/integrity/"
Add-File $healthOut "`n--- integrity probe: $integrityUrl ---"
try {
  $ts3 = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  $resp = & curl.exe -sS --max-time 10 "$integrityUrl`?nocache=$ts3" 2>&1
  Add-File $healthOut $resp
}
catch {
  Add-File $healthOut "curl integrity probe failed."
}

# 14 Recent prod deploy runs
$deployOut = Join-Path $pack "14_DEPLOY_PROD_RECENT.txt"
Write-File $deployOut "Recent deploy-prod.yml runs (metadata only).`n"
try {
  $env:GH_PAGER = "cat"
  $runs = gh run list --repo tcmegahan/Crown2026 --workflow deploy-prod.yml --limit 20 `
    --json databaseId,status,conclusion,headSha,createdAt,displayTitle --status completed 2>&1
  Add-File $deployOut $runs
}
catch {
  Add-File $deployOut "gh run list failed."
}

Write-Host ""
Write-Host "Audit pack written to: $pack" -ForegroundColor Green
Write-Host "Files generated:" -ForegroundColor Cyan
Get-ChildItem $pack | ForEach-Object { Write-Host "  $($_.Name)" }
Write-Host ""
Write-Host "Next: open Copilot Chat and paste:" -ForegroundColor Yellow
Write-Host "  Create a comprehensive NON-FIXING audit report using ONLY the evidence in $pack" -ForegroundColor Yellow

