# Generated by Django 6.0 on 2026-01-25 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household_name', models.CharField(max_length=255)),
                ('primary_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_city', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_state', models.CharField(blank=True, max_length=2, null=True)),
                ('primary_postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['household_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='crown_api.household')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='crown_api.person')),
            ],
            options={
                'ordering': ['person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('GUARDIAN', 'Guardian'), ('FINANCIALLY_RESPONSIBLE', 'Financially Responsible'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('AUTHORIZED_PICKUP', 'Authorized Pickup')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crown_api.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='crown_api.person')),
            ],
            options={
                'ordering': ['household', 'role', 'person__last_name', 'person__first_name'],
                'constraints': [models.UniqueConstraint(fields=('household', 'person', 'role'), name='uniq_household_person_role'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('role__in', ['PRIMARY_GUARDIAN', 'GUARDIAN'])), fields=('household',), name='uniq_household_primary_guardian')],
            },
        ),
    ]
