# Generated by Django 6.0 on 2026-01-25 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='crown_api.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User → Person Link',
                'verbose_name_plural': 'User → Person Links',
            },
        ),
    ]
