# Generated by Django 6.0 on 2026-01-25 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown_api', '0002_identity_user_person_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_grad_year', models.IntegerField(blank=True, null=True)),
                ('notes_public', models.TextField(blank=True, default='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='crown_api.student')),
            ],
            options={
                'ordering': ['student_number'],
            },
        ),
    ]
