# Generated by Django 6.0 on 2026-01-25 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown_api', '0004_course_graderecord_attendancerecord_courseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('VOID', 'Void')], default='OPEN', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crown_api.household')),
            ],
            options={
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(db_index=True, max_length=48, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('payment_date', models.DateField(db_index=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crown_api.household')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
