# Generated by Django 6.0 on 2026-01-25 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown_api', '0005_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_code', models.CharField(max_length=16)),
                ('name_override', models.CharField(blank=True, default='', max_length=128)),
                ('room', models.CharField(blank=True, default='', max_length=32)),
                ('meeting_days', models.CharField(blank=True, default='', max_length=16)),
                ('meeting_time', models.CharField(blank=True, default='', max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='crown_api.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_sections', to='crown_api.person')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='crown_api.term')),
            ],
            options={
                'ordering': ['term__code', 'course__course_code', 'section_code'],
            },
        ),
        migrations.CreateModel(
            name='SectionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='crown_api.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='crown_api.student')),
            ],
            options={
                'ordering': ['section', 'student__person__last_name'],
                'constraints': [models.UniqueConstraint(fields=('section', 'student'), name='uniq_section_enrollment_section_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('term', 'course', 'section_code'), name='uniq_term_course_section_code'),
        ),
    ]
