# Generated by Django 5.2.8 on 2026-02-16 07:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crown_api', '0007_messagethread_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=120, null=True)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
