# Generated by Django 5.2.8 on 2026-02-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seedrun'),
        ('crown_api', '0009_crownuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['course__course_code', 'student__last_name']},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='core.student'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='core.student'),
        ),
    ]
