# Generated by Django 5.2.8 on 2026-02-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seedrun'),
        ('crown_api', '0010_alter_courseenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionenrollment',
            options={'ordering': ['section', 'student__last_name']},
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='core.student'),
        ),
        migrations.AlterField(
            model_name='sectionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='core.student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.student'),
        ),
    ]
