import { expect, test, type Page } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const BASE = process.env.CROWN_UI_URL ?? process.env.VITE_DEV_BASE_URL ?? 'http://localhost:4173';

const PROOF_DIR = path.resolve(
  process.cwd(),
  '..',
  '..',
  'audit-artifacts',
  'dashboard-completion',
  'browser-proof',
  'batch0',
  'dashboard-certification-center_20260620_authorized'
);

async function seedAuthorizedRole(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const role = 'super_admin';
    const roles = ['super_admin', 'crown_platform_ops', 'crown_compliance', 'master_control'];
    const schoolId = '19801b59-8c05-4c84-9312-5d792e4e839d';
    const user = {
      role,
      roles,
      primaryRole: role,
      school_id: schoolId,
    };

    sessionStorage.setItem('crown.role', role);
    sessionStorage.setItem('crown_user', JSON.stringify(user));
    sessionStorage.setItem('crown_current_user', JSON.stringify(user));

    localStorage.setItem('crown.role', role);
    localStorage.setItem('crown.demo.role', role);
    localStorage.setItem('crown_user', JSON.stringify(user));
    localStorage.setItem('crown_current_user', JSON.stringify(user));
    localStorage.setItem('crown_user_roles', JSON.stringify(roles));
    localStorage.setItem('crown.school.id', schoolId);
    localStorage.setItem('schoolId', schoolId);
    localStorage.setItem('school_id', schoolId);

    sessionStorage.setItem('crown.school.id', schoolId);
    sessionStorage.setItem('schoolId', schoolId);
    sessionStorage.setItem('school_id', schoolId);

    globalThis.__CROWN_USER_ROLES__ = roles;
  });
}

test('dashboard-certification-center renders with an authorized platform role', async ({ page }) => {
  const consoleErrors: string[] = [];
  const apiFailures: string[] = [];

  await page.route('**/favicon.ico', async (route) => {
    await route.fulfill({ status: 204, body: '' });
  });
  await page.route('**/api/v1/dashboards/dashboard-certification-center/summary**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        dashboards_certified: 0,
        dashboards_mapped_only: 40,
        pending_review: 0,
        certification_rate: 0,
      }),
    });
  });

  page.on('pageerror', (error) => consoleErrors.push(`[pageerror] ${error.message}`));
  page.on('console', (message) => {
    if (message.type() === 'error') {
      consoleErrors.push(`[console.error] ${message.text()}`);
    }
  });
  page.on('response', (response) => {
    const status = response.status();
    if (status >= 500) {
      apiFailures.push(`${status} ${response.url()}`);
    }
  });

  await seedAuthorizedRole(page);
  await page.goto(`${BASE}/dashboard-certification-center`, { waitUntil: 'networkidle' });

  await expect(page).toHaveURL(/\/dashboard-certification-center$/);
  await expect(page.getByText('Access Restricted')).toHaveCount(0);
  await expect(page.locator('h1, h2, h3, h4, h5, h6').first()).toBeVisible();
  await expect(page.locator('body')).toContainText(/Certification Center|Dashboard Certification/i);

  const h1 = (await page.locator('h1').first().textContent().catch(() => null))?.trim() ?? null;
  const title = await page.title();

  await mkdir(PROOF_DIR, { recursive: true });
  await page.screenshot({
    path: path.join(PROOF_DIR, 'dashboard-certification-center-fullpage.png'),
    fullPage: true,
  });

  const proof = {
    captured_at: new Date().toISOString(),
    url: page.url(),
    title,
    h1,
    seeded_roles: ['super_admin', 'crown_platform_ops', 'crown_compliance', 'master_control'],
    access_restricted: false,
    console_errors: consoleErrors,
    api_5xx_failures: apiFailures,
    screenshot: 'dashboard-certification-center-fullpage.png',
    note: 'Generated by Playwright with a role accepted by RoleRouteGuard.',
  };

  await writeFile(path.join(PROOF_DIR, 'browser-proof.json'), `${JSON.stringify(proof, null, 2)}\n`, 'utf8');

  expect(consoleErrors).toEqual([]);
  expect(apiFailures).toEqual([]);
});
