"""
Django settings for crown_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
import logging
import secrets
import sys
from datetime import timedelta
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from crown_api.wizard_registry import WIZARD_INSTALLED_APPS  # single source of truth


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_list(name: str) -> list[str]:
    value = os.getenv(name)
    if not value:
        return []
    parts = [p.strip() for p in value.replace(";", ",").split(",")]
    return [p for p in parts if p]


def required_env(name: str) -> str:
    value = os.getenv(name)
    if value is None or not value.strip():
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Dev API open toggle (development only). Default closed when running on Azure.
_is_azure = bool(os.getenv("WEBSITE_HOSTNAME") or os.getenv("WEBSITE_INSTANCE_ID"))
CROWN_DEV_OPEN_API = _env_bool("CROWN_DEV_OPEN_API", default=not _is_azure)

# SOLOMON read-only API gate. Keep closed until Phase 3 is explicitly enabled.
CROWN_SOLOMON_API_ENABLED = _env_bool("CROWN_SOLOMON_API_ENABLED", default=False)

# SOLOMON internal context consumption gate. Separate from API gate.
CROWN_SOLOMON_CONTEXT_ENABLED = _env_bool("CROWN_SOLOMON_CONTEXT_ENABLED", default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY")
if not _secret_key_env:
    # In any non-debug / Azure context, refuse to start with the insecure fallback.
    _would_be_debug = _env_bool("DJANGO_DEBUG", default=(False if _is_azure else True)) or _env_bool("DEBUG", default=False)
    if _is_azure or not _would_be_debug:
        raise ImproperlyConfigured(
            "Missing required environment variable: DJANGO_SECRET_KEY. "
            "Set DJANGO_SECRET_KEY in your environment before starting the server."
        )
    # Local dev only — insecure fallback is acceptable when DEBUG=True and not on Azure.
    _secret_key_env = "django-insecure-77tws%k1#a!#aio14%6=4z6wn@_nrnu1d$(bur5-!2$-8+l$d2"
SECRET_KEY = _secret_key_env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=(False if _is_azure else True)) or _env_bool(
    "DEBUG", default=False
)

# ALLOWED_HOSTS configuration
_django_env = os.getenv("DJANGO_ENV", "").lower()
_allowed_hosts = _env_list("ALLOWED_HOSTS") or _env_list("DJANGO_ALLOWED_HOSTS")

# DEV: Allow all hosts to avoid Azure health probe crashes (169.254.x.x IPs)
if _django_env in ("dev", "development"):
    _allowed_hosts = ["*"]
elif not _allowed_hosts and _is_azure:
    # PROD/other: infer from WEBSITE_HOSTNAME
    hostname = os.getenv("WEBSITE_HOSTNAME")
    if hostname:
        _allowed_hosts = [hostname]

# Always allow localhost for local development
if _allowed_hosts != ["*"] and "localhost" not in _allowed_hosts:
    _allowed_hosts = (_allowed_hosts or []) + ["localhost", "127.0.0.1"]

# Ensure Django test client works in CI
if "testserver" not in (_allowed_hosts or []):
    _allowed_hosts = list(_allowed_hosts or []) + ["testserver"]

ALLOWED_HOSTS = _allowed_hosts

# --- CSRF trusted origins (Azure-safe) ---
_raw = os.getenv("CSRF_TRUSTED_ORIGINS", "")

if _raw.startswith("["):
    CSRF_TRUSTED_ORIGINS = json.loads(_raw)
elif _raw:
    CSRF_TRUSTED_ORIGINS = [_raw]
else:
    CSRF_TRUSTED_ORIGINS = []

# Production flag guard -- raises RuntimeError if a dangerous flag is enabled with DEBUG=False.
def _assert_not_prod_true(flag_name: str, flag_value: bool) -> None:
    if not DEBUG and bool(flag_value):
        raise RuntimeError(f"{flag_name} cannot be enabled in production.")

# CORS configuration for local development
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = True
_assert_not_prod_true("CORS_ALLOW_ALL_ORIGINS", CORS_ALLOW_ALL_ORIGINS)
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-school-id",
    "x-crown-school-id",
    "x-demo-key",
]

# Azure reverse-proxy HTTPS handling
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Environment and ops secret (expose as settings attributes for system views)
CROWN_ENV = os.getenv("CROWN_ENV", "")

# Demo mode settings
# Requires explicit CROWN_DEMO_MODE=true env var to enable.
# When enabled, DemoWriteBlockMiddleware blocks all mutating requests.
CROWN_DEMO_MODE = _env_bool("CROWN_DEMO_MODE", default=False)
_assert_not_prod_true("CROWN_DEMO_MODE", CROWN_DEMO_MODE)
CROWN_DEMO_KEY = os.getenv("CROWN_DEMO_KEY", "CrownDemoKey!2026" if DEBUG else "")

# Tenant header enforcement
# When True, TenantHeaderRequiredMiddleware requires X-School-Id on /api/v1/* routes.
TENANT_HEADER_REQUIRED = _env_bool("TENANT_HEADER_REQUIRED", default=True)
CROWN_DEMO_SCHOOL_ID = os.getenv("CROWN_DEMO_SCHOOL_ID", "19801b59-8c05-4c84-9312-5d792e4e839d")
DJANGO_ENV = os.getenv("DJANGO_ENV", "")
CROWN_OPS_SECRET = os.getenv("CROWN_OPS_SECRET", "") or os.getenv("OPS_SECRET", "")
ENVIRONMENT = os.getenv("ENVIRONMENT", "")
DEV_OPS_SECRET = os.getenv("DEV_OPS_SECRET", "")

COMPUWERX_BASE_URL = os.getenv("COMPUWERX_BASE_URL", "https://sandbox.compuwerx.example")
COMPUWERX_API_KEY = os.getenv("COMPUWERX_API_KEY", "")
COMPUWERX_WEBHOOK_SECRET = os.getenv("COMPUWERX_WEBHOOK_SECRET", "")
COMPUWERX_TIMEOUT_SECONDS = int(os.getenv("COMPUWERX_TIMEOUT_SECONDS", "30"))

# Build SHA for deployment determinism proof (Gate 1C)
BUILD_SHA = os.getenv("BUILD_SHA") or os.getenv("GITHUB_SHA") or "local-dev"

# ---------------------------------------------------------------------------
# Disaster Recovery configuration (Stage 1 -- Production Hardening)
# ---------------------------------------------------------------------------
CROWN_RTO_HOURS = int(os.getenv("CROWN_RTO_HOURS", "4"))       # Recovery Time Objective
CROWN_RPO_HOURS = int(os.getenv("CROWN_RPO_HOURS", "1"))       # Recovery Point Objective
CROWN_BACKUP_BUCKET = os.getenv("CROWN_BACKUP_BUCKET", "crown-backups")
CROWN_BACKUP_RETENTION_DAYS = int(os.getenv("CROWN_BACKUP_RETENTION_DAYS", "30"))
# Grace period before delinquent households are suspended (Stage 2)
CROWN_GRACE_PERIOD_DAYS = int(os.getenv("CROWN_GRACE_PERIOD_DAYS", "30"))


# Application definition

INSTALLED_APPS = [
'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'crown_api',
    'crown_api.exports',
    'core',
    'curriculum',
    'apps.compliance.apps.ComplianceConfig',
    'apps.accounting.apps.AccountingConfig',
    'finance.apps.FinanceConfig',
    'aid.apps.AidConfig',
    'admissions.apps.AdmissionsConfig',
    'households',
    'applications',
    'learning_continuity.apps.LearningContinuityConfig',
    'ledger.apps.LedgerConfig',
    'journal',
    'integrations',
    'financial_aid.apps.FinancialAidConfig',
    'academics',
    'academics_ro',
    'curricula',
    'classroom',
    'gradebook',
    'billing',
    'audit',  # Production audit logging
    'solomon',
    'discipline',  # Discipline incidents & actions
    'servicehours',  # Service hours tracking & approvals
    'comms',
    'student_records.apps.StudentRecordsConfig',
    'student360',
    'parent360',
    'executive360',
    'graduation',
    'hr.apps.HrConfig',
    'advancement.apps.AdvancementConfig',
    'pdhub.apps.PdhubConfig',
    'safety.apps.SafetyConfig',
    'integrations_real.apps.IntegrationsRealConfig',
    'spiritual_life.apps.SpiritualLifeConfig',
    'portrait.apps.PortraitConfig',
    'outreach.apps.OutreachConfig',
    'athletics.apps.AthleticsConfig',
    'facops.apps.FacopsConfig',
    'transportation.apps.TransportationConfig',
    'msauth.apps.MsauthConfig',
    'board_oversight',
    # Platform layer (multi-tenant SaaS scaling)
    'tenants.apps.TenantsConfig',
    'platform_ops.apps.PlatformOpsConfig',
    'payments.apps.PaymentsConfig',
    # Subscriptions & Entitlements
    'subscriptions.apps.SubscriptionsConfig',
    # Signal Engine + Crown Compass 2.0 + Intervention Workflow
    'signals',
    # Aftercare Module
    'aftercare',
    # Summer Camp Module
    'summer_camp',
    # Home Academy / Homeschool Affiliation Module
    'home_academy.apps.HomeAcademyConfig',
    # Finance Setup (Policy Wizard)
    'finance_setup.apps.FinanceSetupConfig',
    # Stage 5 -- Org Scalability (onboarding already in WIZARD_INSTALLED_APPS)
    'support.apps.SupportConfig',
    'analytics.apps.AnalyticsConfig',
]
INSTALLED_APPS += WIZARD_INSTALLED_APPS  # wizard SDK: single source of truth in wizard_registry.py

MIDDLEWARE = [
    'core.middleware.DemoWriteBlockMiddleware',
    'crown_api.middleware.api_exceptions.ApiExceptionMiddleware',  # Exception envelope (outermost)
    'crown_api.middleware.performance.PerformanceMiddleware',  # Performance timing
    'crown_api.middleware.api_version.APIVersionMiddleware',   # API deprecation headers
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantIsolationMiddleware',
    'crown_api.auth_middleware.JwtAuthMiddleware',  # JWT authentication (after Django auth, coexists with SimpleJWT)
    'core.tenant_header_middleware.TenantHeaderRequiredMiddleware',  # Tenant guard -- after auth so user.school_id is available for header-less fallback
    'crown_api.tenant_middleware.TenantContextMiddleware',  # Tenant resolution (after JWT auth)
    'audit.middleware.AuditMiddleware',  # Audit logging (after auth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crown_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'crown_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,
        )
    }
elif not DEBUG:
    raise ImproperlyConfigured("Missing required environment variable: DATABASE_URL")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
