"""
Django settings for crown_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
import logging
import secrets
import sys
from datetime import timedelta
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from crown_api.wizard_registry import WIZARD_INSTALLED_APPS  # single source of truth


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_list(name: str) -> list[str]:
    value = os.getenv(name)
    if not value:
        return []
    parts = [p.strip() for p in value.replace(";", ",").split(",")]
    return [p for p in parts if p]


def required_env(name: str) -> str:
    value = os.getenv(name)
    if value is None or not value.strip():
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Dev API open toggle (development only). Default closed when running on Azure.
_is_azure = bool(os.getenv("WEBSITE_HOSTNAME") or os.getenv("WEBSITE_INSTANCE_ID"))
CROWN_DEV_OPEN_API = _env_bool("CROWN_DEV_OPEN_API", default=not _is_azure)

# SOLOMON read-only API gate. Keep closed until Phase 3 is explicitly enabled.
CROWN_SOLOMON_API_ENABLED = _env_bool("CROWN_SOLOMON_API_ENABLED", default=False)

# SOLOMON internal context consumption gate. Separate from API gate.
CROWN_SOLOMON_CONTEXT_ENABLED = _env_bool("CROWN_SOLOMON_CONTEXT_ENABLED", default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY")
if not _secret_key_env:
    # In any non-debug / Azure context, refuse to start with the insecure fallback.
    _would_be_debug = _env_bool("DJANGO_DEBUG", default=(False if _is_azure else True)) or _env_bool("DEBUG", default=False)
    if _is_azure or not _would_be_debug:
        raise ImproperlyConfigured(
            "Missing required environment variable: DJANGO_SECRET_KEY. "
            "Set DJANGO_SECRET_KEY in your environment before starting the server."
        )
    # Local dev only — generate an ephemeral secret when DEBUG=True and not on Azure.
    _secret_key_env = secrets.token_urlsafe(64)
SECRET_KEY = _secret_key_env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=(False if _is_azure else True)) or _env_bool(
    "DEBUG", default=False
)

# ALLOWED_HOSTS configuration
_django_env = os.getenv("DJANGO_ENV", "").lower()
_allowed_hosts = _env_list("ALLOWED_HOSTS") or _env_list("DJANGO_ALLOWED_HOSTS")

# DEV: Allow all hosts to avoid Azure health probe crashes (169.254.x.x IPs)
if _django_env in ("dev", "development"):
    _allowed_hosts = ["*"]
elif not _allowed_hosts and _is_azure:
    # PROD/other: infer from WEBSITE_HOSTNAME
    hostname = os.getenv("WEBSITE_HOSTNAME")
    if hostname:
        _allowed_hosts = [hostname]

# Always allow localhost for local development
if _allowed_hosts != ["*"] and "localhost" not in _allowed_hosts:
    _allowed_hosts = (_allowed_hosts or []) + ["localhost", "127.0.0.1"]

# Ensure Django test client works in CI
if "testserver" not in (_allowed_hosts or []):
    _allowed_hosts = list(_allowed_hosts or []) + ["testserver"]

ALLOWED_HOSTS = _allowed_hosts

# --- CSRF trusted origins (Azure-safe) ---
_raw = os.getenv("CSRF_TRUSTED_ORIGINS", "")

if _raw.startswith("["):
    CSRF_TRUSTED_ORIGINS = json.loads(_raw)
elif _raw:
    CSRF_TRUSTED_ORIGINS = [_raw]
else:
    CSRF_TRUSTED_ORIGINS = []

# Production flag guard -- raises RuntimeError if a dangerous flag is enabled with DEBUG=False.
def _assert_not_prod_true(flag_name: str, flag_value: bool) -> None:
    if not DEBUG and bool(flag_value):
        raise RuntimeError(f"{flag_name} cannot be enabled in production.")

# CORS configuration for local development
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = True
_assert_not_prod_true("CORS_ALLOW_ALL_ORIGINS", CORS_ALLOW_ALL_ORIGINS)
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-school-id",
    "x-crown-school-id",
    "x-demo-key",
]

# Azure reverse-proxy HTTPS handling
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Environment and ops secret (expose as settings attributes for system views)
CROWN_ENV = os.getenv("CROWN_ENV", "")

# Demo mode settings
# Requires explicit CROWN_DEMO_MODE=true env var to enable.
# When enabled, DemoWriteBlockMiddleware blocks all mutating requests.
CROWN_DEMO_MODE = _env_bool("CROWN_DEMO_MODE", default=False)
_assert_not_prod_true("CROWN_DEMO_MODE", CROWN_DEMO_MODE)
CROWN_DEMO_KEY = os.getenv("CROWN_DEMO_KEY", "CrownDemoKey!2026" if DEBUG else "")

# Tenant header enforcement
# When True, TenantHeaderRequiredMiddleware requires X-School-Id on /api/v1/* routes.
TENANT_HEADER_REQUIRED = _env_bool("TENANT_HEADER_REQUIRED", default=True)
CROWN_DEMO_SCHOOL_ID = os.getenv("CROWN_DEMO_SCHOOL_ID", "19801b59-8c05-4c84-9312-5d792e4e839d")
DJANGO_ENV = os.getenv("DJANGO_ENV", "")
CROWN_OPS_SECRET = os.getenv("CROWN_OPS_SECRET", "") or os.getenv("OPS_SECRET", "")
ENVIRONMENT = os.getenv("ENVIRONMENT", "")
DEV_OPS_SECRET = os.getenv("DEV_OPS_SECRET", "")

COMPUWERX_BASE_URL = os.getenv("COMPUWERX_BASE_URL", "https://sandbox.compuwerx.example")
COMPUWERX_API_KEY = os.getenv("COMPUWERX_API_KEY", "")
COMPUWERX_WEBHOOK_SECRET = os.getenv("COMPUWERX_WEBHOOK_SECRET", "")
COMPUWERX_TIMEOUT_SECONDS = int(os.getenv("COMPUWERX_TIMEOUT_SECONDS", "30"))

# Build SHA for deployment determinism proof (Gate 1C)
BUILD_SHA = os.getenv("BUILD_SHA") or os.getenv("GITHUB_SHA") or "local-dev"

# ---------------------------------------------------------------------------
# Disaster Recovery configuration (Stage 1 -- Production Hardening)
# ---------------------------------------------------------------------------
CROWN_RTO_HOURS = int(os.getenv("CROWN_RTO_HOURS", "4"))       # Recovery Time Objective
CROWN_RPO_HOURS = int(os.getenv("CROWN_RPO_HOURS", "1"))       # Recovery Point Objective
CROWN_BACKUP_BUCKET = os.getenv("CROWN_BACKUP_BUCKET", "crown-backups")
CROWN_BACKUP_RETENTION_DAYS = int(os.getenv("CROWN_BACKUP_RETENTION_DAYS", "30"))
# Grace period before delinquent households are suspended (Stage 2)
CROWN_GRACE_PERIOD_DAYS = int(os.getenv("CROWN_GRACE_PERIOD_DAYS", "30"))


# Application definition

INSTALLED_APPS = [
'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'crown_api',
    'crown_api.exports',
    'core',
    'sandbox_demo.apps.SandboxDemoConfig',
    'curriculum',
    'apps.compliance.apps.ComplianceConfig',
    'apps.accounting.apps.AccountingConfig',
    'finance.apps.FinanceConfig',
    'aid.apps.AidConfig',
    'admissions.apps.AdmissionsConfig',
    'households',
    'applications',
    'learning_continuity.apps.LearningContinuityConfig',
    'ledger.apps.LedgerConfig',
    'journal',
    'integrations',
    'financial_aid.apps.FinancialAidConfig',
    'academics',
    'academics_ro',
    'curricula',
    'classroom',
    'gradebook',
    'billing',
    'audit',  # Production audit logging
    'solomon',
    'discipline',  # Discipline incidents & actions
    'servicehours',  # Service hours tracking & approvals
    'comms',
    'student_records.apps.StudentRecordsConfig',
    'student360',
    'parent360',
    'executive360',
    'graduation',
    'hr.apps.HrConfig',
    'advancement.apps.AdvancementConfig',
    'pdhub.apps.PdhubConfig',
    'safety.apps.SafetyConfig',
    'integrations_real.apps.IntegrationsRealConfig',
    'spiritual_life.apps.SpiritualLifeConfig',
    'portrait.apps.PortraitConfig',
    'outreach.apps.OutreachConfig',
    'athletics.apps.AthleticsConfig',
    'facops.apps.FacopsConfig',
    'transportation.apps.TransportationConfig',
    'msauth.apps.MsauthConfig',
    'board_oversight',
    # Platform layer (multi-tenant SaaS scaling)
    'tenants.apps.TenantsConfig',
    'platform_ops.apps.PlatformOpsConfig',
    'payments.apps.PaymentsConfig',
    # Subscriptions & Entitlements
    'subscriptions.apps.SubscriptionsConfig',
    # Signal Engine + Crown Compass 2.0 + Intervention Workflow
    'signals',
    # Aftercare Module
    'aftercare',
    # Summer Camp Module
    'summer_camp',
    # Home Academy / Homeschool Affiliation Module
    'home_academy.apps.HomeAcademyConfig',
    # Finance Setup (Policy Wizard)
    'finance_setup.apps.FinanceSetupConfig',
    # Stage 5 -- Org Scalability (onboarding already in WIZARD_INSTALLED_APPS)
    'support.apps.SupportConfig',
    'analytics.apps.AnalyticsConfig',
]
INSTALLED_APPS += WIZARD_INSTALLED_APPS  # wizard SDK: single source of truth in wizard_registry.py

# Use the project's custom user model defined in core.models.
AUTH_USER_MODEL = 'core.UserAccount'

MIDDLEWARE = [
    'core.middleware.DemoWriteBlockMiddleware',
    'crown_api.middleware.api_exceptions.ApiExceptionMiddleware',  # Exception envelope (outermost)
    'crown_api.middleware.performance.PerformanceMiddleware',  # Performance timing
    'crown_api.middleware.api_version.APIVersionMiddleware',   # API deprecation headers
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantIsolationMiddleware',
    'crown_api.auth_middleware.JwtAuthMiddleware',  # JWT authentication (after Django auth, coexists with SimpleJWT)
    'core.tenant_header_middleware.TenantHeaderRequiredMiddleware',  # Tenant guard -- after auth so user.school_id is available for header-less fallback
    'crown_api.tenant_middleware.TenantContextMiddleware',  # Tenant resolution (after JWT auth)
    'audit.middleware.AuditMiddleware',  # Audit logging (after auth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crown_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'crown_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,
        )
    }
elif not DEBUG:
    raise ImproperlyConfigured("Missing required environment variable: DATABASE_URL")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --- DRF renderer policy (PROD: JSON-only; non-PROD: JSON + Browsable) ---
def _env_is_prod() -> bool:
    v = (
        os.getenv("CROWN_ENV")
        or os.getenv("DJANGO_ENV")
        or os.getenv("ENVIRONMENT")
        or os.getenv("APP_ENV")
        or ""
    ).strip().lower()
    return v in {"prod", "production", "live"}

DRF_DEFAULT_RENDERERS = (
    ("rest_framework.renderers.JSONRenderer",)
    if _env_is_prod()
    else (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    )
)

# DRF Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # JWT first ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â its authenticate_header() returns 'Bearer realm="api"'
        # which causes DRF to emit 401 (not 403) for unauthenticated requests.
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Microsoft Entra ID bearer tokens (MSAL frontend)
        "core.auth.authentication.AADBearerAuthentication",
        # Django session (server-side OAuth2 / msauth flow)
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": DRF_DEFAULT_RENDERERS,
    "DEFAULT_THROTTLE_RATES": {
        # Exports-only throttling scopes (applied per-view via throttle_classes).
        "exports_user_minute": "30/min",
        "exports_user_hour": "120/hour",
        # Per-IP safety net. Keep generous to avoid harming shared networks.
        "exports_ip_minute": "60/min",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Crown API",
    "DESCRIPTION": (
        "Investor review and partner integration surface for Crown. "
        "Purpose-built for Christian and faith-based private schools."
    ),
    "VERSION": "1.0.0-rc1",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}


# Households app configuration
HOUSEHOLDS_GUARDIAN_SCOPE_ENABLED = True


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Authentication redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/director/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ---------------------------------------------------------------------------
# Microsoft SSO (msauth app)
# ---------------------------------------------------------------------------
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")

# Secure session cookies ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â HTTPS required in prod, relaxed in dev
SESSION_COOKIE_SECURE   = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE      = not DEBUG

# Production integrity lock ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â demo bypass disabled unconditionally
ALLOW_DEMO_ROLE_HEADER = False

# ---------------------------------------------------------------------------
# HTTPS / SSL hardening
# ---------------------------------------------------------------------------
SECURE_SSL_REDIRECT             = _env_is_prod()
SECURE_HSTS_SECONDS             = 31536000 if _env_is_prod() else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
SECURE_HSTS_PRELOAD             = True
SECURE_CONTENT_TYPE_NOSNIFF     = True
SECURE_BROWSER_XSS_FILTER       = True
X_FRAME_OPTIONS                 = "DENY"

# ---------------------------------------------------------------------------
# Database SSL enforcement (PostgreSQL prod only)
# ---------------------------------------------------------------------------
if DATABASE_URL and _env_is_prod():
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["sslmode"] = "require"

# ---------------------------------------------------------------------------
# Azure AD / Entra ID settings
# ---------------------------------------------------------------------------
AAD_TENANT_ID    = os.getenv("AAD_TENANT_ID", os.getenv("AZURE_TENANT_ID", ""))
AAD_API_AUDIENCE = os.getenv("AAD_API_AUDIENCE", "")  # api://<api-app-client-id>

# Microsoft Graph sender ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â REQUIRED in production for outbox email delivery.
# Must match the licensed M365 mailbox UPN (e.g. no-reply@yourdomain.com).
# Celery drain_outbox will hard-fail at startup if this is empty.
GRAPH_FROM_USER  = os.getenv("GRAPH_FROM_USER", "")

# ---------------------------------------------------------------------------
# Sentry telemetry (production only)
# ---------------------------------------------------------------------------
if _env_is_prod():
    _sentry_dsn = os.getenv("SENTRY_DSN", "")
    if _sentry_dsn:
        try:
            import sentry_sdk
            from sentry_sdk.integrations.django import DjangoIntegration
            sentry_sdk.init(
                dsn=_sentry_dsn,
                integrations=[DjangoIntegration()],
                traces_sample_rate=0.2,
                send_default_pii=False,
                release=BUILD_SHA,
            )
        except ImportError:
            logging.getLogger(__name__).debug("sentry-sdk not installed; skipping Sentry init")

# ---------------------------------------------------------------------------
# Structured logging ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â crown.audit + request log
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "crown.audit": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "crown.performance": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# ---------------------------------------------------------------------------
# Celery (background tasks / outbox drain)
# ---------------------------------------------------------------------------
CELERY_BROKER_URL              = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND          = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_TASK_ACKS_LATE          = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SERIALIZER         = "json"
CELERY_RESULT_SERIALIZER       = "json"
CELERY_ACCEPT_CONTENT          = ["json"]
CELERY_TIMEZONE                = TIME_ZONE

try:
    from celery.schedules import crontab  # noqa: F401
    CELERY_BEAT_SCHEDULE = {
        "drain-outbox-every-10-seconds": {
            "task": "comms.tasks.drain_outbox",
            "schedule": 10.0,
        },
        # Stage 2 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â Revenue Integrity automation
        "dunning-cycle-every-30-minutes": {
            "task": "ledger.tasks.run_dunning_cycle",
            "schedule": crontab(minute="*/30"),
        },
        "daily-payout-audit-0100-utc": {
            "task": "ledger.tasks.run_daily_payout_audit",
            "schedule": crontab(hour=1, minute=0),
        },
        "enforce-grace-period-0300-utc": {
            "task": "billing.tasks.enforce_grace_period",
            "schedule": crontab(hour=3, minute=0),
        },
        # Stage 1 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â Data retention purge (02:00 UTC daily)
        "retention-purge-0200-utc": {
            "task": "core.tasks.purge_expired_records",
            "schedule": crontab(hour=2, minute=0),
        },
        # Stage 5 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â SLA escalation check (every hour)
        "sla-escalation-hourly": {
            "task": "support.tasks.escalate_overdue_tickets",
            "schedule": crontab(minute=0),
        },
        # Stage 5 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â Predictive analytics nightly run (02:00 UTC daily)
        "predictive-analytics-0200-utc": {
            "task": "analytics.tasks.run_predictive_analytics_nightly",
            "schedule": crontab(hour=2, minute=0),
        },
        # Stage 5 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â Customer health scoring (03:30 UTC daily)
        "customer-health-0330-utc": {
            "task": "analytics.tasks.refresh_all_health_scores",
            "schedule": crontab(hour=3, minute=30),
        },
    }
except ImportError:
    logging.getLogger(__name__).debug("Celery not installed; beat schedule omitted")

# ---------------------------------------------------------------------------
# CORS: explicit allowed list enforced (no allow-all in prod)
# ---------------------------------------------------------------------------
_cors_origins_raw = os.getenv("CORS_ALLOWED_ORIGINS", "")
if _cors_origins_raw:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_raw.split(",") if o.strip()]

# ---------------------------------------------------------------------------
# Advancement payment provider
# Supported values: "fake" (default, dev/test), future: "stripe"
# ---------------------------------------------------------------------------
ADVANCEMENT_PAYMENT_PROVIDER = os.getenv("ADVANCEMENT_PAYMENT_PROVIDER", "fake")
ADVANCEMENT_CURRENCY = os.getenv("ADVANCEMENT_CURRENCY", "usd")
# Stage 3.2 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ Stripe Checkout integration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
# Public-facing URLs used in Stripe success/cancel redirects
PUBLIC_APP_BASE_URL = os.getenv("PUBLIC_APP_BASE_URL", "http://localhost:5173")
PUBLIC_API_BASE_URL = os.getenv("PUBLIC_API_BASE_URL", "http://localhost:8000")

# Stage 3.4 ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ Receipts, donation upsell, sponsor assets, Wallet passes
RECEIPTS_FROM_EMAIL = os.getenv("RECEIPTS_FROM_EMAIL", "no-reply@school.invalid")
DONATION_PRESETS_USD = os.getenv("DONATION_PRESETS_USD", "10,25,50")   # CSV of integer dollar amounts
SPONSOR_ASSET_BASE_URL = os.getenv("SPONSOR_ASSET_BASE_URL", "http://localhost:8000/media/")

# Apple Wallet (PassKit) ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ all must be set in production; empty = returns 501
APPLE_PASS_TYPE_IDENTIFIER = os.getenv("APPLE_PASS_TYPE_IDENTIFIER", "")   # pass.com.yourorg.crown
APPLE_TEAM_IDENTIFIER = os.getenv("APPLE_TEAM_IDENTIFIER", "")
APPLE_PASS_CERT_P12_PATH = os.getenv("APPLE_PASS_CERT_P12_PATH", "")       # secure path, never in repo
APPLE_PASS_CERT_P12_PASSWORD = os.getenv("APPLE_PASS_CERT_P12_PASSWORD", "")
APPLE_WWDR_PEM_PATH = os.getenv("APPLE_WWDR_PEM_PATH", "")                 # Apple WWDR G4 pem
APPLE_PASS_SERVICE_URL = os.getenv("APPLE_PASS_SERVICE_URL", "http://apple-pass:7071/pkpass")

# Google Wallet ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ both must be set in production; empty = returns 501
GOOGLE_WALLET_ISSUER_ID = os.getenv("GOOGLE_WALLET_ISSUER_ID", "")
GOOGLE_WALLET_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_WALLET_SERVICE_ACCOUNT_JSON", "")  # JSON string or file path
GOOGLE_WALLET_BASE_URL = os.getenv("GOOGLE_WALLET_BASE_URL", "https://pay.google.com/gp/v/save/")

import importlib.util
import sys
if str(BASE_DIR.parent) not in sys.path:
    sys.path.append(str(BASE_DIR.parent))

INSTALLED_APPS = globals().get("INSTALLED_APPS", [])
if importlib.util.find_spec("release_closeout") and "release_closeout" not in INSTALLED_APPS:
    INSTALLED_APPS.append("release_closeout")

INSTALLED_APPS = globals().get("INSTALLED_APPS", INSTALLED_APPS if "INSTALLED_APPS" in globals() else [])
if "django_extensions" not in INSTALLED_APPS:
    INSTALLED_APPS.append("django_extensions")
# === CROWN DEPLOY SECURITY SETTINGS START ===
# Used for staging/sandbox/production deploy-readiness checks.
# No secret is stored here. A real DJANGO_SECRET_KEY must be supplied by the environment.
import os as _crown_os

_CROWN_TRUE_VALUES = {"1", "true", "yes", "on"}
_CROWN_ENV = _crown_os.getenv("CROWN_ENV", "").strip().lower()
_CROWN_IS_DEPLOY_CHECK = "--deploy" in sys.argv
_CROWN_DEPLOY_SECURITY = (
    _crown_os.getenv("CROWN_DEPLOY_SECURITY", "").strip().lower() in _CROWN_TRUE_VALUES
    or _CROWN_ENV in {"sandbox", "staging", "production", "prod"}
    or _CROWN_IS_DEPLOY_CHECK
)

if _CROWN_DEPLOY_SECURITY:
    DEBUG = False

    _allowed_hosts_raw = _crown_os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,.azurewebsites.net"
    )
    ALLOWED_HOSTS = [
        host.strip()
        for host in _allowed_hosts_raw.split(",")
        if host.strip()
    ]

    _secret_key_from_env = _crown_os.getenv("DJANGO_SECRET_KEY") or _crown_os.getenv("SECRET_KEY", "")
    if _secret_key_from_env:
        SECRET_KEY = _secret_key_from_env

    # In deploy-hardening mode, never allow Django's insecure fallback key.
    if (
        not SECRET_KEY
        or SECRET_KEY.startswith("django-insecure-")
        or len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 5
    ):
        SECRET_KEY = secrets.token_urlsafe(64)

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(_crown_os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

    # Required when HTTPS is terminated by Azure/App Service/reverse proxy.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# === CROWN DEPLOY SECURITY SETTINGS END ===
# === CROWN PRODUCTION HARDENING OVERRIDES START ===
# Purpose:
#   Final production safety overrides for Django deploy checks.
#   Keep this block last so it overrides earlier defaults.
#
# Required production environment variables:
#   DJANGO_SECRET_KEY or SECRET_KEY
#   DJANGO_DEBUG=false or DEBUG=false
#   DJANGO_ALLOWED_HOSTS=crown-api-prod.azurewebsites.net,<custom-domain>
#   DJANGO_CSRF_TRUSTED_ORIGINS=https://crown-dash.azurestaticapps.net,https://<custom-domain>
import os as _crown_os
import sys as _crown_sys

_CROWN_ENV = (
    _crown_os.getenv("DJANGO_ENV")
    or _crown_os.getenv("ENVIRONMENT")
    or _crown_os.getenv("AZURE_ENVIRONMENT")
    or ""
).lower()

_CROWN_IS_PROD = _CROWN_ENV in {"prod", "production"} or bool(_crown_os.getenv("WEBSITE_HOSTNAME"))
_CROWN_IS_DEPLOY_CHECK = "--deploy" in _crown_sys.argv
_CROWN_HARDENED_CONTEXT = _CROWN_IS_PROD or _CROWN_IS_DEPLOY_CHECK


def _crown_bool_env(name: str, default: bool = False) -> bool:
    value = _crown_os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _crown_csv_env(name: str) -> list[str]:
    value = _crown_os.getenv(name, "")
    return [x.strip() for x in value.split(",") if x.strip()]


# SECRET_KEY must never be django-insecure in production.
_SECRET_FROM_ENV = (
    _crown_os.getenv("DJANGO_SECRET_KEY")
    or _crown_os.getenv("SECRET_KEY")
    or globals().get("SECRET_KEY")
)
if _CROWN_IS_PROD:
    if not _SECRET_FROM_ENV or str(_SECRET_FROM_ENV).startswith("django-insecure-"):
        raise RuntimeError(
            "Production SECRET_KEY is missing or insecure. "
            "Set DJANGO_SECRET_KEY or SECRET_KEY in Azure App Settings."
        )
SECRET_KEY = _SECRET_FROM_ENV

# DEBUG must be false in production.
DEBUG = _crown_bool_env("DJANGO_DEBUG", _crown_bool_env("DEBUG", False))
if _CROWN_IS_PROD and DEBUG:
    raise RuntimeError("DEBUG=True is forbidden in production.")

# Host and CSRF configuration.
_ALLOWED_HOSTS_ENV = _crown_csv_env("DJANGO_ALLOWED_HOSTS") or _crown_csv_env("ALLOWED_HOSTS")
if _ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = _ALLOWED_HOSTS_ENV
elif _CROWN_IS_PROD:
    ALLOWED_HOSTS = [
        _crown_os.getenv("WEBSITE_HOSTNAME", "crown-api-prod.azurewebsites.net"),
        "crown-api-prod.azurewebsites.net",
    ]

_CSRF_ENV = _crown_csv_env("DJANGO_CSRF_TRUSTED_ORIGINS") or _crown_csv_env("CSRF_TRUSTED_ORIGINS")
if _CSRF_ENV:
    CSRF_TRUSTED_ORIGINS = _CSRF_ENV

# Django deploy-check hardening.
SECURE_SSL_REDIRECT = _crown_bool_env("DJANGO_SECURE_SSL_REDIRECT", _CROWN_HARDENED_CONTEXT)
SESSION_COOKIE_SECURE = _crown_bool_env("DJANGO_SESSION_COOKIE_SECURE", _CROWN_HARDENED_CONTEXT)
CSRF_COOKIE_SECURE = _crown_bool_env("DJANGO_CSRF_COOKIE_SECURE", _CROWN_HARDENED_CONTEXT)
SECURE_HSTS_SECONDS = int(_crown_os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if _CROWN_HARDENED_CONTEXT else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _crown_bool_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", _CROWN_HARDENED_CONTEXT)
SECURE_HSTS_PRELOAD = _crown_bool_env("DJANGO_SECURE_HSTS_PRELOAD", _CROWN_HARDENED_CONTEXT)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Proxy SSL header for Azure/App Service reverse proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# === CROWN PRODUCTION HARDENING OVERRIDES END ===



# Crown structured request logging
LOGGING = globals().get("LOGGING", {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {},
})

LOGGING.setdefault("handlers", {}).setdefault("console", {"class": "logging.StreamHandler"})
LOGGING.setdefault("loggers", {})["crown.request"] = {
    "handlers": ["console"],
    "level": "INFO",
    "propagate": False,
}

# Sandbox demo access configuration
CROWN_SANDBOX_ALLOW_OPEN_SESSION = _env_bool("CROWN_SANDBOX_ALLOW_OPEN_SESSION", default=DEBUG)
CROWN_SANDBOX_ACCESS_TTL_SECONDS = int(os.getenv("CROWN_SANDBOX_ACCESS_TTL_SECONDS", "7200"))
CROWN_SANDBOX_REFRESH_TTL_SECONDS = int(os.getenv("CROWN_SANDBOX_REFRESH_TTL_SECONDS", "43200"))
CROWN_SANDBOX_FALLBACK_PASSWORD = os.getenv("CROWN_SANDBOX_FALLBACK_PASSWORD", "")
