from copy import deepcopy

SHELL_BACKEND_CONTRACT = {
    "version": 3,
    "wizards": [
        {
            "moduleKey": "admissions-onboarding",
            "path": "/onboarding",
            "apiPrefix": "/api/v1/onboarding/imports/",
            "requiresAuth": True,
            "requiresSchoolHeader": True,
            "schoolHeaderName": "X-School-Id",
            "probeSchoolId": "1",
            "acceptableUnauthenticatedStatusCodes": [401, 403],
            "acceptableMissingSchoolHeaderStatusCodes": [400, 403],
            "acceptableAuthenticatedStatusCodes": [200, 403, 405],
            "requiresSeededSuccess": True,
            "seededSuccessProbeMethod": "POST",
            "acceptableSeededSuccessStatusCodes": [201],
            "expectedJsonTopLevelKinds": ["array", "object"],
        },
        {
            "moduleKey": "reenrollment",
            "path": "/reenrollment",
            "apiPrefix": "/api/v1/reenrollment/sessions/",
            "requiresAuth": True,
            "requiresSchoolHeader": True,
            "schoolHeaderName": "X-School-Id",
            "probeSchoolId": "1",
            "acceptableUnauthenticatedStatusCodes": [401, 403],
            "acceptableMissingSchoolHeaderStatusCodes": [400, 403],
            "acceptableAuthenticatedStatusCodes": [200, 403, 405],
            "requiresSeededSuccess": True,
            "seededSuccessProbeMethod": "POST",
            "acceptableSeededSuccessStatusCodes": [201],
            "expectedJsonTopLevelKinds": ["array", "object"],
        },
        {
            "moduleKey": "financial-aid-setup",
            "path": "/aid-setup",
            "apiPrefix": "/api/v1/aid-wizard/sessions/",
            "requiresAuth": True,
            "requiresSchoolHeader": True,
            "schoolHeaderName": "X-School-Id",
            "probeSchoolId": "1",
            "acceptableUnauthenticatedStatusCodes": [401, 403],
            "acceptableMissingSchoolHeaderStatusCodes": [400, 403],
            "acceptableAuthenticatedStatusCodes": [200, 403, 405],
            "requiresSeededSuccess": True,
            "seededSuccessProbeMethod": "POST",
            "acceptableSeededSuccessStatusCodes": [201],
            "expectedJsonTopLevelKinds": ["array", "object"],
        },
        {
            "moduleKey": "enrollment-conversion",
            "path": "/enrollment-conversion",
            "apiPrefix": "/api/v1/enrollment-conversion-wizard/sessions/",
            "requiresAuth": True,
            "requiresSchoolHeader": True,
            "schoolHeaderName": "X-School-Id",
            "probeSchoolId": "1",
            "acceptableUnauthenticatedStatusCodes": [401, 403],
            "acceptableMissingSchoolHeaderStatusCodes": [400, 403],
            "acceptableAuthenticatedStatusCodes": [200, 403, 405],
            "requiresSeededSuccess": True,
            "seededSuccessProbeMethod": "POST",
            "acceptableSeededSuccessStatusCodes": [201],
            "expectedJsonTopLevelKinds": ["array", "object"],
        },
        {
            "moduleKey": "enrollment-period-setup",
            "path": "/enrollment-period-setup",
            "apiPrefix": "/api/v1/enrollment-period-wizard/sessions/",
            "requiresAuth": True,
            "requiresSchoolHeader": True,
            "schoolHeaderName": "X-School-Id",
            "probeSchoolId": "1",
            "acceptableUnauthenticatedStatusCodes": [401, 403],
            "acceptableMissingSchoolHeaderStatusCodes": [400, 403],
            "acceptableAuthenticatedStatusCodes": [200, 403, 405],
            "requiresSeededSuccess": True,
            "seededSuccessProbeMethod": "POST",
            "acceptableSeededSuccessStatusCodes": [201],
            "expectedJsonTopLevelKinds": ["array", "object"],
        },
    ],
    "dashboardModules": [],
}


def get_shell_backend_contract():
    return deepcopy(SHELL_BACKEND_CONTRACT)
