# Generated by Django 5.2.8 on 2026-02-27 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structure_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_structures', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_structures', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='MarkingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ordering', models.IntegerField()),
                ('is_grade_term', models.BooleanField(default=True)),
                ('term_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_periods', to='term_structure_wizard.termstructure')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='TermStructureWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structure_config', models.JSONField(blank=True, null=True)),
                ('periods_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('periods_set', 'Periods Set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_structure_wizard_sessions', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_structure_wizard_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_structure_wizard_sessions', to='core.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='termstructure',
            index=models.Index(fields=['school', 'is_active'], name='term_struct_school__4571fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='termstructure',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year'), name='uniq_term_structure_school_year'),
        ),
        migrations.AddConstraint(
            model_name='markingperiod',
            constraint=models.UniqueConstraint(fields=('term_structure', 'code'), name='uniq_marking_period_code'),
        ),
        migrations.AddConstraint(
            model_name='markingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='chk_marking_period_start_lte_end'),
        ),
        migrations.AddIndex(
            model_name='termstructurewizardsession',
            index=models.Index(fields=['school', 'status'], name='term_struct_school__0088f8_idx'),
        ),
    ]
