# Generated by Django 5.2.13 on 2026-05-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sandboxevent',
            new_name='sandbox_dem_event_e5e380_idx',
            old_name='sandbox_dem_event_d14ac3_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxevent',
            new_name='sandbox_dem_track_5d199d_idx',
            old_name='sandbox_dem_track_80f9ed_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxfeedback',
            new_name='sandbox_dem_rating_ab1bd5_idx',
            old_name='sandbox_dem_rating_8ff55a_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxfeedback',
            new_name='sandbox_dem_track_0dba9d_idx',
            old_name='sandbox_dem_track_cf54a8_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxinvite',
            new_name='sandbox_dem_track_817822_idx',
            old_name='sandbox_dem_track_f3f4d5_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxinvite',
            new_name='sandbox_dem_revoked_c4f67a_idx',
            old_name='sandbox_dem_revoked_4fd23e_idx',
        ),
    ]
