# Generated by Django 5.2.14 on 2026-05-31 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_demo', '0003_merge_20260530_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SandboxAccessRequest',
        ),
    ]
