# Generated by Django 5.2.13 on 2026-05-28 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_retentionpurgeaudit'),
        ('households', '0008_households_guardians_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerCampConfigWizardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_config_wizard_state', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=24)),
                ('registration_source', models.CharField(default='EXISTING', max_length=24)),
                ('form_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('MISSING', 'Missing'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='MISSING', max_length=24)),
                ('payment_status', models.CharField(choices=[('NOT_BILLED', 'Not Billed'), ('DEPOSIT_DUE', 'Deposit Due'), ('DEPOSIT_PAID', 'Deposit Paid'), ('BALANCE_DUE', 'Balance Due'), ('PAID_IN_FULL', 'Paid In Full'), ('PAST_DUE', 'Past Due'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='DEPOSIT_DUE', max_length=24)),
                ('health_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('NEEDS_REVIEW', 'Needs Review'), ('APPROVED', 'Approved')], default='NEEDS_REVIEW', max_length=24)),
                ('pickup_status', models.CharField(default='MISSING', max_length=24)),
                ('readiness_status', models.CharField(choices=[('READY', 'Ready'), ('MISSING_PAYMENT', 'Missing Payment'), ('MISSING_FORMS', 'Missing Forms'), ('HEALTH_REVIEW_REQUIRED', 'Health Review Required'), ('PICKUP_CONTACT_MISSING', 'Pickup Contact Missing'), ('WAITLISTED', 'Waitlisted'), ('CAPACITY_BLOCKED', 'Capacity Blocked'), ('STAFF_REVIEW_REQUIRED', 'Staff Review Required'), ('BLOCKED', 'Blocked')], default='BLOCKED', max_length=32)),
                ('readiness_blockers', models.JSONField(blank=True, default=list)),
                ('waitlist_position', models.IntegerField(blank=True, null=True)),
                ('payment_required_before_attendance', models.BooleanField(default=True)),
                ('balance_due_cents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_enrollments', to='households.household')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_enrollments', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_enrollments', to='households.student')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampBillingLedgerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=64)),
                ('charge_type', models.CharField(default='SESSION', max_length=64)),
                ('amount_cents', models.IntegerField(default=0)),
                ('status', models.CharField(default='OPEN', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_billing_links', to='core.school')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_links', to='summer_camp.summercampenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampHealthReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('emergency_contacts', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('NEEDS_REVIEW', 'Needs Review'), ('APPROVED', 'Approved')], default='NEEDS_REVIEW', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_review', to='summer_camp.summercampenrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_health_reviews', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampPickupContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_contacts', to='summer_camp.summercampenrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_pickup_contacts', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('program_type', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('grade_band', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('public_registration_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_programs', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SummerCampProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(default='Summer Camp', max_length=160)),
                ('default_start_time', models.TimeField(default='08:00')),
                ('default_end_time', models.TimeField(default='15:00')),
                ('default_capacity', models.IntegerField(default=30)),
                ('default_staff_ratio', models.IntegerField(default=10)),
                ('required_form_policy', models.JSONField(blank=True, default=dict)),
                ('billing_policy', models.CharField(choices=[('PER_SESSION', 'Per Session'), ('PER_WEEK', 'Per Week'), ('FULL_CAMP', 'Full Camp')], default='PER_SESSION', max_length=24)),
                ('pickup_policy', models.JSONField(blank=True, default=dict)),
                ('health_review_policy', models.JSONField(blank=True, default=dict)),
                ('public_registration_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_program_config', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(default=0)),
                ('waitlist_capacity', models.IntegerField(default=0)),
                ('price_cents', models.IntegerField(default=0)),
                ('deposit_cents', models.IntegerField(default=0)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('required_forms', models.JSONField(blank=True, default=list)),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='summer_camp.summercampprogram')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_sessions', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('parent_notified', models.BooleanField(default=False)),
                ('health_followup_required', models.BooleanField(default=False)),
                ('discipline_record_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_incidents', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_incidents', to='households.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='summer_camp.summercampsession')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age_band', models.CharField(blank=True, max_length=64)),
                ('capacity', models.IntegerField(default=0)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_counselor_groups', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_groups', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='summer_camp.summercampsession')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampFormRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('conditional_rule', models.CharField(blank=True, max_length=240)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_form_requirements', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_requirements', to='summer_camp.summercampsession')),
            ],
        ),
        migrations.AddField(
            model_name='summercampenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='summer_camp.summercampsession'),
        ),
        migrations.CreateModel(
            name='SummerCampAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_attendance', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_attendance', to='households.student')),
                ('pickup_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summer_camp.summercamppickupcontact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='summer_camp.summercampsession')),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('credential_status', models.CharField(default='PENDING', max_length=64)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_staff_assignments', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='summer_camp.summercampsession')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummerCampGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='summer_camp.summercampenrollment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='summer_camp.summercampgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_camp_group_assignments', to='core.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summer_camp_group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'enrollment')},
            },
        ),
        migrations.AddIndex(
            model_name='summercampsession',
            index=models.Index(fields=['school', 'start_date', 'status'], name='summer_camp_school__9c5de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='summercampsession',
            unique_together={('program', 'name', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='summercampgroup',
            unique_together={('session', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='summercampformrequirement',
            unique_together={('session', 'form_type')},
        ),
        migrations.AddIndex(
            model_name='summercampenrollment',
            index=models.Index(fields=['school', 'session', 'status'], name='summer_camp_school__cbb634_idx'),
        ),
        migrations.AddIndex(
            model_name='summercampenrollment',
            index=models.Index(fields=['school', 'student'], name='summer_camp_school__034515_idx'),
        ),
        migrations.AddIndex(
            model_name='summercampattendance',
            index=models.Index(fields=['school', 'date'], name='summer_camp_school__e0ea22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='summercampattendance',
            unique_together={('session', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='summercampstaffassignment',
            unique_together={('session', 'staff_user', 'role')},
        ),
    ]
