# Generated by Django 5.2.8 on 2026-02-27 08:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReenrollmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year_label', models.CharField(blank=True, default='', help_text='E.g. "2026-2027" — labels the BillingRun term.', max_length=24)),
                ('enrollment_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-student enrollment fee for the new year.', max_digits=10)),
                ('excluded_ids', models.JSONField(blank=True, default=list, help_text='List of households.Student UUIDs to exclude from this run.')),
                ('candidates_snapshot', models.JSONField(blank=True, help_text='Snapshot of households.Student records eligible for re-enrollment.', null=True)),
                ('commit_result', models.JSONField(blank=True, help_text='Written by commit_session; read by verify_session.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('committed', 'Committed'), ('verified', 'Verified')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reenrollment_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenrollment_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
