# Generated by Django 5.2.17 on 2026-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reenrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reenrollmentsession',
            name='communication_timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
        migrations.AddField(
            model_name='reenrollmentsession',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
