# Generated by Django 5.2.8 on 2026-02-18 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seedrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Graduation Policy', max_length=120)),
                ('required_total_credits', models.DecimalField(decimal_places=2, default=24.0, max_digits=6)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_rules', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'is_active'], name='graduation__school__7d127b_idx')],
            },
        ),
    ]
