# Generated by Django 5.2.8 on 2026-02-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('period_label', models.CharField(default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
                'unique_together': {('school_id', 'as_of_date', 'period_label')},
            },
        ),
        migrations.CreateModel(
            name='BoardPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshots', models.ManyToManyField(blank=True, to='board_oversight.boardreportsnapshot')),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
    ]
