# Generated by Django 6.0 on 2026-01-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aiddocument_aid_application_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLedgerEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.ledgerentry',),
        ),
        migrations.CreateModel(
            name='FinanceStudentTuition',
            fields=[
            ],
            options={
                'verbose_name': 'Student Tuition',
                'verbose_name_plural': 'Student Tuitions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.studenttuition',),
        ),
        migrations.CreateModel(
            name='FinanceTuitionPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Tuition Plan',
                'verbose_name_plural': 'Tuition Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tuitionplan',),
        ),
    ]
