# Generated by Django 5.2.8 on 2026-02-25 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        ('finance', '0002_financeledgerentry_financestudenttuition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('refunded', 'Refunded')], default='open', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(db_index=True)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_invoices', to=settings.AUTH_USER_MODEL)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_invoices', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_invoices', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('tuition', 'Tuition'), ('fee', 'Fee'), ('incidental', 'Incidental'), ('donation_pledge', 'Donation Pledge')], default='tuition', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('refunded', 'Refunded')], default='open', max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField(db_index=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('academic_year_label', models.CharField(blank=True, default='', max_length=9)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_obligations', to=settings.AUTH_USER_MODEL)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_obligations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_obligations', to='core.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_finance_obligations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.financeinvoice')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='finance.financeobligation')),
            ],
        ),
        migrations.CreateModel(
            name='FinancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('void', 'Void'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('processor', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('compuwerx', 'Compuwerx')], default='manual', max_length=16)),
                ('processor_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_payments', to=settings.AUTH_USER_MODEL)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_allocations', to='core.school')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.financeobligation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.financepayment')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('void', 'Void'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('processor', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('compuwerx', 'Compuwerx')], default='manual', max_length=16)),
                ('processor_refund_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.financepayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_refunds', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('refunded', 'Refunded')], default='open', max_length=16)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('fund_code', models.CharField(blank=True, default='', max_length=64)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_rule', models.CharField(blank=True, default='', max_length=128)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_donations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_donations', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'donor_user', 'status'], name='finance_fin_school__aa6b4d_idx'), models.Index(fields=['school', 'fund_code'], name='finance_fin_school__947979_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financeinvoice',
            index=models.Index(fields=['school', 'payer_user', 'status'], name='finance_fin_school__378345_idx'),
        ),
        migrations.AddIndex(
            model_name='financeinvoice',
            index=models.Index(fields=['school', 'due_date'], name='finance_fin_school__383fea_idx'),
        ),
        migrations.AddIndex(
            model_name='financeobligation',
            index=models.Index(fields=['school', 'payer_user', 'status'], name='finance_fin_school__108209_idx'),
        ),
        migrations.AddIndex(
            model_name='financeobligation',
            index=models.Index(fields=['school', 'due_date'], name='finance_fin_school__85c982_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeobligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='finance_obligation_amount_cents_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='financeinvoiceline',
            unique_together={('invoice', 'obligation')},
        ),
        migrations.AddIndex(
            model_name='financepayment',
            index=models.Index(fields=['school', 'payer_user', 'status'], name='finance_fin_school__032d35_idx'),
        ),
        migrations.AddIndex(
            model_name='financepayment',
            index=models.Index(fields=['school', 'processor', 'processor_payment_id'], name='finance_fin_school__67a880_idx'),
        ),
        migrations.AddConstraint(
            model_name='financepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='finance_payment_amount_cents_nonneg'),
        ),
        migrations.AddIndex(
            model_name='financeallocation',
            index=models.Index(fields=['school', 'obligation'], name='finance_fin_school__79666e_idx'),
        ),
        migrations.AddIndex(
            model_name='financeallocation',
            index=models.Index(fields=['school', 'payment'], name='finance_fin_school__387315_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='finance_allocation_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='financerefund',
            index=models.Index(fields=['school', 'processor', 'processor_refund_id'], name='finance_fin_school__7cdf5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='financerefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='finance_refund_amount_positive'),
        ),
    ]
