# Generated by Django 5.2.8 on 2026-01-25 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0008_households_guardians_students"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('DECIDED', 'Decided')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='households.household')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('grade_applying_for', models.CharField(blank=True, default='', max_length=16)),
                ('dob', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_links', to='households.student')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='applications.application')),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
            ],
            options={
                'db_table': 'application_event',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['school_id', 'status'], name='application_school__88e211_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['school_id', 'created_at'], name='application_school__1b5874_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['school_id', 'application'], name='applicant_school__8477ad_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['school_id', 'last_name', 'first_name'], name='applicant_school__6ea9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['school_id', 'application', 'created_at'], name='application_school__88d31b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['school_id', 'event_type'], name='application_school__12d360_idx'),
        ),
    ]
