# Generated by Django 6.0 on 2026-02-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applications_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicant',
            name='source',
            field=models.CharField(db_index=True, default='other', max_length=32),
        ),
    ]
