# Generated by Django 5.2.13 on 2026-05-27 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_checklist_access_keys(apps, schema_editor):
    application_model = apps.get_model('applications', 'Application')
    for row in application_model.objects.filter(checklist_access_key__isnull=True).only('id'):
        row.checklist_access_key = uuid.uuid4()
        row.save(update_fields=['checklist_access_key'])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicant_flags_applicant_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='checklist_access_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationChecklistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('item_key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('office', models.CharField(blank=True, default='', max_length=120)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='missing', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='applications.application')),
            ],
            options={
                'db_table': 'application_checklist_item',
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklistDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('file', models.FileField(upload_to='admissions/checklist/%Y/%m/%d')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.applicationchecklistitem')),
            ],
            options={
                'db_table': 'application_checklist_document',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('signed', 'Signed'), ('countersigned', 'Countersigned'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=32)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('contract_totals', models.JSONField(blank=True, default=dict)),
                ('net_amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_plan', models.CharField(blank=True, default='', max_length=80)),
                ('payment_schedule', models.CharField(blank=True, default='', max_length=255)),
                ('responsible_payer', models.CharField(blank=True, default='', max_length=255)),
                ('refund_terms', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='applications.enrollmentcontract')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_contracts', to='applications.application')),
            ],
            options={
                'db_table': 'enrollment_contract',
            },
        ),
        migrations.AddIndex(
            model_name='applicationchecklistitem',
            index=models.Index(fields=['school_id', 'application', 'status'], name='application_school__77121a_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationchecklistitem',
            constraint=models.UniqueConstraint(fields=('application', 'item_key'), name='uniq_app_checklist_item_key'),
        ),
        migrations.AddIndex(
            model_name='applicationchecklistdocument',
            index=models.Index(fields=['school_id', 'checklist_item', 'created_at'], name='application_school__720fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentcontract',
            index=models.Index(fields=['school_id', 'application', 'status'], name='enrollment__school__6ffb43_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentcontract',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='uniq_enrollment_contract_version'),
        ),
        migrations.RunPython(_backfill_checklist_access_keys, _noop_reverse),
        migrations.AlterField(
            model_name='application',
            name='checklist_access_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
