# Generated by Django 5.2 on 2026-10-05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0011_application_checklist_access_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAssentEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(choices=[("SIGN", "Sign"), ("COUNTERSIGN", "Countersign")], max_length=16)),
                ("signer_name", models.CharField(max_length=255)),
                ("signer_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contract_sha256", models.CharField(db_index=True, max_length=64)),
                ("consent_version", models.CharField(default="crown-contract-assent-v1", max_length=64)),
                ("consent_text", models.TextField()),
                ("accepted_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrollment_contract_assents", to=settings.AUTH_USER_MODEL)),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assent_evidence", to="applications.enrollmentcontract")),
            ],
            options={
                "db_table": "contract_assent_evidence",
                "ordering": ["accepted_at", "id"],
                "indexes": [
                    models.Index(fields=["school_id", "contract", "action"], name="contract_as_school__8b7bb6_idx"),
                    models.Index(fields=["school_id", "actor_user", "accepted_at"], name="contract_as_school__7e37d4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("contract", "action", "actor_user", "contract_sha256"), name="uniq_contract_actor_assent_digest"),
                ],
            },
        ),
    ]
