# Generated by Django 5.2.8 on 2026-02-27 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('capacity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='uniq_room_code_per_school'), models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='chk_room_capacity_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='RoomSetupWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=32)),
                ('rooms', models.JSONField(blank=True, default=list)),
                ('commit_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='room_setup__school__bceed6_idx')],
            },
        ),
    ]
