# Generated by Django 5.2.8 on 2026-02-27 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommsWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(default='', max_length=128)),
                ('channels', models.JSONField(default=list)),
                ('subject', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('recipients', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('message_drafted', 'Message Drafted'), ('recipients_staged', 'Recipients Staged'), ('committed', 'Committed'), ('verified', 'Verified')], db_index=True, default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comms_wizard_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_wizard_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='comms_wizar_school__9b416f_idx')],
            },
        ),
    ]
