# Generated by Django 5.2.13 on 2026-04-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms_wizard', '0002_message_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='comms_wizar_school__2f2841_idx',
            old_name='comms_wizar_school__idx1',
        ),
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='comms_wizar_categor_73052b_idx',
            old_name='comms_wizar_categor_idx2',
        ),
    ]
