# Generated by Django 5.2.13 on 2026-04-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms_wizard', '0003_rename_comms_wizar_school__idx1_comms_wizar_school__2f2841_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
