# Generated by Django 6.0 on 2026-02-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRow',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('school_id', models.CharField(db_index=True, max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionRow',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('school_id', models.CharField(db_index=True, max_length=32)),
                ('course_id', models.CharField(max_length=32)),
                ('term_ref_id', models.CharField(blank=True, max_length=32, null=True)),
                ('term', models.CharField(max_length=24)),
                ('teacher_name', models.CharField(max_length=120)),
                ('grade_band', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
    ]
