# Generated by Django 5.2.8 on 2026-02-27 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('credits', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='uniq_course_code_per_school')],
            },
        ),
        migrations.CreateModel(
            name='CourseCatalogWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=32)),
                ('catalog', models.JSONField(blank=True, default=list)),
                ('commit_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='course_cata_school__b7ba26_idx')],
            },
        ),
    ]
