# Generated by Django 5.2.8 on 2026-02-27 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('students_guardians', 'Students + Guardians'), ('staff', 'Staff / Teachers'), ('contacts', 'Emergency Contacts')], default='students_guardians', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('validated', 'Validated'), ('previewed', 'Previewed'), ('committed', 'Committed'), ('verified', 'Verified')], default='pending', max_length=30)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('raw_csv', models.TextField(blank=True)),
                ('rows_total', models.IntegerField(default=0)),
                ('students_detected', models.IntegerField(default=0)),
                ('guardians_detected', models.IntegerField(default=0)),
                ('households_detected', models.IntegerField(default=0)),
                ('validate_result', models.JSONField(blank=True, null=True)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
