# Generated by Django 5.2.8 on 2026-03-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_stage3_onboarding_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportFieldMapping',
        ),
    ]
