# Generated by Django 5.2.12 on 2026-04-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_delete_importfieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolomonAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('role_code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SolomonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SolomonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ['module', 'sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='helparticle',
            name='article_type',
            field=models.CharField(choices=[('guide', 'Guide'), ('contextual', 'Contextual'), ('faq', 'FAQ'), ('migration', 'Migration')], default='guide', max_length=20),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='route_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('staff', 'Staff'), ('admin', 'Admin')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='articles', to='onboarding.solomonaudience'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='onboarding.solomoncategory'),
        ),
        migrations.CreateModel(
            name='SolomonPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('staff', 'Staff'), ('admin', 'Admin')], default='public', max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('route_path', models.CharField(blank=True, default='', max_length=200)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audiences', models.ManyToManyField(blank=True, related_name='playbooks', to='onboarding.solomonaudience')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to='onboarding.solomoncategory')),
            ],
            options={
                'ordering': ['module', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SolomonRouteContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('route_path', models.CharField(db_index=True, max_length=200)),
                ('context_key', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_contexts', to='onboarding.solomonaudience')),
                ('help_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_contexts', to='onboarding.helparticle')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_contexts', to='onboarding.solomonplaybook')),
            ],
            options={
                'ordering': ['module', 'route_path', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', to='onboarding.solomontopic'),
        ),
    ]
