# Generated by Django 5.2.8 on 2026-02-27 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('term', models.CharField(db_index=True, max_length=24)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='core.school')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('tuition', 'Tuition'), ('fee', 'Fee')], default='fee', max_length=16)),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('semester', 'Semester'), ('monthly', 'Monthly'), ('one_time', 'One-time')], default='annual', max_length=16)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fee_schedule_wizard.feeschedule')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FeeScheduleWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=24)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('lines_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('lines_set', 'Lines Set'), ('committed', 'Committed'), ('verified', 'Verified')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_schedule_wizard_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedule_wizard_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['school', 'term'], name='fee_schedul_school__ecc169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeschedule',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feeline',
            unique_together={('fee_schedule', 'code')},
        ),
        migrations.AddIndex(
            model_name='feeschedulewizardsession',
            index=models.Index(fields=['school', 'status'], name='fee_schedul_school__cb69d3_idx'),
        ),
    ]
