# Generated by Django 5.2.12 on 2026-03-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('provider_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('signature', models.CharField(blank=True, default='', max_length=256)),
                ('raw_body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='received', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uq_gateway_event_provider_event_id')],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('client_reference_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('settling', 'Settling'), ('settled', 'Settled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], db_index=True, default='created', max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
