# Generated by Django 5.2.12 on 2026-03-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('dispute_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], db_index=True, default='open', max_length=32)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('payout_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('expected_payment_count', models.IntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payments.providerpayoutbatch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
