# Generated by Django 5.2.12 on 2026-03-13 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_providerdispute_providerpayoutbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('household_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('provider_customer_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_method_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('method_type', models.CharField(blank=True, default='card', max_length=32)),
                ('brand', models.CharField(blank=True, default='', max_length=32)),
                ('last4', models.CharField(blank=True, default='', max_length=8)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSupportException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('compuwerx', 'Compuwerx')], max_length=32)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('retrying', 'Retrying'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=16)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('gateway_event_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payment_intent_record_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dispute_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payout_batch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payment_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderDisputeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('provider_response_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_dispute_actions', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='payments.providerdispute')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StatementExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('household_id', models.UUIDField(db_index=True)),
                ('format', models.CharField(default='csv', max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('generated', 'Generated'), ('failed', 'Failed')], db_index=True, default='requested', max_length=32)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
