# Generated by Django 5.2.12 on 2026-03-13 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_savedpaymentmethod_paymentsupportexception_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=32)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('posted_date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_matched', models.BooleanField(db_index=True, default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payments.bankstatementimport')),
            ],
            options={
                'ordering': ['-posted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayoutBankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('auto_matched', 'Auto Matched'), ('manual_matched', 'Manual Matched'), ('rejected', 'Rejected')], db_index=True, default='auto_matched', max_length=32)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_delta_days', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_matches', to='payments.bankstatemententry')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_bank_matches', to=settings.AUTH_USER_MODEL)),
                ('payout_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_matches', to='payments.providerpayoutbatch')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('payout_batch', 'bank_entry'), name='uq_payout_bank_match_pair')],
            },
        ),
    ]
