# Generated by Django 5.2.17 on 2026-09-30 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_extended_care_edit_permission'),
        ('payments', '0007_reconciliation_evidence_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('price_cents', models.PositiveIntegerField()),
                ('tax_rate_bp', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('resulting_stock', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='payments.storeproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('school', 'sku'), name='store_school_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('school', 'barcode'), name='store_school_barcode_unique'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_bp__lte', 10000)), name='store_tax_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='storestockmovement',
            constraint=models.UniqueConstraint(fields=('product', 'idempotency_key'), name='store_stock_movement_unique'),
        ),
        migrations.AddConstraint(
            model_name='storestockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='store_stock_delta_nonzero'),
        ),
    ]
