# Generated by Django 5.2.17 on 2026-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_extended_care_edit_permission'),
        ('payments', '0008_school_store_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='sales_area',
            field=models.CharField(choices=[('store', 'School Store'), ('snack', 'Snack Stand'), ('lunch', 'School Lunches')], default='store', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('sales_area__in', ['store', 'snack', 'lunch'])), name='store_sales_area_valid'),
        ),
    ]
