# Generated by Django 5.2.8 on 2026-02-27 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(default='', max_length=24)),
                ('billing_mode', models.CharField(choices=[('simple', 'Simple'), ('advanced', 'Advanced')], default='simple', max_length=16)),
                ('plans_config', models.JSONField(default=list)),
                ('fees_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('plans_saved', 'Plans Saved'), ('fees_saved', 'Fees Saved'), ('committed', 'Committed'), ('verified', 'Verified')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_wizard_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_wizard_sessions', to='core.school')),
            ],
            options={
                'db_table': 'billing_wizard_session',
                'indexes': [models.Index(fields=['school', 'status'], name='billing_wiz_school__5bd1b1_idx'), models.Index(fields=['school', 'term'], name='billing_wiz_school__29775a_idx')],
            },
        ),
    ]
