# Generated by Django 5.2.8 on 2026-02-27 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, default='', max_length=24)),
                ('school_year', models.CharField(blank=True, default='', max_length=16)),
                ('courses_config', models.JSONField(default=list)),
                ('sections_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('courses_saved', 'Courses Saved'), ('sections_staged', 'Sections Staged'), ('committed', 'Committed'), ('verified', 'Verified')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_wizard_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
