# Generated by Django 5.2.8 — advancement Stage 1 expansion

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advancement", "0001_initial"),
    ]

    operations = [
        # ------------------------------------------------------------------
        # Donor — add extended fields
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name="donor",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="donor",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="donor",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="donor",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="donor",
            name="donor_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("business", "Business"),
                    ("church", "Church"),
                    ("alumni", "Alumni"),
                ],
                default="individual",
                max_length=50,
            ),
        ),
        # ------------------------------------------------------------------
        # Campaign — add date range fields
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        # ------------------------------------------------------------------
        # SponsorshipPackage
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="SponsorshipPackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, default="")),
                ("placement_type", models.CharField(blank=True, default="", max_length=100)),
                ("duration", models.CharField(blank=True, default="", max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["price"]},
        ),
        # ------------------------------------------------------------------
        # Event
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("ticket_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("tickets_sold", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["date"]},
        ),
        # ------------------------------------------------------------------
        # Ticket
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("event", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="tickets",
                    to="advancement.event",
                )),
                ("purchaser_name", models.CharField(max_length=255)),
                ("purchaser_email", models.EmailField()),
                ("qr_code", models.CharField(max_length=255, unique=True)),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("purchased_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-purchased_at"]},
        ),
        # ------------------------------------------------------------------
        # StoreItem
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        # ------------------------------------------------------------------
        # AdvancementTransaction
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name="AdvancementTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("school_id", models.UUIDField(db_index=True)),
                ("category", models.CharField(
                    choices=[
                        ("donation", "Donation"),
                        ("event_ticket", "Event Ticket"),
                        ("sponsorship", "Sponsorship"),
                        ("store_purchase", "Store Purchase"),
                    ],
                    db_index=True,
                    max_length=30,
                )),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("reference_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("campaign", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="transactions",
                    to="advancement.campaign",
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="advancementtransaction",
            index=models.Index(fields=["school_id", "category"], name="adv_txn_school__fb5116_idx"),
        ),
        migrations.AddIndex(
            model_name="advancementtransaction",
            index=models.Index(fields=["school_id", "created_at"], name="adv_txn_school__606626_idx"),
        ),
    ]
