# Generated by Django 5.2.8 on 2026-03-01 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancement', '0002_stage1_advancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('donor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restricted', models.BooleanField(default=False)),
                ('restriction_label', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'status'], name='gift_school_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('donor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=40)),
                ('external_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'status'], name='pledge_school_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('sponsor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='advancement.sponsorshippackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'status'], name='spons_agr_school_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('qr_attempted', models.CharField(blank=True, default='', max_length=255)),
                ('scanned_by_id', models.UUIDField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], default='accepted', max_length=40)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='advancement.ticket')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['school_id', 'result'], name='ticketscan_school_result_idx')],
            },
        ),
    ]
