# Generated by Django 5.2.8 on 2026-03-01 01:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancement', '0003_stage2_advancement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('class_year', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('benefits', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['annual_price'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('section', models.CharField(max_length=50)),
                ('row', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('layout_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('capacity_tier', models.CharField(choices=[('unknown', 'Unknown'), ('tier1', 'Tier 1 ($10k+)'), ('tier2', 'Tier 2 ($5k–$9.9k)'), ('tier3', 'Tier 3 ($1k–$4.9k)'), ('tier4', 'Tier 4 (<$1k)')], default='unknown', max_length=20)),
                ('interest_tags', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_profiles', to='advancement.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('stage', models.CharField(choices=[('identified', 'Identified'), ('qualified', 'Qualified'), ('cultivating', 'Cultivating'), ('soliciting', 'Soliciting'), ('stewarding', 'Stewarding'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='identified', max_length=30)),
                ('action_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('tour', 'Tour'), ('event', 'Event Invite'), ('proposal', 'Proposal'), ('thank_you', 'Thank You'), ('other', 'Other')], default='other', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_created', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='advancement.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('relationship_type', models.CharField(choices=[('alumni', 'Alumni'), ('parent', 'Parent'), ('grandparent', 'Grandparent'), ('church_partner', 'Church Partner'), ('business_partner', 'Business Partner'), ('board', 'Board Member'), ('friend', 'Friend of School'), ('staff', 'Staff')], default='friend', max_length=50)),
                ('class_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='advancement.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('held_by_email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='advancement.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='advancement.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seating_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='advancement.seatingmap'),
        ),
        migrations.CreateModel(
            name='EventSeating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('hold_minutes', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_config', to='advancement.event')),
                ('seating_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_configs', to='advancement.seatingmap')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('deliverable_type', models.CharField(choices=[('banner', 'Banner'), ('livestream_overlay', 'Livestream Overlay'), ('program_ad', 'Program Ad'), ('website_block', 'Website Block'), ('newsletter', 'Newsletter'), ('social_post', 'Social Post'), ('other', 'Other')], default='other', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='advancement.sponsorshipagreement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(default='unknown', max_length=40)),
                ('count', models.IntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advancement.sponsorshipdeliverable')),
            ],
            options={
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to='advancement.seat')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignment', to='advancement.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='seatingmap',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_maps', to='advancement.venue'),
        ),
        migrations.CreateModel(
            name='AlumniCohortMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='advancement.alumnicohort')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_memberships', to='advancement.donor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school_id', 'cohort', 'donor')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='advancement.donor')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='advancement.membershiptier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'status'], name='membership_school_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['school_id', 'is_active'], name='prospect_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['school_id', 'stage'], name='move_school_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['school_id', 'prospect_id'], name='move_school_prospect_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['school_id', 'relationship_type'], name='rel_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['school_id', 'event'], name='seathold_school_event_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seathold',
            unique_together={('school_id', 'event', 'seat')},
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['school_id', 'seating_map'], name='seat_school_map_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('school_id', 'seating_map', 'section', 'row', 'number')},
        ),
        migrations.AddIndex(
            model_name='sponsorimpression',
            index=models.Index(fields=['school_id', 'deliverable'], name='impression_school_deliv_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketseat',
            index=models.Index(fields=['school_id'], name='ticketseat_school_idx'),
        ),
    ]
