# Generated by Django 5.2.8 on 2026-03-01 02:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancement', '0004_stage3_advancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='ticketseat',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticketseat',
            unique_together={('school_id', 'event_id', 'seat')},
        ),
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('ticket_delivery', 'Ticket Delivery'), ('receipt', 'Receipt'), ('general', 'General')], default='general', max_length=40)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('attachments_json', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emailoutbox_status_created_idx'), models.Index(fields=['school_id'], name='emailoutbox_school_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSectionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('section', models.CharField(max_length=100)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'event_id'], name='sectprice_school_event_idx')],
                'unique_together': {('school_id', 'event_id', 'section')},
            },
        ),
        migrations.CreateModel(
            name='PendingSeatOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('purchaser_name', models.CharField(max_length=255)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('seat_ids', models.JSONField(default=list)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('provider', models.CharField(default='fake', max_length=40)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'event_id'], name='pendingorder_school_event_idx'), models.Index(fields=['provider_session_id'], name='pendingorder_session_idx')],
            },
        ),
    ]
