# Generated by Django 5.2.8 on 2026-03-01 03:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancement', '0005_stage3_1_2_3_seat_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True, unique=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('receipt_number', models.CharField(max_length=80, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('provider_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school_id', 'event_id'], name='receipt_school_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('sponsor_name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sponsor_name'],
                'indexes': [models.Index(fields=['school_id'], name='sponsorasset_school_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSponsorPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('tier', models.CharField(default='standard', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='advancement.sponsorasset')),
            ],
            options={
                'ordering': ['sort_order', 'tier'],
                'indexes': [models.Index(fields=['school_id', 'event_id'], name='evtsponsor_school_event_idx')],
                'unique_together': {('school_id', 'event_id', 'sponsor')},
            },
        ),
    ]
