# Generated by Django 5.2.11 on 2026-02-26 00:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('V', 'Varsity'), ('JV', 'Junior Varsity'), ('MS', 'Middle School'), ('ES', 'Elementary'), ('CLUB', 'Club')], default='V', max_length=8)),
                ('display_name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('participation_fee_cents', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.school')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='athletics.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='athletics.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PRACTICE', 'Practice'), ('GAME', 'Game'), ('TRYOUT', 'Tryout'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('opponent', models.CharField(blank=True, default='', max_length=200)),
                ('is_home', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletic_events', to='core.school')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='athletics.facility')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='athletics.team')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_medically_cleared', models.BooleanField(default=False)),
                ('is_academically_eligible', models.BooleanField(default=False)),
                ('is_behaviorally_eligible', models.BooleanField(default=False)),
                ('is_attendance_eligible', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_eligibility', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='core.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='athletics.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head_coach', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coaches', to='core.school')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='athletics.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rosters', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='core.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='athletics.team')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('physical_expires_on', models.DateField(blank=True, null=True)),
                ('insurance_on_file', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_clearances', to='core.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_clearance', to='core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['school'], name='athletics_a_school__984517_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['school', 'start_date'], name='athletics_s_school__789587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['school', 'is_active'], name='athletics_s_school__2f76a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sport',
            unique_together={('school', 'name', 'gender')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['school', 'season'], name='athletics_t_school__92d964_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['school', 'sport'], name='athletics_t_school__25c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['school', 'starts_at'], name='athletics_e_school__a0efe7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['school', 'team', 'starts_at'], name='athletics_e_school__4cbeca_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteeligibility',
            index=models.Index(fields=['school', 'team'], name='athletics_a_school__5f3115_idx'),
        ),
        migrations.AddIndex(
            model_name='athleteeligibility',
            index=models.Index(fields=['school', 'student'], name='athletics_a_school__09977b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='athleteeligibility',
            unique_together={('team', 'student')},
        ),
        migrations.AddIndex(
            model_name='teamcoach',
            index=models.Index(fields=['school', 'team'], name='athletics_t_school__b70466_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamcoach',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='teamroster',
            index=models.Index(fields=['school', 'team'], name='athletics_t_school__e85c78_idx'),
        ),
        migrations.AddIndex(
            model_name='teamroster',
            index=models.Index(fields=['school', 'student'], name='athletics_t_school__ee8a55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamroster',
            unique_together={('team', 'student')},
        ),
    ]
