# Generated by Django 5.2.8 on 2026-02-17 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seedrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('tardy', 'Tardy'), ('dress_code', 'Dress Code'), ('disruption', 'Disruption'), ('disrespect', 'Disrespect'), ('bullying', 'Bullying'), ('academic_dishonesty', 'Academic Dishonesty'), ('other', 'Other')], default='other', max_length=32)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='minor', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='open', max_length=16)),
                ('summary', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True, default='')),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_reported', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='core.student')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('assigned', 'Assigned'), ('parent_notified', 'Parent Notified'), ('status_changed', 'Status Changed'), ('closed', 'Closed')], default='note', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discipline.disciplineincident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disciplineincident',
            index=models.Index(fields=['school', 'status', 'severity'], name='discipline__school__834800_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineincident',
            index=models.Index(fields=['school', 'occurred_at'], name='discipline__school__9aa3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineincident',
            index=models.Index(fields=['school', 'student'], name='discipline__school__30b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplineaction',
            index=models.Index(fields=['incident', 'created_at'], name='discipline__inciden_92a51d_idx'),
        ),
    ]
