# Generated by Django 5.2.13 on 2026-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineaction',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('assigned', 'Assigned'), ('escalated', 'Escalated'), ('parent_notified', 'Parent Notified'), ('status_changed', 'Status Changed'), ('closed', 'Closed')], default='note', max_length=32),
        ),
    ]
