# Generated by Django 5.2.8 on 2026-02-16 21:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seedrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=64)),
                ('grade_level', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('worldview_theme', models.CharField(blank=True, default='', max_length=255)),
                ('anchor_scripture_ref', models.CharField(blank=True, default='', max_length=128)),
                ('anchor_scripture_text', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='core.school')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('essential_question', models.CharField(blank=True, default='', max_length=255)),
                ('big_idea', models.TextField(blank=True, default='')),
                ('worldview_focus', models.CharField(blank=True, default='', max_length=255)),
                ('scripture_ref', models.CharField(blank=True, default='', max_length=128)),
                ('scripture_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum.curriculumcourse')),
            ],
            options={
                'ordering': ['course_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('worldview_focus', models.CharField(blank=True, default='', max_length=255)),
                ('scripture_ref', models.CharField(blank=True, default='', max_length=128)),
                ('scripture_text', models.TextField(blank=True, default='')),
                ('resources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.curriculumunit')),
            ],
            options={
                'ordering': ['unit_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uq_curriculum_course_school_code'),
        ),
        migrations.AddConstraint(
            model_name='curriculumunit',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uq_curriculum_unit_course_order'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='uq_curriculum_lesson_unit_order'),
        ),
    ]
