# Generated by Django 5.2.8 on 2026-02-28 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AftercareProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True, unique=True)),
                ('start_time', models.TimeField(default='15:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('late_fee_per_10_min', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('late_fee_grace_minutes', models.IntegerField(default=0)),
                ('late_fee_cap', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('ratio_k_2', models.IntegerField(default=12)),
                ('ratio_3_5', models.IntegerField(default=15)),
                ('ratio_6_8', models.IntegerField(default=18)),
                ('ratio_9_12', models.IntegerField(default=20)),
                ('default_billing_model', models.CharField(choices=[('FLAT_MONTHLY', 'Flat Monthly'), ('PREPAID', 'Prepaid Sessions'), ('DROPIN', 'Drop-in Daily')], default='FLAT_MONTHLY', max_length=20)),
                ('dropin_daily_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('prepaid_session_unit_price', models.DecimalField(decimal_places=2, default=12.0, max_digits=8)),
                ('monthly_rate_1_day', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('monthly_rate_2_days', models.DecimalField(decimal_places=2, default=105.0, max_digits=8)),
                ('monthly_rate_3_days', models.DecimalField(decimal_places=2, default=145.0, max_digits=8)),
                ('monthly_rate_4_days', models.DecimalField(decimal_places=2, default=180.0, max_digits=8)),
                ('monthly_rate_5_days', models.DecimalField(decimal_places=2, default=210.0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AftercareAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_contact_id', models.IntegerField(blank=True, null=True)),
                ('pickup_name_freeform', models.CharField(blank=True, max_length=120)),
                ('pickup_verified', models.BooleanField(default=False)),
                ('late_minutes', models.IntegerField(default=0)),
                ('late_fee_cents', models.IntegerField(default=0)),
                ('late_fee_charge_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'date'], name='aftercare_a_school__dd98f3_idx')],
                'unique_together': {('school_id', 'student_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AftercareEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.JSONField(default=list)),
                ('billing_model', models.CharField(choices=[('FLAT_MONTHLY', 'Flat Monthly'), ('PREPAID', 'Prepaid Sessions'), ('DROPIN', 'Drop-in Daily')], max_length=20)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prepaid_sessions_balance', models.IntegerField(default=0)),
                ('dropin_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'is_active'], name='aftercare_a_school__e6d1d7_idx'), models.Index(fields=['school_id', 'student_id'], name='aftercare_a_school__d3f048_idx')],
            },
        ),
        migrations.CreateModel(
            name='AftercareIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('attendance_id', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major')], default='MINOR', max_length=20)),
                ('description', models.TextField()),
                ('parent_notified', models.BooleanField(default=False)),
                ('discipline_record_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'student_id', 'occurred_at'], name='aftercare_a_school__ce1e6c_idx'), models.Index(fields=['school_id', 'severity', 'occurred_at'], name='aftercare_a_school__e7be52_idx')],
            },
        ),
        migrations.CreateModel(
            name='AftercareMonthlyChargeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'year', 'month'], name='aftercare_a_school__dcff14_idx')],
                'unique_together': {('school_id', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AftercarePickupContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'student_id', 'is_active'], name='aftercare_a_school__deecad_idx')],
            },
        ),
    ]
