# Generated by Django 5.2.14 on 2026-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftercare', '0002_add_uuid_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftercareincident',
            name='discipline_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
