# Generated by Django 5.2.13 on 2026-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftercare', '0003_alter_aftercareincident_discipline_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftercareincident',
            name='discipline_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
