# Generated by Django 5.2.8 on 2026-02-27 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_name', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.CharField(blank=True, default='', max_length=10)),
                ('end_date', models.CharField(blank=True, default='', max_length=10)),
                ('terms_config', models.JSONField(default=list)),
                ('commit_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('terms_set', 'Terms Set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_year_wizard_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_wizard_sessions', to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='academic_ye_school__5c5676_idx')],
            },
        ),
    ]
