$cur = "audit-artifacts/sandbox-launch-5schools/current"
Write-Host "=== SCHOOL MATRIX ==="
Get-Content "$cur/01_school_matrix.csv"
Write-Host ""
Write-Host "=== ROLE FLOW MATRIX ==="
Get-Content "$cur/02_role_flow_matrix.csv"
Write-Host ""
Write-Host "=== BLOCKERS ==="
Get-Content "$cur/03_blocker_log.csv"
Write-Host ""
Write-Host "=== RISKS ==="
Get-Content "$cur/04_risk_register.csv"
Write-Host ""
Write-Host "=== SCOREBOARD ==="
Get-Content "$cur/05_hourly_scoreboard.csv"
Write-Host ""
Write-Host "=== FINAL CLOSEOUT ==="
Get-Content "$cur/20_final_go_no_go.md"
