# Generated by Django 5.2.14 on 2026-05-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialaidrule',
            new_name='home_academ_school__269e9e_idx',
            old_name='home_acade_school__0e7bb3_idx',
        ),
        migrations.RenameIndex(
            model_name='homeacademyenrollment',
            new_name='home_academ_school__a51c31_idx',
            old_name='home_acade_school__69991b_idx',
        ),
        migrations.RenameIndex(
            model_name='homeacademyenrollment',
            new_name='home_academ_school__6d1787_idx',
            old_name='home_acade_school__e8dbdb_idx',
        ),
        migrations.RenameIndex(
            model_name='homeacademyprogram',
            new_name='home_academ_school__302b3f_idx',
            old_name='home_acade_school__d5f6b9_idx',
        ),
        migrations.RenameIndex(
            model_name='offering',
            new_name='home_academ_school__3eba1c_idx',
            old_name='home_acade_school__5dfcdd_idx',
        ),
        migrations.RenameIndex(
            model_name='offering',
            new_name='home_academ_school__1d9d3b_idx',
            old_name='home_acade_school__39a9f8_idx',
        ),
        migrations.RenameIndex(
            model_name='offeringenrollment',
            new_name='home_academ_school__94c900_idx',
            old_name='home_acade_school__0ca03f_idx',
        ),
        migrations.RenameIndex(
            model_name='offeringenrollment',
            new_name='home_academ_school__842864_idx',
            old_name='home_acade_school__295752_idx',
        ),
    ]
