# Generated by Django 5.2.8 on 2026-02-27 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        ('course_catalog_wizard', '0001_initial'),
        ('room_setup_wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSchedulerWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('sections_set', 'Sections Set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=32)),
                ('term_code', models.CharField(blank=True, default='', max_length=16)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('commit_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=32)),
                ('term_code', models.CharField(max_length=16)),
                ('template_code', models.CharField(max_length=16)),
                ('block_code', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course_catalog_wizard.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_setup_wizard.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.school')),
            ],
        ),
    ]
