# Generated by Django 5.2.8 on 2026-02-27 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        ('section_scheduler_wizard', '0001_initial'),
        ('staff_setup_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_setup_wizard.staffmember'),
        ),
        migrations.AddField(
            model_name='sectionschedulerwizardsession',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='sectionschedulerwizardsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'section_code'), name='uniq_section_code_per_year'),
        ),
        migrations.AddIndex(
            model_name='sectionschedulerwizardsession',
            index=models.Index(fields=['school', 'status'], name='section_sch_school__d305b1_idx'),
        ),
    ]
