# Generated by Django 5.2.8 on 2026-02-26 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('speaker', models.CharField(blank=True, default='', max_length=120)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('theme', models.CharField(blank=True, default='', max_length=120)),
                ('scripture_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapel_events_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapel_events', to='core.school')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ChapelAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], default='present', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapel_attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapel_attendances', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapel_attendances', to='core.student')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='spiritual_life.chapelevent')),
            ],
        ),
        migrations.CreateModel(
            name='PastoralNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_date', models.DateField()),
                ('body', models.TextField()),
                ('is_sensitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pastoral_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_notes', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_notes', to='core.student')),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private – pastoral only'), ('staff', 'Staff only'), ('group', 'Small group'), ('school', 'School-wide')], default='staff', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='core.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_groups_led', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_groups', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmallGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='spiritual_life.smallgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_group_members', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_group_memberships', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='SmallGroupSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(db_index=True)),
                ('topic', models.CharField(blank=True, default='', max_length=180)),
                ('scripture_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spiritual_life.smallgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_group_sessions', to='core.school')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='SmallGroupAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_group_attendances', to='core.school')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='spiritual_life.smallgroupmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='spiritual_life.smallgroupsession')),
            ],
        ),
        migrations.CreateModel(
            name='SpiritualAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_title', models.CharField(max_length=180)),
                ('assessment_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spiritual_assessments_administered', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_assessments', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_assessments', to='core.student')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSpiritualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faith_background', models.CharField(blank=True, default='', max_length=120)),
                ('baptized', models.BooleanField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('spiritual_gifts', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_profiles', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_profiles', to='core.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spiritual_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='chapelevent',
            index=models.Index(fields=['school', 'event_date'], name='spiritual_l_school__7ce628_idx'),
        ),
        migrations.AddIndex(
            model_name='chapelattendance',
            index=models.Index(fields=['school', 'event'], name='spiritual_l_school__7539eb_idx'),
        ),
        migrations.AddIndex(
            model_name='chapelattendance',
            index=models.Index(fields=['school', 'student'], name='spiritual_l_school__da64b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapelattendance',
            unique_together={('school', 'event', 'student')},
        ),
        migrations.AddIndex(
            model_name='pastoralnote',
            index=models.Index(fields=['school', 'student', 'note_date'], name='spiritual_l_school__9b3fac_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['school', 'status'], name='spiritual_l_school__cc22b1_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['school', 'visibility'], name='spiritual_l_school__0c1d32_idx'),
        ),
        migrations.AddIndex(
            model_name='smallgroup',
            index=models.Index(fields=['school', 'is_active'], name='spiritual_l_school__e19c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='smallgroupmember',
            index=models.Index(fields=['school', 'group'], name='spiritual_l_school__e96359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smallgroupmember',
            unique_together={('school', 'group', 'student')},
        ),
        migrations.AddIndex(
            model_name='smallgroupsession',
            index=models.Index(fields=['school', 'group', 'session_date'], name='spiritual_l_school__345cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='smallgroupattendance',
            index=models.Index(fields=['school', 'session'], name='spiritual_l_school__30de38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smallgroupattendance',
            unique_together={('school', 'session', 'member')},
        ),
        migrations.AddIndex(
            model_name='spiritualassessment',
            index=models.Index(fields=['school', 'student', 'assessment_date'], name='spiritual_l_school__725fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentspiritualprofile',
            index=models.Index(fields=['school', 'student'], name='spiritual_l_school__1d06bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentspiritualprofile',
            unique_together={('school', 'student')},
        ),
    ]
