# Generated by Django 5.2.8 on 2026-02-27 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_grade_code', models.CharField(max_length=8)),
                ('to_grade_code', models.CharField(max_length=8)),
                ('ordering', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='core.school')),
            ],
            options={
                'ordering': ['ordering', 'from_grade_code'],
                'constraints': [models.UniqueConstraint(fields=('school', 'from_grade_code'), name='uniq_promo_from_grade_per_school')],
            },
        ),
        migrations.CreateModel(
            name='PromotionWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=32)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('commit_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='promotion_w_school__6c7011_idx')],
            },
        ),
    ]
