# Generated by Django 5.2.8 on 2026-02-26 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=96)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_contractor', models.BooleanField(default=False)),
                ('cdl_number', models.CharField(blank=True, default='', max_length=32)),
                ('cdl_expiry', models.DateField(blank=True, null=True)),
                ('background_check_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_drivers', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=96)),
                ('direction', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('MID', 'Midday')], default='AM', max_length=8)),
                ('days_of_week', models.CharField(default='MTWTF', max_length=32)),
                ('active_start', models.DateField(blank=True, null=True)),
                ('active_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='transportation.driver')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('service_date', models.DateField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('BOARDED', 'Boarded'), ('NO_SHOW', 'No Show'), ('LATE', 'Late'), ('INCIDENT', 'Incident')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_ride_events', to='core.school')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transportation.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=96)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('safety_notes', models.TextField(blank=True, default='')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transportation.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_stops', to='core.school')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('school_year', models.CharField(max_length=9)),
                ('is_eligible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dropoff_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_riders', to='transportation.stop')),
                ('pickup_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_riders', to='transportation.stop')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_riders', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('VAN', 'Van'), ('CARPOOL', 'Carpool')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('plate', models.CharField(blank=True, default='', max_length=24)),
                ('vin', models.CharField(blank=True, default='', max_length=32)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='core.school')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='transportation.vehicle'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_override', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.school')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='transportation.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transportation.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='transportation.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['school', 'is_deleted'], name='transportat_school__04b390_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['school', 'service_date', 'event_type', 'is_deleted'], name='transportat_school__99ee55_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['school', 'route', 'order', 'is_deleted'], name='transportat_school__d56ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrider',
            index=models.Index(fields=['school', 'student_id', 'school_year', 'is_deleted'], name='transportat_school__ad590c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['school', 'vehicle_type', 'is_deleted'], name='transportat_school__f79e65_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['school', 'direction', 'is_deleted'], name='transportat_school__eb9326_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school', 'route', 'start_date', 'is_deleted'], name='transportat_school__232ed9_idx'),
        ),
    ]
