# Generated by Django 5.2.8 on 2026-02-27 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_crown_permission_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scale_type', models.CharField(choices=[('LETTER', 'Letter Grades (A–F)'), ('PERCENT', 'Percent (0–100)')], default='LETTER', max_length=10)),
                ('rounding', models.CharField(choices=[('NEAREST', 'Round to nearest'), ('FLOOR', 'Always round down (floor)'), ('CEIL', 'Always round up (ceiling)')], default='NEAREST', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='GradeScaleBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('min_pct', models.IntegerField()),
                ('max_pct', models.IntegerField()),
                ('ordering', models.IntegerField()),
                ('gpa_points', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grade_scale_wizard.gradescale')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='GradeScaleWizardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scale_config', models.JSONField(default=None, null=True)),
                ('bands_config', models.JSONField(default=list)),
                ('weights_config', models.JSONField(default=None, null=True)),
                ('commit_result', models.JSONField(default=None, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('bands_set', 'Bands set'), ('weights_set', 'Weights set'), ('committed', 'Committed'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scale_sessions', to='core.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scale_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scale_sessions', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='TermWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_code', models.CharField(max_length=20)),
                ('weight_bp', models.IntegerField(help_text='Basis points (10 000 bp = 100 %)')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_weights', to='grade_scale_wizard.gradescale')),
            ],
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['school', 'academic_year', 'is_active'], name='grade_scale_school__3aaf7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='uniq_grade_scale_school_year_name'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.UniqueConstraint(fields=('scale', 'label'), name='uniq_grade_band_scale_label'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.UniqueConstraint(fields=('scale', 'ordering'), name='uniq_grade_band_scale_ordering'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.CheckConstraint(condition=models.Q(('min_pct__gte', 0)), name='chk_band_min_pct_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.CheckConstraint(condition=models.Q(('max_pct__lte', 100)), name='chk_band_max_pct_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.CheckConstraint(condition=models.Q(('min_pct__lt', models.F('max_pct'))), name='chk_band_min_lt_max'),
        ),
        migrations.AddIndex(
            model_name='gradescalewizardsession',
            index=models.Index(fields=['school', 'status'], name='grade_scale_school__c1fdf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='termweight',
            constraint=models.UniqueConstraint(fields=('scale', 'term_code'), name='uniq_term_weight_scale_code'),
        ),
        migrations.AddConstraint(
            model_name='termweight',
            constraint=models.CheckConstraint(condition=models.Q(('weight_bp__gt', 0), ('weight_bp__lte', 10000)), name='chk_term_weight_bp_range'),
        ),
    ]
