# Generated by Django 5.2.8 on 2026-01-25 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0009_applications_core"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account', to='households.household')),
            ],
            options={
                'db_table': 'ledger_account',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_void', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='ledger.ledgeraccount')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ledger.ledgeraccount')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ledger.charge')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.payment')),
            ],
            options={
                'db_table': 'allocation',
            },
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['school_id'], name='ledger_acco_school__370c55_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['school_id', 'account'], name='charge_school__ae48df_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['school_id', 'created_at'], name='charge_school__c7678d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school_id', 'account'], name='payment_school__80ff35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school_id', 'created_at'], name='payment_school__826175_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['school_id', 'payment'], name='allocation_school__39aa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['school_id', 'charge'], name='allocation_school__e24892_idx'),
        ),
    ]
