# Generated by Django 6.0 on 2026-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0010_ledger_core"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.allocation',),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uniq_payment_charge_allocation'),
        ),
    ]
