# Generated by Django 5.2.8 on 2026-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0050_ledger_allocations"),
        ("crown_api", "0007_messagethread_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="source",
            field=models.CharField(db_index=True, default="EXTERNAL", max_length=32),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
