# Generated by Django 5.2.8 on 2026-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0060_ledger_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
