# Generated by Django 5.2.8 on 2026-02-28 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0061_payment_is_void'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPayoutAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('audit_date', models.DateField(db_index=True)),
                ('expected_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verified', models.BooleanField(default=False)),
                ('processor_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_payout_audit',
                'indexes': [models.Index(fields=['school_id', 'audit_date'], name='daily_payou_school__04057a_idx'), models.Index(fields=['school_id', 'verified'], name='daily_payou_school__ec67b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'audit_date'), name='uniq_daily_payout_audit_school_date')],
            },
        ),
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('dispute_reason', models.TextField()),
                ('dispute_status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], db_index=True, default='open', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargebacks', to='ledger.payment')),
            ],
            options={
                'db_table': 'chargeback',
                'indexes': [models.Index(fields=['school_id', 'dispute_status'], name='chargeback_school__fa6b37_idx'), models.Index(fields=['school_id', 'opened_at'], name='chargeback_school__db0c81_idx')],
            },
        ),
        migrations.CreateModel(
            name='DunningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('resolved', 'Resolved'), ('delinquent', 'Delinquent')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processor_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_record', to='ledger.payment')),
            ],
            options={
                'db_table': 'dunning_record',
                'indexes': [models.Index(fields=['school_id', 'status'], name='dunning_rec_school__d21b1e_idx'), models.Index(fields=['school_id', 'next_retry_at'], name='dunning_rec_school__56b6db_idx')],
            },
        ),
    ]
