# Generated by Django 5.2.8 on 2026-02-28 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardExecutiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('enrollment_health', models.IntegerField(default=0)),
                ('financial_health', models.IntegerField(default=0)),
                ('culture_health', models.IntegerField(default=0)),
                ('mission_health', models.IntegerField(default=0)),
                ('retention_risk', models.IntegerField(default=0)),
                ('highlights', models.JSONField(default=list)),
                ('watchlist', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'as_of_date'], name='signals_boa_school__824a80_idx')],
                'unique_together': {('school_id', 'as_of_date')},
            },
        ),
        migrations.CreateModel(
            name='InterventionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('case_id', models.IntegerField(db_index=True)),
                ('action_type', models.CharField(default='NOTE', max_length=24)),
                ('note', models.TextField()),
                ('created_by_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'case_id', 'created_at'], name='signals_int_school__25d4cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=16)),
                ('priority', models.CharField(default='MED', max_length=12)),
                ('reason', models.CharField(max_length=200)),
                ('linked_signals', models.JSONField(default=list)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'status', 'priority'], name='signals_int_school__ff06f3_idx'), models.Index(fields=['school_id', 'student_id', 'status'], name='signals_int_school__d644c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('severity_weight', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'is_active'], name='signals_sig_school__1612aa_idx')],
                'unique_together': {('school_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('signal_key', models.SlugField(max_length=64)),
                ('weight', models.IntegerField(default=10)),
                ('summary', models.CharField(max_length=200)),
                ('details', models.JSONField(default=dict)),
                ('fired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'student_id', 'fired_at'], name='signals_sig_school__0c5315_idx'), models.Index(fields=['school_id', 'signal_key', 'fired_at'], name='signals_sig_school__5126a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(db_index=True)),
                ('student_id', models.IntegerField(db_index=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='LOW', max_length=12)),
                ('drivers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['school_id', 'as_of_date', 'risk_level'], name='signals_stu_school__75d627_idx'), models.Index(fields=['school_id', 'student_id'], name='signals_stu_school__712107_idx')],
                'unique_together': {('school_id', 'student_id', 'as_of_date')},
            },
        ),
    ]
