# Generated by Django 5.2.8 on 2026-03-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_rebuild_uuid_fks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boardexecutivemetric',
            new_name='signals_boa_school__824a80_idx',
            old_name='signals_bem2_date_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionaction',
            new_name='signals_int_school__25d4cf_idx',
            old_name='signals_ia2_case_date_idx',
        ),
        migrations.RenameIndex(
            model_name='interventioncase',
            new_name='signals_int_school__ff06f3_idx',
            old_name='signals_ic2_status_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='interventioncase',
            new_name='signals_int_school__d644c9_idx',
            old_name='signals_ic2_stu_status_idx',
        ),
        migrations.RenameIndex(
            model_name='signaldefinition',
            new_name='signals_sig_school__1612aa_idx',
            old_name='signals_sig2_school_active_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='signals_sig_school__0c5315_idx',
            old_name='signals_evt2_stu_date_idx',
        ),
        migrations.RenameIndex(
            model_name='signalevent',
            new_name='signals_sig_school__5126a5_idx',
            old_name='signals_evt2_key_date_idx',
        ),
        migrations.RenameIndex(
            model_name='studentrisksnapshot',
            new_name='signals_stu_school__75d627_idx',
            old_name='signals_rsk2_date_lvl_idx',
        ),
        migrations.RenameIndex(
            model_name='studentrisksnapshot',
            new_name='signals_stu_school__712107_idx',
            old_name='signals_rsk2_school_stu_idx',
        ),
    ]
