# Generated by Django 5.2.17 on 2026-10-01 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_rename_signals_bem2_date_idx_signals_boa_school__824a80_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionaction',
            name='created_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='owner_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_intervention_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventioncase',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interventionaction',
            name='created_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
