# Generated by Django 5.2.17 on 2026-10-04 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_student_health_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_authority_verified', models.BooleanField(default=False)),
                ('medication', models.CharField(max_length=160)),
                ('dose', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(max_length=24)),
                ('route', models.CharField(max_length=40)),
                ('directions', models.CharField(max_length=2000)),
                ('order_evidence', models.CharField(max_length=300)),
                ('consent_evidence', models.CharField(max_length=300)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=2000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.guardian')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('visit', 'Visit'), ('administration', 'Administration'), ('immunization', 'Immunization'), ('care_plan', 'Care_Plan')], max_length=24)),
                ('occurred_at', models.DateTimeField()),
                ('topic', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=4000)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=300)),
                ('administration_state', models.CharField(blank=True, choices=[('given', 'Given'), ('refused', 'Refused'), ('not_given', 'Not_Given')], max_length=16)),
                ('administered_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('administered_unit', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrects', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='student_health.healthentry')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_health.medicationauthorization')),
            ],
            options={
                'ordering': ['-occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HealthMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=24)),
                ('result', models.JSONField()),
                ('reason', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'actor', 'request_key'), name='student_health_retry')],
            },
        ),
        migrations.AddIndex(
            model_name='medicationauthorization',
            index=models.Index(fields=['school', 'student', 'ends_on'], name='student_hea_school__21307c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthentry',
            index=models.Index(fields=['school', 'student', 'occurred_at'], name='student_hea_school__1d3c58_idx'),
        ),
    ]
