# Generated by Django 6.0 on 2026-01-03 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.chartaccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.journalbatch'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.family'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.ledgerentry'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.school'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.school'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='core.school'),
        ),
        migrations.AddField(
            model_name='family',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='core.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.school'),
        ),
        migrations.AddField(
            model_name='aidreview',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_reviews', to='core.school'),
        ),
        migrations.AddField(
            model_name='aiddocument',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_documents', to='core.school'),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_awards', to='core.school'),
        ),
        migrations.AddField(
            model_name='aidauditevent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_audit_events', to='core.school'),
        ),
        migrations.AddField(
            model_name='aidapplication',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_applications', to='core.school'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='core.school'),
        ),
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.school'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gradelevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.family'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),
        migrations.AddField(
            model_name='aidaward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_awards', to='core.student'),
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tuitions', to='core.school'),
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='core.student'),
        ),
        migrations.AddField(
            model_name='tuitionplan',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plans', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='tuitionplan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_plans', to='core.school'),
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='tuition_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tuitionplan'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.school'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('school', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('school', 'family_name')},
        ),
        migrations.AlterUniqueTogether(
            name='aidapplication',
            unique_together={('school', 'family', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('school', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('school', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'student_number')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('school', 'student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='aidaward',
            unique_together={('school', 'student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='tuitionplan',
            unique_together={('school', 'academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studenttuition',
            unique_together={('school', 'student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('school', 'user', 'role_code')},
        ),
    ]
