# Generated by Django 6.0 on 2026-01-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiddocument',
            name='aid_application',
        ),
        migrations.RemoveField(
            model_name='aidreview',
            name='aid_application',
        ),
        migrations.RemoveField(
            model_name='aidauditevent',
            name='actor_user',
        ),
        migrations.RemoveField(
            model_name='aidauditevent',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='aidaward',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aidaward',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='aidaward',
            name='decided_by_user',
        ),
        migrations.RemoveField(
            model_name='aidaward',
            name='school',
        ),
        migrations.RemoveField(
            model_name='aidaward',
            name='student',
        ),
        migrations.RemoveField(
            model_name='aiddocument',
            name='school',
        ),
        migrations.RemoveField(
            model_name='aidreview',
            name='reviewer_user',
        ),
        migrations.RemoveField(
            model_name='aidreview',
            name='school',
        ),
        migrations.DeleteModel(
            name='AidApplication',
        ),
        migrations.DeleteModel(
            name='AidAuditEvent',
        ),
        migrations.DeleteModel(
            name='AidAward',
        ),
        migrations.DeleteModel(
            name='AidDocument',
        ),
        migrations.DeleteModel(
            name='AidReview',
        ),
    ]
