# Generated by Django 6.0 on 2026-02-01 00:00

import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aiddocument_aid_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ('env_name', models.CharField(max_length=32, default='unknown', db_index=True)),
                ('build_sha', models.CharField(max_length=64, default='unknown', db_index=True)),
                ('school_id', models.UUIDField(null=True, blank=True, db_index=True)),
                ('command', models.CharField(max_length=128, default='golden_path_bootstrap', db_index=True)),
                ('force', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=16, default='started', db_index=True)),
                ('summary_json', models.JSONField(default=dict, blank=True)),
                ('error_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
