# Generated by Django 5.2.8 on 2026-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crown_permission_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Django app label + model, e.g. "audit.AuditLog"', max_length=100, unique=True)),
                ('retention_days', models.IntegerField(default=365, help_text='Days to retain records from created_at before purging.')),
                ('legal_hold', models.BooleanField(default=False, help_text='When True, this model is excluded from automated purge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'ordering': ['model_name'],
            },
        ),
    ]
