# Generated by Django 5.2.8 on 2026-03-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_data_destruction_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataDestructionCertificate',
        ),
    ]
