# Generated by Django 5.2.12 on 2026-03-16 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_datadestructioncertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdFamilyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(choices=[('admissions', 'From AdmissionsApplication'), ('enrollment', 'From enrollment event'), ('import', 'From SIS import'), ('manual', 'Manual linking')], max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_family_links', to='core.family')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_family_links', to='core.school')),
            ],
            options={
                'unique_together': {('household_id', 'family')},
            },
        ),
    ]
