# Generated by Django 5.2.12 on 2026-03-16 12:52

from django.db import migrations


def backfill_household_family_links(apps, schema_editor):
    """
    Seed HouseholdFamilyLink from existing AdmissionsApplication rows
    where both family and household are set (the original temporary bridge).
    Idempotent via get_or_create.
    """
    AdmissionsApplication = apps.get_model('admissions', 'AdmissionsApplication')
    HouseholdFamilyLink = apps.get_model('core', 'HouseholdFamilyLink')

    rows = (
        AdmissionsApplication.objects
        .filter(family__isnull=False, household__isnull=False)
        .values('school_id', 'family_id', 'household_id')
        .distinct()
    )

    for row in rows:
        HouseholdFamilyLink.objects.get_or_create(
            household_id=row['household_id'],
            family_id=row['family_id'],
            defaults={
                'school_id': row['school_id'],
                'source': 'admissions',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_household_family_link'),
        ('admissions', '0003_alter_admissionsapplication_status'),
    ]

    operations = [
        migrations.RunPython(
            backfill_household_family_links,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
