# Generated by Django 5.2.14 on 2026-05-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retentionpurgeaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.useraccount'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.useraccount'),
        ),
    ]
