import { BASE_NOTE } from './_baseData.js';

const APPLICATION_VOLUME_TREND = [
  { month: 'Sep', value: 12 },
  { month: 'Oct', value: 18 },
  { month: 'Nov', value: 24 },
  { month: 'Dec', value: 19 },
  { month: 'Jan', value: 31 },
  { month: 'Feb', value: 38 },
  { month: 'Mar', value: 42 },
];

const CONVERSION_RATE_TREND = [
  { month: 'Sep', value: 58 },
  { month: 'Oct', value: 62 },
  { month: 'Nov', value: 60 },
  { month: 'Dec', value: 63 },
  { month: 'Jan', value: 65 },
  { month: 'Feb', value: 67 },
  { month: 'Mar', value: 68 },
];

export default {
  key: 'admissions',
  activePath: '/admissions',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 5,
  user: {
    initials: 'LT',
    name: 'Lisa Thompson',
    role: 'Admissions Manager',
  },
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Lisa!',
  subtitle: 'Heritage Christian Academy',
  note: BASE_NOTE,

  metrics: [
    { label: 'Open Applications', value: '84', detail: '12 awaiting principal signoff — action needed today.', accent: 'blue' },
    { label: 'Tours Scheduled', value: '14', detail: 'Three families added this week. Thursday slots still open.', accent: 'navy' },
    { label: 'Accepted Students', value: '31', detail: '6 accepted families have not yet returned enrollment packets.', accent: 'gold' },
    { label: 'Conversion Rate', value: '68%', detail: 'Up 5 points from February — best of the year.', accent: 'emerald' },
  ],

  priorities: [
    { title: '12 applications pending principal signoff', detail: 'Review committee met yesterday — principal approval required before 10:30 AM.', state: 'In Progress', tone: 'warn' },
    { title: 'Follow up with 6 families ready to enroll', detail: 'Accepted — paperwork not returned. 72-hour window closing today.', state: 'Ready', tone: 'warn' },
    { title: 'Confirm Thursday tour schedule', detail: 'Two families have not confirmed. Contact by 1 PM to secure attendance.', state: 'Ready', tone: 'good' },
  ],
  prioritiesTitle: 'Admissions execution queue',

  alerts: [
    { title: '8 incomplete applications at 72-hour deadline', detail: 'Missing documents. Families must complete or lose their review slot.', tone: 'warn' },
    { title: '2 accepted families missing enrollment packets', detail: 'Packets due by Friday — seat held pending receipt. Contact today.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'pipeline',
      icon: 'PL',
      title: 'Application Pipeline',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '84 open applications',
      summary: '12 applications require principal signoff before morning pipeline review closes.',
      kpis: [
        { label: 'Open applications', value: '84' },
        { label: 'Awaiting signoff', value: '12' },
        { label: 'Incomplete at deadline', value: '8' },
        { label: 'New this week', value: '11' },
      ],
      details: [
        '12 applications approved by committee — need principal signature',
        '8 incomplete applications flagged at 72-hour warning',
        '11 new applications received this week',
        'Pipeline review closes at 10:30 AM',
      ],
      primaryActionLabel: 'Review Pipeline',
      backActionLabel: 'All Applications',
      primaryActionHref: '/admissions/pipeline',
      backActionHref: '/admissions',
      lastUpdated: '8:48 AM',
    },
    {
      key: 'tours',
      icon: 'TO',
      title: 'Tours & Campus Visits',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '14 tours scheduled',
      summary: 'Thursday tour has 2 unconfirmed families — contact required before 1 PM.',
      kpis: [
        { label: 'Scheduled this week', value: '14' },
        { label: 'Confirmed', value: '12' },
        { label: 'Awaiting confirmation', value: '2' },
        { label: 'Available tour slots', value: '4' },
      ],
      details: [
        '2 Thursday tour families unconfirmed — call before 1 PM',
        '12 families confirmed for scheduled campus visits',
        '4 open tour slots available next week',
        'Virtual tour option available for remote families',
      ],
      primaryActionLabel: 'View Tours',
      backActionLabel: 'Schedule Tour',
      primaryActionHref: '/admissions',
      backActionHref: '/admissions/pipeline',
      lastUpdated: '8:30 AM',
    },
    {
      key: 'acceptance',
      icon: 'AC',
      title: 'Acceptance & Decision',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '31 students accepted',
      summary: '6 accepted families have not returned enrollment packets — follow-up due today.',
      kpis: [
        { label: 'Accepted students', value: '31' },
        { label: 'Enrollment packets returned', value: '25' },
        { label: 'Packets outstanding', value: '6' },
        { label: 'Deposits received', value: '22' },
      ],
      details: [
        '6 accepted families have not returned enrollment packets',
        'Seat holds expire Friday if packets not received',
        '22 enrollment deposits confirmed — 9 still pending',
        'Acceptance letter batch sent for the week',
      ],
      primaryActionLabel: 'Review Acceptances',
      backActionLabel: 'Pipeline View',
      primaryActionHref: '/admissions/pipeline',
      backActionHref: '/admissions',
      lastUpdated: '8:38 AM',
    },
    {
      key: 'enrollment',
      icon: 'EN',
      title: 'Enrollment Conversion',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '68% conversion rate',
      summary: 'Best conversion rate of the year. 22 enrollment deposits secured this cycle.',
      kpis: [
        { label: 'Conversion rate', value: '68%' },
        { label: 'Enrolled students', value: '22' },
        { label: 'Reenrolling students', value: '188' },
        { label: 'New family yield', value: '+14 vs prior yr' },
      ],
      details: [
        '68% conversion — up from 63% in January',
        '22 new enrollment deposits received this cycle',
        '188 students confirmed for reenrollment',
        'Yield improvement: +14 new families vs prior year',
      ],
      primaryActionLabel: 'Open Enrollment',
      backActionLabel: 'Pipeline View',
      primaryActionHref: '/reenrollment',
      backActionHref: '/admissions/pipeline',
      lastUpdated: '8:25 AM',
    },
    {
      key: 'family-follow-up',
      icon: 'FF',
      title: 'Family Follow-up',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '6 families need contact today',
      summary: 'Accepted families with outstanding paperwork require personal outreach today.',
      kpis: [
        { label: 'Immediate follow-up', value: '6' },
        { label: 'Follow-up queue total', value: '18' },
        { label: 'Contacted this week', value: '12' },
        { label: 'Tours confirmed via follow-up', value: '4' },
      ],
      details: [
        '6 accepted families — packets due Friday, no response yet',
        '18 families in active follow-up queue',
        '4 tour confirmations closed through follow-up this week',
        'Auto-email follow-up sent — personal call recommended for 6 priority families',
      ],
      primaryActionLabel: 'Open Communications',
      backActionLabel: 'View Pipeline',
      primaryActionHref: '/communications',
      backActionHref: '/admissions/pipeline',
      lastUpdated: '8:22 AM',
    },
    {
      key: 'inquiry',
      icon: 'IQ',
      title: 'Inquiry & Marketing',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '42 inquiries this month',
      summary: 'March inquiry volume is the highest of the year. Digital leads converting at 22%.',
      kpis: [
        { label: 'Inquiries this month', value: '42' },
        { label: 'Digital leads', value: '28' },
        { label: 'Lead conversion rate', value: '22%' },
        { label: 'Open house registrations', value: '17' },
      ],
      details: [
        '42 inquiries in March — highest single-month count',
        '28 digital leads from school website form',
        'Open house on May 14 — 17 families registered',
        'Social media referral source tracking active',
      ],
      primaryActionLabel: 'View Inquiry Pipeline',
      backActionLabel: 'Admissions Overview',
      primaryActionHref: '/admissions',
      backActionHref: '/admissions',
      lastUpdated: '8:10 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Application volume trend',
      title: 'New applications received — by month',
      chip: 'Accelerating',
      trend: APPLICATION_VOLUME_TREND,
    },
    {
      kicker: 'Conversion rate trend',
      title: 'Inquiry-to-enrollment conversion rate — semester',
      chip: 'Best rate this year',
      trend: CONVERSION_RATE_TREND,
    },
  ],

  activityKicker: 'Admissions activity',
  activityTitle: 'Recent admissions events',
  activities: [
    '12 applications forwarded to principal for signoff.',
    'Thursday tour confirmations sent to 12 of 14 families.',
    'Enrollment packet reminder emailed to 6 accepted families.',
    '8 incomplete applications flagged at 72-hour deadline.',
    'March inquiry volume hit 42 — highest of the year.',
  ],

  quickActions: [
    {
      title: 'Review Pipeline',
      eyebrow: 'Quick action',
      description: 'Open application pipeline — 12 items need principal signoff today.',
      actionLabel: 'Review Pipeline',
      href: '/admissions/pipeline',
      allowedRoles: ['admissions'],
    },
    {
      title: 'Send Follow-up',
      eyebrow: 'Quick action',
      description: 'Contact accepted families with outstanding enrollment packets.',
      actionLabel: 'Open Communications',
      href: '/communications',
      allowedRoles: ['admissions'],
    },
    {
      title: 'Process Enrollment',
      eyebrow: 'Quick action',
      description: 'Review and confirm enrollment deposits and new student setup.',
      actionLabel: 'Open Enrollment',
      href: '/reenrollment',
      allowedRoles: ['admissions'],
    },
    {
      title: 'View Applications',
      eyebrow: 'Quick action',
      description: 'Open full application list and status tracking.',
      actionLabel: 'All Applications',
      href: '/admissions',
      allowedRoles: ['admissions'],
    },
  ],

  statusTitle: 'Admissions systems',
  statusKicker: 'System health',
  statuses: [
    { label: 'Application Portal', state: 'Accepting submissions' },
    { label: 'Enrollment System', state: 'Open' },
    { label: 'CRM Sync', state: 'Current' },
    { label: 'Family Comms', state: 'Active' },
  ],
};
