import { BASE_NOTE } from './_baseData.js';

const MESSAGE_VOLUME_TREND = [
  { month: 'Sep', value: 142 },
  { month: 'Oct', value: 158 },
  { month: 'Nov', value: 171 },
  { month: 'Dec', value: 139 },
  { month: 'Jan', value: 162 },
  { month: 'Feb', value: 174 },
  { month: 'Mar', value: 186 },
];

const ENGAGEMENT_TREND = [
  { month: 'Sep', value: 72 },
  { month: 'Oct', value: 74 },
  { month: 'Nov', value: 75 },
  { month: 'Dec', value: 71 },
  { month: 'Jan', value: 76 },
  { month: 'Feb', value: 78 },
  { month: 'Mar', value: 79 },
];

export default {
  key: 'communications',
  activePath: '/communications',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 4,
  user: {
    initials: 'JC',
    name: 'James Carter',
    role: 'Communications Coordinator',
  },
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, James!',
  subtitle: 'Heritage Christian Academy',
  note: BASE_NOTE,

  dataSource: 'live_api',
  apiEndpoint: '/api/v1/dashboards/communications/summary/',
  liveDataKey: 'communications',
  metrics: [
    { label: 'Messages Queued', value: '18', detail: 'Ready for approval or scheduling â€” 4 are time-sensitive.', accent: 'blue' },
    { label: 'Unread Threads', value: '9', detail: 'Parent and staff threads requiring triage before noon.', accent: 'gold' },
    { label: 'Announcements Sent', value: '4', detail: 'Published this morning to families and staff.', accent: 'navy' },
    { label: 'Delivery Health', value: '99.4%', detail: 'Outbound message success rate â€” 2 contacts flagged.', accent: 'emerald' },
  ],

  priorities: [
    { title: 'Publish weekly parent bulletin', detail: 'Draft is ready â€” principal approval received. Publish before 9 AM.', state: 'Draft ready', tone: 'warn' },
    { title: 'Respond to 5 priority parent inquiries', detail: 'Threads marked urgent â€” 3 from teachers, 2 from front office.', state: 'Before lunch', tone: 'warn' },
    { title: 'Schedule Thursday chapel announcement', detail: 'Message drafted. Needs scheduling for Wednesday 4 PM delivery.', state: 'Ready', tone: 'good' },
  ],
  prioritiesTitle: 'Communications execution queue',

  alerts: [
    { title: '2 undelivered messages â€” contact info needed', detail: 'Two family records have stale email addresses. Records office must update.', tone: 'warn' },
    { title: 'Social media post pending principal approval', detail: 'Spring Open House post drafted and queued â€” approval required before publication.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'announcements',
      icon: 'AN',
      title: 'Announcements',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '18 messages queued',
      summary: 'Parent bulletin is approved and ready â€” publish before the 9 AM open.',
      kpis: [
        { label: 'Messages queued', value: '18' },
        { label: 'Published today', value: '4' },
        { label: 'Pending approval', value: '2' },
        { label: 'Scheduled', value: '3' },
      ],
      details: [
        'Weekly parent bulletin approved â€” ready to publish',
        '3 messages scheduled for this week',
        '2 messages awaiting principal approval',
        'Thursday chapel announcement drafted and queued',
      ],
      primaryActionLabel: 'Publish Announcement',
      backActionLabel: 'All Announcements',
      primaryActionHref: '/communications',
      backActionHref: '/communications-director',
      lastUpdated: '8:49 AM',
    },
    {
      key: 'parent-comms',
      icon: 'PC',
      title: 'Parent Communications',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '9 unread threads',
      summary: '5 priority parent threads marked for before-noon response.',
      kpis: [
        { label: 'Unread threads', value: '9' },
        { label: 'Priority threads', value: '5' },
        { label: 'Responded today', value: '3' },
        { label: 'Avg response time', value: '4.2 hrs' },
      ],
      details: [
        '5 threads flagged urgent â€” 3 from teachers, 2 front office',
        'Average response time 4.2 hours vs 4-hour target',
        '2 contact records with invalid email addresses',
        'Auto-acknowledgment active for all new threads',
      ],
      primaryActionLabel: 'Open Message Center',
      backActionLabel: 'All Parent Threads',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:41 AM',
    },
    {
      key: 'staff-messaging',
      icon: 'SM',
      title: 'Staff Messaging',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '4 staff messages sent today',
      summary: 'All staff announcements delivered. No delivery failures on staff channel.',
      kpis: [
        { label: 'Staff messages sent today', value: '4' },
        { label: 'Staff channels active', value: '3' },
        { label: 'Read rate (today)', value: '81%' },
        { label: 'Open staff threads', value: '2' },
      ],
      details: [
        'Principal morning memo delivered â€” 81% read rate',
        'Academic calendar reminder sent to all teaching staff',
        'Safety protocol update distributed school-wide',
        '2 open staff threads â€” non-urgent',
      ],
      primaryActionLabel: 'Open Staff Channel',
      backActionLabel: 'Communications Director',
      primaryActionHref: '/communications-director',
      backActionHref: '/communications',
      lastUpdated: '8:30 AM',
    },
    {
      key: 'bulletin',
      icon: 'BU',
      title: 'School Bulletin',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: 'Bulletin ready to publish',
      summary: 'Weekly bulletin approved by principal â€” waiting to be published before 9 AM.',
      kpis: [
        { label: 'Status', value: 'Approved' },
        { label: 'Last published', value: 'Last Thursday' },
        { label: 'Stories included', value: '6' },
        { label: 'Estimated reads', value: '430+' },
      ],
      details: [
        'Bulletin approved â€” principal signature on file',
        '6 stories finalized: calendar, chapel, sports, events, academics, faith',
        'Expected audience: 430+ families and staff',
        'Archived bulletins available in communications director view',
      ],
      primaryActionLabel: 'Publish Bulletin',
      backActionLabel: 'Bulletin Archive',
      primaryActionHref: '/communications-director',
      backActionHref: '/communications-director',
      lastUpdated: '8:46 AM',
    },
    {
      key: 'alert-system',
      icon: 'AL',
      title: 'Alert System',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: 'No active alerts',
      summary: 'Emergency and safety alert system is healthy. All channels operational.',
      kpis: [
        { label: 'Alert status', value: 'Normal' },
        { label: 'Last test', value: 'Apr 21' },
        { label: 'Channels ready', value: '4 of 4' },
        { label: 'Contact list currency', value: '99.1%' },
      ],
      details: [
        'All 4 alert channels tested and operational',
        'Contact database 99.1% current â€” 2 records need update',
        'Last emergency alert test: April 21',
        'Next scheduled drill: May 15',
      ],
      primaryActionLabel: 'View Alert System',
      backActionLabel: 'Communications',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:00 AM',
    },
    {
      key: 'digital',
      icon: 'DG',
      title: 'Digital & Social',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: 'Spring post pending approval',
      summary: 'Spring Open House social media post drafted â€” principal approval required.',
      kpis: [
        { label: 'Pending approval', value: '1' },
        { label: 'Posts published this month', value: '8' },
        { label: 'Avg engagement rate', value: '79%' },
        { label: 'Website news items', value: '3 queued' },
      ],
      details: [
        'Spring Open House announcement post awaiting principal approval',
        '3 website news items queued for this week',
        '8 social posts this month â€” 79% average engagement rate',
        'Next scheduled post: Thursday before chapel',
      ],
      primaryActionLabel: 'View Digital Queue',
      backActionLabel: 'Communications Director',
      primaryActionHref: '/communications-director',
      backActionHref: '/communications-director',
      lastUpdated: '8:18 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Message volume trend',
      title: 'Total outbound messages sent â€” by month',
      chip: 'Up 31% since September',
      trend: MESSAGE_VOLUME_TREND,
    },
    {
      kicker: 'Parent engagement trend',
      title: 'Parent message open/read rate â€” by month',
      chip: 'Growing steadily',
      trend: ENGAGEMENT_TREND,
    },
  ],

  activityKicker: 'Communications activity',
  activityTitle: 'Recent communications events',
  activities: [
    'Parent bulletin approved by principal â€” ready to publish.',
    '5 priority parent threads flagged for before-noon response.',
    '4 announcements published to families and staff this morning.',
    'Social media post for Open House drafted and queued.',
    '2 undeliverable emails flagged â€” records office notified.',
  ],

  quickActions: [
    {
      title: 'Publish Announcement',
      eyebrow: 'Quick action',
      description: 'Release approved bulletin and queued announcements to families.',
      actionLabel: 'Publish Announcement',
      href: '/communications',
      allowedRoles: ['communications'],
    },
    {
      title: 'Open Message Center',
      eyebrow: 'Quick action',
      description: 'Triage 9 unread parent and staff threads before noon.',
      actionLabel: 'Open Messages',
      href: '/communications',
      allowedRoles: ['communications'],
    },
    {
      title: 'Review Bulletin',
      eyebrow: 'Quick action',
      description: 'Finalize and publish the weekly school bulletin.',
      actionLabel: 'Open Bulletin',
      href: '/communications-director',
      allowedRoles: ['communications'],
    },
    {
      title: 'View All Communications',
      eyebrow: 'Quick action',
      description: 'Open the full communications director view for all channels.',
      actionLabel: 'All Communications',
      href: '/communications',
      allowedRoles: ['communications'],
    },
  ],

  statusTitle: 'Communications systems',
  statusKicker: 'System health',
  statuses: [
    { label: 'Messaging System', state: 'Operational' },
    { label: 'Delivery Gateway', state: 'Healthy' },
    { label: 'Parent Portal', state: 'Connected' },
    { label: 'Staff Channel', state: 'Active' },
  ],
};

