import { LIVE_NOTE } from './_baseData.js';

const COLLECTIONS_TREND = [
  { month: 'Sep', value: 241000 },
  { month: 'Oct', value: 258000 },
  { month: 'Nov', value: 262000 },
  { month: 'Dec', value: 245000 },
  { month: 'Jan', value: 270000 },
  { month: 'Feb', value: 278000 },
  { month: 'Mar', value: 284500 },
];

const AR_AGING_TREND = [
  { month: 'Sep', value: 168000 },
  { month: 'Oct', value: 162000 },
  { month: 'Nov', value: 155000 },
  { month: 'Dec', value: 159000 },
  { month: 'Jan', value: 151000 },
  { month: 'Feb', value: 149000 },
  { month: 'Mar', value: 148200 },
];

export default {
  key: 'finance',
  activePath: '/finance',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 9,
  user: {
    initials: 'RW',
    name: 'Rebecca Walsh',
    role: 'Business Office Director',
  },
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Rebecca!',
  subtitle: 'Heritage Christian Academy',
  note: LIVE_NOTE,
  dataSource: 'live_api',
  apiEndpoint: '/api/v1/dashboards/finance/summary/',
  liveDataKey: 'finance',

  metrics: [
    { label: 'AR Outstanding', value: '$148,200', detail: 'Total outstanding family receivables â€” 94.2% collection rate.', accent: 'navy' },
    { label: 'Collected This Month', value: '$284,500', detail: 'March collections â€” 8% above March prior year.', accent: 'emerald' },
    { label: 'Payment Plans Active', value: '412', detail: '98.4% of plans current â€” 7 behind schedule.', accent: 'blue' },
    { label: 'Open Exceptions', value: '9', detail: '9 items require specialist review before noon.', accent: 'gold' },
    { label: 'Aid Applications', value: '24', detail: '3 applications pending approval â€” deadline this week.', accent: 'navy' },
    { label: 'Collection Rate', value: '94.2%', detail: 'Above the 93% semester target. Trend stable.', accent: 'emerald' },
  ],

  priorities: [
    { title: 'Process 9 exceptions before 12 PM', detail: 'Auto-pay failures and gateway flags â€” must clear before afternoon batch.', state: 'In Progress', tone: 'warn' },
    { title: 'Approve 3 financial aid applications', detail: 'Families notified of deadline â€” committee review ready.', state: 'Ready', tone: 'warn' },
    { title: 'Review overnight reconciliation discrepancy', detail: 'Bank sync flagged a $2,400 variance in yesterday\'s payout batch.', state: 'In Progress', tone: 'warn' },
  ],
  prioritiesTitle: 'Business office execution queue',

  alerts: [
    { title: '3 auto-pay failures overnight', detail: 'Three family accounts failed scheduled auto-pay â€” cards declined or expired.', tone: 'warn' },
    { title: '2 new chargebacks in dispute workbench', detail: 'Two dispute records require documentation and written response within 5 days.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'accounts-receivable',
      icon: 'AR',
      title: 'Accounts Receivable',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '$148,200 outstanding',
      summary: 'AR balance trending down month-over-month. 7 payment plans behind schedule.',
      kpis: [
        { label: 'Total AR balance', value: '$148,200' },
        { label: 'Collection rate', value: '94.2%' },
        { label: 'Plans behind schedule', value: '7' },
        { label: 'Balances over 90 days', value: '3' },
      ],
      details: [
        '7 payment plans are past their scheduled installment date',
        '3 accounts exceed 90-day aging threshold',
        'AR trending down from $168K in September â€” positive trajectory',
        'Auto-contact outreach queued for 11 delinquent accounts',
      ],
      primaryActionLabel: 'Open AR Dashboard',
      backActionLabel: 'View Invoices',
      primaryActionHref: '/billing-dashboard',
      backActionHref: '/finance/invoices',
      lastUpdated: '8:50 AM',
    },
    {
      key: 'billing',
      icon: 'BI',
      title: 'Billing & Invoices',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '$284,500 collected this month',
      summary: 'March collections on target. Statement batch completed successfully.',
      kpis: [
        { label: 'Collected this month', value: '$284,500' },
        { label: 'Invoices posted', value: '481' },
        { label: 'Invoices outstanding', value: '63' },
        { label: 'Statement batch', value: 'Complete' },
      ],
      details: [
        'Monthly statement batch finalized and distributed',
        '481 invoices posted for March billing cycle',
        '63 outstanding invoices with open balances',
        '$284,500 collected â€” up 8% vs prior March',
      ],
      primaryActionLabel: 'View Invoices',
      backActionLabel: 'Billing Dashboard',
      primaryActionHref: '/finance/invoices',
      backActionHref: '/billing-dashboard',
      lastUpdated: '8:45 AM',
    },
    {
      key: 'payment-plans',
      icon: 'PP',
      title: 'Payment Plans',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '412 active plans â€” 7 delinquent',
      summary: '7 payment plan accounts are behind schedule and require outreach today.',
      kpis: [
        { label: 'Active plans', value: '412' },
        { label: 'Current plans', value: '405' },
        { label: 'Behind schedule', value: '7' },
        { label: 'Auto-pay failures', value: '3' },
      ],
      details: [
        '3 auto-pay card failures from overnight batch â€” need manual follow-up',
        '4 plans delinquent 2+ months â€” escalation review',
        'Payment plan enrollment open through May 15',
        'Modification requests pending: 2 families',
      ],
      primaryActionLabel: 'Review Plans',
      backActionLabel: 'Billing Dashboard',
      primaryActionHref: '/billing',
      backActionHref: '/billing-dashboard',
      lastUpdated: '8:40 AM',
    },
    {
      key: 'financial-aid',
      icon: 'FA',
      title: 'Financial Aid',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '3 applications pending approval',
      summary: 'Committee review ready for 3 applications. 24 total in current cycle.',
      kpis: [
        { label: 'Total applications', value: '24' },
        { label: 'Pending approval', value: '3' },
        { label: 'Approved this cycle', value: '18' },
        { label: 'Aid awarded', value: '$38,400' },
      ],
      details: [
        '3 aid applications awaiting committee approval',
        'Deadline for this cycle: May 9 â€” families notified',
        '18 families approved â€” award letters sent',
        '$38,400 total aid disbursed this academic year',
      ],
      primaryActionLabel: 'Open Financial Aid',
      backActionLabel: 'Review Applications',
      primaryActionHref: '/financial-aid',
      backActionHref: '/financial-aid',
      lastUpdated: '8:30 AM',
    },
    {
      key: 'exceptions',
      icon: 'EX',
      title: 'Exceptions Queue',
      status: 'Critical',
      statusTone: 'warn',
      mainKpi: '9 open exceptions',
      summary: '9 items require specialist review and must clear before the afternoon batch runs.',
      kpis: [
        { label: 'Open exceptions', value: '9' },
        { label: 'Auto-pay failures', value: '3' },
        { label: 'Chargebacks pending', value: '2' },
        { label: 'Manual review items', value: '4' },
      ],
      details: [
        '3 overnight auto-pay failures requiring card update or manual charge',
        '2 chargeback disputes need documentation within 5 days',
        '4 miscellaneous exceptions flagged by gateway',
        'Batch closes at 3 PM â€” all items must clear before then',
      ],
      primaryActionLabel: 'Open Exceptions',
      backActionLabel: 'Dispute Workbench',
      primaryActionHref: '/finance/exceptions',
      backActionHref: '/finance/dispute-workbench',
      lastUpdated: '8:52 AM',
    },
    {
      key: 'reconciliation',
      icon: 'RC',
      title: 'Bank Reconciliation',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '$2,400 variance flagged',
      summary: 'Overnight payout sync returned a $2,400 variance requiring review before close.',
      kpis: [
        { label: 'Reconciliation status', value: 'Variance' },
        { label: 'Flagged discrepancy', value: '$2,400' },
        { label: 'Last successful batch', value: 'Yesterday' },
        { label: 'Payout batches this week', value: '4' },
      ],
      details: [
        'Bank sync flagged $2,400 variance in yesterday\'s batch',
        '4 payout batches processed this week â€” 3 clean',
        'Payout reconciliation report available for review',
        'Discrepancy must be resolved before Friday ledger close',
      ],
      primaryActionLabel: 'Open Reconciliation',
      backActionLabel: 'Payout Reconciliation',
      primaryActionHref: '/finance/bank-reconciliation',
      backActionHref: '/finance/payout-reconciliation',
      lastUpdated: '8:48 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Monthly collections trend',
      title: 'Total collected per month â€” academic year',
      chip: 'Trending up',
      trend: COLLECTIONS_TREND,
    },
    {
      kicker: 'AR aging trend',
      title: 'Total AR balance â€” month over month',
      chip: 'Declining â€” positive',
      trend: AR_AGING_TREND,
    },
  ],

  activityKicker: 'Finance activity',
  activityTitle: 'Recent business office activity',
  activities: [
    'March billing batch completed â€” 481 invoices posted.',
    'Compuwerx payout reconciled â€” $2,400 variance flagged.',
    '3 auto-pay card failures logged from overnight batch.',
    'Financial aid award letters sent to 18 approved families.',
    'Bank sync completed â€” 4 of 4 batches processed.',
  ],

  quickActions: [
    {
      title: 'Open Exceptions',
      eyebrow: 'Quick action',
      description: 'Clear 9 outstanding exceptions before the 3 PM batch run.',
      actionLabel: 'Open Exceptions',
      href: '/finance/exceptions',
      allowedRoles: ['finance'],
    },
    {
      title: 'Review AR',
      eyebrow: 'Quick action',
      description: 'View outstanding balances and delinquent payment plans.',
      actionLabel: 'Open AR Dashboard',
      href: '/billing-dashboard',
      allowedRoles: ['finance'],
    },
    {
      title: 'Process Invoices',
      eyebrow: 'Quick action',
      description: 'Manage open invoice queue for March billing cycle.',
      actionLabel: 'Open Invoices',
      href: '/finance/invoices',
      allowedRoles: ['finance'],
    },
    {
      title: 'Open Financial Aid',
      eyebrow: 'Quick action',
      description: 'Review and approve 3 pending aid applications.',
      actionLabel: 'Open Financial Aid',
      href: '/financial-aid',
      allowedRoles: ['finance'],
    },
  ],

  statusTitle: 'Business office systems',
  statusKicker: 'Financial system health',
  statuses: [
    { label: 'Compuwerx Sync', state: 'Healthy' },
    { label: 'Payment Gateway', state: 'Processing' },
    { label: 'AR System', state: 'Current' },
    { label: 'Bank Connection', state: 'Active' },
  ],
};
