import { BASE_NOTE } from './_baseData.js';

const ACADEMIC_TREND = [
  { month: 'Sep', value: 89 },
  { month: 'Oct', value: 90 },
  { month: 'Nov', value: 91 },
  { month: 'Dec', value: 88 },
  { month: 'Jan', value: 90 },
  { month: 'Feb', value: 92 },
  { month: 'Mar', value: 93 },
];

const FAMILY_ATTENDANCE_TREND = [
  { month: 'Sep', value: 96 },
  { month: 'Oct', value: 97 },
  { month: 'Nov', value: 98 },
  { month: 'Dec', value: 96 },
  { month: 'Jan', value: 97 },
  { month: 'Feb', value: 98 },
  { month: 'Mar', value: 98 },
];

export default {
  key: 'parent',
  activePath: '/parent',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 2,
  user: {
    initials: 'EP',
    name: 'Emily Parker',
    role: 'Parent / Guardian',
  },
  dashboardTitle: 'Parent Dashboard',
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Mrs. Parker!',
  subtitle: 'Heritage Christian Academy',
  note: BASE_NOTE,

  metrics: [
    { label: 'Children Enrolled', value: '2', detail: 'Aiden (8th) and Sophie (5th) — both active.', accent: 'blue' },
    { label: 'Open Assignments', value: '4', detail: '3 due this week across both students.', accent: 'gold' },
    { label: 'Attendance This Week', value: '98%', detail: 'One late arrival noted for Aiden on Monday.', accent: 'emerald' },
    { label: 'Account Balance', value: '$425', detail: 'November billing statement available for review.', accent: 'navy' },
  ],

  priorities: [
    { title: 'Review Sophie\'s missing English assignment', detail: 'Due today — teacher flagged it in the parent portal this morning.', state: 'Due today', tone: 'warn' },
    { title: 'Confirm field trip permission slip for Aiden', detail: 'Science museum trip — consent required by Friday noon.', state: 'Due Friday', tone: 'warn' },
    { title: 'Review November billing statement', detail: 'Statement posted — payment due by the 15th. Payment plan available.', state: 'Due next week', tone: 'warn' },
  ],
  prioritiesTitle: 'Family action queue',

  alerts: [
    { title: 'Aiden: Algebra quiz below 75%', detail: 'Quiz score of 72% posted — teacher recommends review session before next test.', tone: 'warn' },
    { title: 'Billing statement ready', detail: 'November statement is available. Balance of $425 due by the 15th.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'academics',
      icon: 'AC',
      title: 'Academic Progress',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '4 open assignments',
      summary: 'Both students tracking well overall, but Sophie has a missing assignment due today.',
      kpis: [
        { label: 'Aiden — current avg', value: '88.6%' },
        { label: 'Sophie — current avg', value: '93.1%' },
        { label: 'Missing assignments', value: '4' },
        { label: 'Upcoming assessments', value: '3' },
      ],
      details: [
        'Sophie: missing English reflection — due today',
        'Aiden: Algebra quiz result flagged for review',
        'Both students: midterm report cards available',
        '3 assessments scheduled this week across both students',
      ],
      primaryActionLabel: 'View Grades',
      backActionLabel: 'Academic Snapshot',
      primaryActionHref: '/academics/parent-snapshot',
      backActionHref: '/academics/parent-snapshot',
      lastUpdated: '8:51 AM',
    },
    {
      key: 'attendance',
      icon: 'AT',
      title: 'Attendance',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '98% attendance this week',
      summary: 'Both students maintaining strong attendance. One late arrival logged this week.',
      kpis: [
        { label: 'Days present (Aiden)', value: '4 / 5' },
        { label: 'Days present (Sophie)', value: '5 / 5' },
        { label: 'Tardies this month', value: '1' },
        { label: 'Semester attendance rate', value: '97.8%' },
      ],
      details: [
        'Aiden: one late arrival Monday — no action needed',
        'Sophie: perfect attendance this week',
        'Semester rate of 97.8% exceeds school benchmark of 95%',
        'Attendance history available in parent portal',
      ],
      primaryActionLabel: 'View Attendance',
      backActionLabel: 'Full History',
      primaryActionHref: '/parent/attendance',
      backActionHref: '/parent/attendance',
      lastUpdated: '8:45 AM',
    },
    {
      key: 'billing',
      icon: 'BI',
      title: 'Family Billing',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '$425 account balance',
      summary: 'November statement posted. Payment due by the 15th — payment plan available.',
      kpis: [
        { label: 'Current balance', value: '$425.00' },
        { label: 'Payment plan', value: 'Active' },
        { label: 'Last payment', value: '$450 — Oct 28' },
        { label: 'Next due date', value: 'Nov 15' },
      ],
      details: [
        'November tuition and activity fee statement posted',
        'Payment plan is active — $450/month recurring',
        'Last payment of $450 received October 28',
        'Contact business office to adjust payment schedule',
      ],
      primaryActionLabel: 'Review Invoices',
      backActionLabel: 'Pay Balance',
      primaryActionHref: '/finance/invoices',
      backActionHref: '/finance/invoices',
      lastUpdated: '8:31 AM',
    },
    {
      key: 'communications',
      icon: 'CO',
      title: 'School Communications',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '2 unread messages',
      summary: 'Teacher update and principal announcement are unread in your parent inbox.',
      kpis: [
        { label: 'Unread messages', value: '2' },
        { label: 'School announcements', value: '4' },
        { label: 'Teacher messages', value: '1' },
        { label: 'Bulletin reads this week', value: '3' },
      ],
      details: [
        'Mrs. Chen: Sophie\'s English assignment note',
        'Principal Hernandez: End-of-quarter letter',
        'Weekly parent bulletin published this morning',
        '3 upcoming event reminders delivered',
      ],
      primaryActionLabel: 'Open Messages',
      backActionLabel: 'View Announcements',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:18 AM',
    },
    {
      key: 'calendar',
      icon: 'CA',
      title: 'Calendar & Events',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '7 events this week',
      summary: 'Field trip permission and chapel schedule are the active items requiring family action.',
      kpis: [
        { label: 'Events this week', value: '7' },
        { label: 'Permissions pending', value: '1' },
        { label: 'Parent meetings', value: '0' },
        { label: 'Chapel schedule', value: 'Wednesday' },
      ],
      details: [
        'Aiden: Science museum field trip — permission due Friday',
        'Wednesday chapel at 9:00 AM — all students attend',
        'Sophie: band concert next Tuesday at 7:00 PM',
        'No parent-teacher conferences this week',
      ],
      primaryActionLabel: 'View Calendar',
      backActionLabel: 'School Communications',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:10 AM',
    },
    {
      key: 'student-profiles',
      icon: 'ST',
      title: 'Student Profiles',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: 'Both students active',
      summary: 'Aiden and Sophie are both enrolled and active for the current academic year.',
      kpis: [
        { label: 'Aiden — Grade 8', value: '88.6% avg' },
        { label: 'Sophie — Grade 5', value: '93.1% avg' },
        { label: 'Service hours (Aiden)', value: '12 / 20 hrs' },
        { label: 'Service hours (Sophie)', value: 'N/A — Grade 5' },
      ],
      details: [
        'Aiden: on track for service hour requirement completion',
        'Sophie: highest scoring student in 5th grade English',
        'Both students current on health and emergency forms',
        'Enrollment renewal forms available for next year',
      ],
      primaryActionLabel: 'View Student Details',
      backActionLabel: 'Academic Snapshot',
      primaryActionHref: '/academics/parent-snapshot',
      backActionHref: '/academics/parent-snapshot',
      lastUpdated: '8:02 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Academic trend',
      title: 'Combined academic average — both students',
      chip: 'Last 7 months',
      trend: ACADEMIC_TREND,
    },
    {
      kicker: 'Attendance trend',
      title: 'Family attendance rate — semester',
      chip: 'Consistently above 96%',
      trend: FAMILY_ATTENDANCE_TREND,
    },
  ],

  activityKicker: 'Family activity',
  activityTitle: 'Recent family events',
  activities: [
    'Sophie submitted math homework before the 9 PM deadline.',
    'Field trip permission reminder received for Aiden.',
    'Weekly parent bulletin from principal opened.',
    'Aiden\'s Algebra quiz result posted — 72%.',
    'November billing statement available in parent portal.',
  ],

  quickActions: [
    {
      title: 'View Grades',
      eyebrow: 'Quick action',
      description: 'Review academic progress and assignment status for both students.',
      actionLabel: 'View Grades',
      href: '/academics/parent-snapshot',
      allowedRoles: ['parent'],
    },
    {
      title: 'Check Attendance',
      eyebrow: 'Quick action',
      description: 'Review attendance history and any tardiness for both students.',
      actionLabel: 'Check Attendance',
      href: '/parent/attendance',
      allowedRoles: ['parent'],
    },
    {
      title: 'Review Billing',
      eyebrow: 'Quick action',
      description: 'View invoices and manage your family payment schedule.',
      actionLabel: 'Open Billing',
      href: '/finance/invoices',
      allowedRoles: ['parent'],
    },
    {
      title: 'Open Messages',
      eyebrow: 'Quick action',
      description: 'Read teacher and school communications in your parent inbox.',
      actionLabel: 'Open Messages',
      href: '/communications',
      allowedRoles: ['parent'],
    },
  ],

  statusTitle: 'Family portal status',
  statusKicker: 'System health',
  statuses: [
    { label: 'Student Records', state: 'Current' },
    { label: 'Billing Portal', state: 'Online' },
    { label: 'Parent Messaging', state: 'Active' },
    { label: 'Attendance Sync', state: 'Up to date' },
  ],
};
