import { BASE_NOTE } from './_baseData.js';

const ENROLLMENT_TREND = [
  { month: 'Oct', value: 1198 },
  { month: 'Nov', value: 1216 },
  { month: 'Dec', value: 1228 },
  { month: 'Jan', value: 1236 },
  { month: 'Feb', value: 1241 },
  { month: 'Mar', value: 1248 },
];

const ATTENDANCE_TREND = [
  { month: 'Oct', value: 95.1 },
  { month: 'Nov', value: 95.4 },
  { month: 'Dec', value: 95.8 },
  { month: 'Jan', value: 96.0 },
  { month: 'Feb', value: 96.1 },
  { month: 'Mar', value: 96.2 },
];

export default {
  key: 'schoolAdministrator',
  activePath: '/school-admin',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 6,
  user: {
    initials: 'SJ',
    name: 'Sarah James',
    role: 'School Administrator',
  },
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Sarah!',
  subtitle: 'Heritage Christian Academy',
  note: BASE_NOTE,
  metrics: [
    { label: 'Total Students', value: '1,248', detail: 'Enrollment is up 4.1% from last semester.', accent: 'blue' },
    { label: 'Faculty & Staff', value: '156', detail: 'Three new hires completed onboarding this week.', accent: 'navy' },
    { label: 'Attendance Rate', value: '96.2%', detail: 'Steady above benchmark across all divisions.', accent: 'gold' },
    { label: 'Tuition Collected', value: '$2.4M', detail: '94% of semester target collected to date.', accent: 'emerald' },
    { label: 'Open Admissions', value: '42', detail: 'Applications in decision and packet stages.', accent: 'blue' },
    { label: 'Active Alerts', value: '6', detail: 'Cross-department exceptions need review today.', accent: 'gold' },
  ],
  priorities: [
    { title: 'Finalize open admissions decisions', detail: '12 applications pending principal signoff.', state: 'Due by 10:30 AM', tone: 'warn' },
    { title: 'Resolve attendance submission gaps', detail: '5 homerooms still missing first-period sync.', state: 'In progress', tone: 'warn' },
    { title: 'Confirm tuition follow-up plan', detail: 'Finance needs outreach approval for 18 accounts.', state: 'Ready', tone: 'good' },
    { title: 'Approve Friday event staffing', detail: 'Volunteer and chaperone roster awaiting confirmation.', state: 'Ready', tone: 'good' },
  ],
  alerts: [
    { title: 'Incident report escalation', detail: 'Health/Safety flagged a bus-loop incident requiring review.', tone: 'warn' },
    { title: 'SIS sync retries detected', detail: '2 overnight integration retries completed with warnings.', tone: 'warn' },
    { title: 'Family billing exception', detail: 'Aid queue includes 3 accounts waiting counselor note.', tone: 'warn' },
  ],
  commandModules: [
    {
      key: 'admissions',
      icon: 'AD',
      title: 'Admissions / Enrollment',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '42 open applications',
      summary: 'Pipeline remains strong with tours and packet processing active.',
      kpis: [
        { label: 'New inquiries', value: '74' },
        { label: 'Applications submitted', value: '42' },
        { label: 'Tours scheduled', value: '19' },
        { label: 'Packets pending', value: '12' },
      ],
      details: ['12 files pending final review', '19 family tours in next 7 days', '8 follow-up calls required'],
      primaryActionLabel: 'Review applications',
      backActionLabel: 'Send enrollment packet',
      lastUpdated: '8:42 AM',
    },
    {
      key: 'attendance',
      icon: 'AT',
      title: 'Attendance',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '96.2% present today',
      summary: 'Attendance is healthy but submissions are incomplete in select homerooms.',
      kpis: [
        { label: "Today's attendance", value: '96.2%' },
        { label: 'Students absent', value: '47' },
        { label: 'Late arrivals', value: '18' },
        { label: 'Missing submissions', value: '5' },
      ],
      details: ['5 teachers missing first period sync', '18 late arrivals logged before 9:00 AM', 'Family notification batch ready'],
      primaryActionLabel: 'Open attendance review',
      backActionLabel: 'Notify families',
      lastUpdated: '8:50 AM',
    },
    {
      key: 'academics',
      icon: 'AC',
      title: 'Academics / Gradebook',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '18 students at risk',
      summary: 'Gradebook completion is improving but intervention cases require action.',
      kpis: [
        { label: 'Classes missing grades', value: '9' },
        { label: 'At-risk students', value: '18' },
        { label: 'Assignment completion', value: '92%' },
        { label: 'Report cards ready', value: '84%' },
      ],
      details: ['9 courses need final grade sync', 'Intervention plans pending for 6 students', 'Report cards ready by Thursday target'],
      primaryActionLabel: 'Review gradebook',
      backActionLabel: 'Generate progress report',
      lastUpdated: '8:36 AM',
    },
    {
      key: 'finance',
      icon: 'FI',
      title: 'Finance / Billing',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '$2.4M collected',
      summary: 'Collections are on target with manageable outstanding balances.',
      kpis: [
        { label: 'Tuition collected', value: '$2.4M' },
        { label: 'Outstanding balances', value: '$184K' },
        { label: 'Payment plans active', value: '138' },
        { label: 'Aid pending', value: '24' },
      ],
      details: ['138 plans active across all divisions', '24 aid applications awaiting committee', 'Batch posting completed this morning'],
      primaryActionLabel: 'Review billing',
      backActionLabel: 'Open financial aid queue',
      lastUpdated: '8:31 AM',
    },
    {
      key: 'communications',
      icon: 'CO',
      title: 'Communications',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '27 messages pending',
      summary: 'Family and staff communications are active with scheduled announcements queued.',
      kpis: [
        { label: 'Messages pending', value: '27' },
        { label: 'Announcements scheduled', value: '5' },
        { label: 'Family replies needed', value: '14' },
        { label: 'Unread staff messages', value: '9' },
      ],
      details: ['Weekly bulletin draft ready', '14 family responses pending follow-up', 'Staff channel digest scheduled'],
      primaryActionLabel: 'Send announcement',
      backActionLabel: 'Open message center',
      lastUpdated: '8:27 AM',
    },
    {
      key: 'hr',
      icon: 'HR',
      title: 'Staff / HR',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '4 substitutes needed',
      summary: 'Coverage and credential tracking need review before midday.',
      kpis: [
        { label: 'Staff present', value: '147' },
        { label: 'Substitutes needed', value: '4' },
        { label: 'Certifications expiring', value: '7' },
        { label: 'Open HR tasks', value: '11' },
      ],
      details: ['4 substitute assignments unresolved', '7 certifications expire this month', '11 HR checklist tasks remain'],
      primaryActionLabel: 'Open staff roster',
      backActionLabel: 'Manage HR checklist',
      lastUpdated: '8:21 AM',
    },
    {
      key: 'student-life',
      icon: 'SL',
      title: 'Student Life / Discipline',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '13 behavior follow-ups',
      summary: 'Counseling and discipline queues need leadership review.',
      kpis: [
        { label: 'Discipline follow-ups', value: '13' },
        { label: 'Counseling referrals', value: '9' },
        { label: 'Service hours pending', value: '32' },
        { label: 'Behavior alerts', value: '6' },
      ],
      details: ['6 high-priority alerts require same-day response', 'Counseling referrals queued for advisor review', 'Service hour verification backlog increased'],
      primaryActionLabel: 'Review student life queue',
      backActionLabel: 'Open discipline cases',
      lastUpdated: '8:18 AM',
    },
    {
      key: 'health-safety',
      icon: 'HS',
      title: 'Health / Safety',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '7 incident reports',
      summary: 'Health office load is manageable but incident reviews are pending.',
      kpis: [
        { label: 'Nurse visits today', value: '24' },
        { label: 'Medical forms missing', value: '16' },
        { label: 'Incident reports', value: '7' },
        { label: 'Emergency contacts incomplete', value: '9' },
      ],
      details: ['7 incidents need administrator signoff', '16 families missing medical updates', 'Emergency contact verification in progress'],
      primaryActionLabel: 'Open health office',
      backActionLabel: 'Review incidents',
      lastUpdated: '8:12 AM',
    },
    {
      key: 'calendar-events',
      icon: 'EV',
      title: 'Calendar / Events',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '11 events this week',
      summary: 'Event cadence is healthy with approvals and logistics underway.',
      kpis: [
        { label: 'Events this week', value: '11' },
        { label: 'Field trips pending', value: '3' },
        { label: 'Rooms booked', value: '28' },
        { label: 'Volunteer needs', value: '14' },
      ],
      details: ['3 field trip approvals awaiting final signoff', 'Volunteer roster still needs 14 slots', 'Room booking conflicts resolved for Friday'],
      primaryActionLabel: 'Create event',
      backActionLabel: 'Approve field trip',
      lastUpdated: '8:09 AM',
    },
    {
      key: 'system-it',
      icon: 'IT',
      title: 'System / IT / Integrations',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '3 failed syncs',
      summary: 'Core platform is online but integration retries need tracking.',
      kpis: [
        { label: 'System status', value: 'Operational' },
        { label: 'Failed syncs', value: '3' },
        { label: 'Open support tickets', value: '8' },
        { label: 'Backup status', value: 'Complete' },
      ],
      details: ['3 SIS retries from overnight import', '8 tickets in school support queue', 'Backup completed at 2:14 AM'],
      primaryActionLabel: 'Open system integrity',
      backActionLabel: 'Review sync errors',
      lastUpdated: '8:04 AM',
    },
  ],
  trendPanels: [
    {
      kicker: 'Enrollment trend',
      title: 'Enrollment / attendance trend',
      chip: 'Updated this morning',
      trend: ENROLLMENT_TREND,
    },
    {
      kicker: 'Attendance trend',
      title: 'Attendance stability across divisions',
      chip: 'Last 6 months',
      trend: ATTENDANCE_TREND,
    },
  ],
  activityKicker: 'Activity feed',
  activityTitle: 'Recent activity',
  activities: [
    'Admissions team completed principal review packets for 8 applicants.',
    'Attendance office issued family outreach for unresolved absences.',
    'Finance posted overnight payment batch and reconciliation report.',
    'Health office escalated 2 incident logs for administrator approval.',
    'IT cleared device sync latency affecting gradebook uploads.',
  ],
  quickActions: [
    {
      title: 'Add student',
      eyebrow: 'Quick action',
      description: 'Create a new student profile and initialize enrollment records.',
      actionLabel: 'Add student',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Add staff',
      eyebrow: 'Quick action',
      description: 'Start onboarding workflow for new teacher or support staff.',
      actionLabel: 'Add staff',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Review admissions',
      eyebrow: 'Quick action',
      description: 'Open pending admissions queue and decision checklist.',
      actionLabel: 'Review admissions',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Send announcement',
      eyebrow: 'Quick action',
      description: 'Draft and publish a schoolwide communication update.',
      actionLabel: 'Send announcement',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Open attendance',
      eyebrow: 'Quick action',
      description: 'Review attendance exceptions and dispatch follow-ups.',
      actionLabel: 'Open attendance',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Open billing',
      eyebrow: 'Quick action',
      description: 'Jump to billing exceptions and payment processing queue.',
      actionLabel: 'Open billing',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'Generate report',
      eyebrow: 'Quick action',
      description: 'Create executive daily operations and readiness report.',
      actionLabel: 'Generate report',
      allowedRoles: ['schoolAdministrator'],
    },
    {
      title: 'View calendar',
      eyebrow: 'Quick action',
      description: 'Open calendar control center for events and approvals.',
      actionLabel: 'View calendar',
      allowedRoles: ['schoolAdministrator'],
    },
  ],
  statusKicker: 'Operational status widgets',
  statusTitle: 'Whole-school system health',
  statuses: [
    { label: 'Admissions workflow', state: 'Watch' },
    { label: 'Attendance processing', state: 'Watch' },
    { label: 'Billing operations', state: 'Stable' },
    { label: 'Communications engine', state: 'Ready' },
  ],
  operationsTitle: 'Department readiness table',
  operations: [
    { area: 'Admissions', owner: 'Director of Admissions', status: 'Watch - packet queue high', updated: '8:42 AM' },
    { area: 'Attendance', owner: 'Student Life Office', status: 'Watch - 5 submissions missing', updated: '8:50 AM' },
    { area: 'Academics', owner: 'Academic Dean', status: 'Stable - intervention plans active', updated: '8:36 AM' },
    { area: 'Finance', owner: 'Business Office', status: 'Stable - batch posted', updated: '8:31 AM' },
    { area: 'Communications', owner: 'Front Office', status: 'Ready - bulletin queued', updated: '8:27 AM' },
    { area: 'Staff / HR', owner: 'HR Coordinator', status: 'Watch - substitute coverage', updated: '8:21 AM' },
    { area: 'Student Life', owner: 'Dean of Students', status: 'Watch - behavior follow-ups', updated: '8:18 AM' },
    { area: 'Health / Safety', owner: 'Health Office', status: 'Watch - incident signoff', updated: '8:12 AM' },
    { area: 'Calendar / Events', owner: 'Events Office', status: 'Ready - approvals in queue', updated: '8:09 AM' },
    { area: 'System / IT', owner: 'Technology Team', status: 'Watch - 3 failed syncs', updated: '8:04 AM' },
  ],
};
