import { LIVE_NOTE } from './_baseData.js';

const CHAPEL_TREND = [
  { month: 'Sep', value: 84 }, { month: 'Oct', value: 86 }, { month: 'Nov', value: 87 },
  { month: 'Dec', value: 88 }, { month: 'Jan', value: 88 }, { month: 'Feb', value: 89 }, { month: 'Mar', value: 89 },
];
const SERVICE_TREND = [
  { month: 'Sep', value: 410 }, { month: 'Oct', value: 580 }, { month: 'Nov', value: 760 },
  { month: 'Dec', value: 1180 }, { month: 'Jan', value: 1620 }, { month: 'Feb', value: 1980 }, { month: 'Mar', value: 2340 },
];
const FORMATION_TREND = [
  { month: 'Sep', value: 62 }, { month: 'Oct', value: 68 }, { month: 'Nov', value: 73 },
  { month: 'Dec', value: 75 }, { month: 'Jan', value: 81 }, { month: 'Feb', value: 84 }, { month: 'Mar', value: 88 },
];

export default {
  key: 'spiritualLife',
  activePath: '/spiritual-life',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 8,
  user: { initials: 'CH', name: 'Chaplain', role: 'Spiritual Life & Biblical Formation' },
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Chaplain!',
  subtitle: 'Spiritual Life & Biblical Formation Command Center',
  note: LIVE_NOTE,
  dataSource: 'live_api',
  apiEndpoint: '/api/v1/dashboards/spiritualLife/summary/',
  liveDataKey: 'spiritualLife',

  metrics: [
    { label: 'Chapel Attendance', value: '89%', detail: 'Worship and formation rhythm above 4-week average.', accent: 'emerald' },
    { label: 'Devotions Published', value: '5/5', detail: 'Daily grade-level devotion pipeline is on schedule.', accent: 'blue' },
    { label: 'Open Spiritual Care', value: '6', detail: 'Active pastoral care cases require monitored follow-up.', accent: 'gold' },
    { label: 'Portrait Coverage', value: '88%', detail: 'Graduate outcomes represented across formation artifacts.', accent: 'emerald' },
  ],

  priorities: [
    { title: 'Approve Friday family devotion', detail: 'Review grade-band prompts, staff connection, and parent discussion guide.', state: 'Today', tone: 'warn' },
    { title: 'Complete pastor luncheon follow-up', detail: 'Send thank-you notes and schedule two campus tours from RSVP list.', state: 'This week', tone: 'warn' },
    { title: 'Finalize student leadership summit', detail: 'Confirm worship team, peer mentors, service captains, and commissioning plan.', state: 'This week', tone: 'warn' },
    { title: 'Map chapel series to Portrait outcomes', detail: 'Attach Biblical worldview priorities and evidence artifacts before board report.', state: 'Monthly', tone: 'good' },
  ],
  prioritiesTitle: 'Mission formation priorities',

  alerts: [
    { title: '6 open spiritual care cases', detail: 'Pastoral care queue needs next-step owner review.', tone: 'warn' },
    { title: 'Speaker vetting pending', detail: 'Two guest speakers need statement-of-faith and topic review before chapel confirmation.', tone: 'warn' },
    { title: 'Christian Education Sunday materials due', detail: 'Bulletin insert and student testimony packet need final approval.', tone: 'warn' },
  ],

  commandModules: [
    { key: 'formation-rhythm', icon: 'FR', title: "Today's Formation Rhythm", status: 'Stable', statusTone: 'good',
      mainKpi: 'Core rhythm active', summary: 'Devotions, chapel prep, prayer focus, and staff formation are visible for today.',
      kpis: [{ label: 'Devotions', value: '5/5' }, { label: 'Prayer focus', value: 'Set' }, { label: 'Staff note', value: 'Published' }, { label: 'Small groups', value: '8' }],
      details: ['Daily devotions scheduled by grade band', 'Prayer focus posted to staff and student dashboards', 'Small-group guide tied to chapel theme', 'Family prompt prepared for Friday'],
      primaryActionLabel: 'Open Rhythm Board', backActionLabel: 'Formation Calendar',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '8:45 AM' },
    { key: 'devotions', icon: 'DV', title: 'Daily Devotion Publishing', status: 'Stable', statusTone: 'good',
      mainKpi: '5 grade bands ready', summary: 'Daily devotion plan supports students, families, and staff with review-gated publishing.',
      kpis: [{ label: 'Published', value: '5' }, { label: 'In review', value: '2' }, { label: 'Family prompts', value: 'Ready' }, { label: 'Assisted drafts', value: 'Review gated' }],
      details: ['Lower elementary, upper elementary, middle school, high school, and staff devotion tracks active', 'Family discussion guide requires final review', 'Assisted draft content requires human approval', 'Archive tags include scripture, worldview priority, and Portrait domain'],
      primaryActionLabel: 'Devotion Library', backActionLabel: 'Publishing Queue',
      primaryActionHref: '/spiritual-life', backActionHref: '/communications', lastUpdated: '8:40 AM' },
    { key: 'chapel', icon: 'CH', title: 'Chapel & Worship', status: 'Stable', statusTone: 'good',
      mainKpi: '89% attendance', summary: 'Chapel attendance above 4-week average with follow-up formation content planned.',
      kpis: [{ label: 'Attendance %', value: '89%' }, { label: 'Speakers booked', value: '6' }, { label: 'Student roles', value: '12' }, { label: 'Follow-up guide', value: 'Ready' }],
      details: ['Spring speaker series confirmed through May', 'Worship team rehearsal Tuesday', 'Student prayer and scripture roles assigned', 'Chapel follow-up devotion connected to small-group guide'],
      primaryActionLabel: 'Open Chapel Console', backActionLabel: 'Speaker Schedule',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '8:30 AM' },
    { key: 'care', icon: 'SC', title: 'Spiritual Counseling & Care', status: 'Watch', statusTone: 'warn',
      mainKpi: '6 open cases', summary: 'Pastoral care queue separates spiritual support from licensed counseling referrals.',
      kpis: [{ label: 'Open cases', value: '6' }, { label: 'Urgent', value: '1' }, { label: 'Counselor handoffs', value: '2' }, { label: 'Aged follow-ups', value: '3' }],
      details: ['Prayer requests can become pastoral care cases', 'Referral boundary flags are tracked', 'Sensitive pastoral notes remain restricted', 'Parent notification and administrator review flags are visible'],
      primaryActionLabel: 'Open Care Queue', backActionLabel: 'Counseling Coord.',
      primaryActionHref: '/spiritual-life', backActionHref: '/counseling', lastUpdated: '8:20 AM' },
    { key: 'worldview', icon: 'BW', title: 'Biblical Worldview Priorities', status: 'Stable', statusTone: 'good',
      mainKpi: '7 active priorities', summary: 'Chapel, devotions, service, and family resources are mapped to worldview themes.',
      kpis: [{ label: 'Priorities', value: '7' }, { label: 'Mapped artifacts', value: '42' }, { label: 'Coverage', value: '84%' }, { label: 'Gaps', value: '2' }],
      details: ['Scripture authority and imago Dei themes appear in March sequence', 'Service projects mapped to servant leadership', 'Family resources mapped to home discipleship', 'Coverage gaps need grade 5 and grade 8 reinforcement'],
      primaryActionLabel: 'Open Worldview Map', backActionLabel: 'Coverage Report',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '8:10 AM' },
    { key: 'portrait', icon: 'PG', title: 'Portrait of the Graduate Alignment', status: 'Stable', statusTone: 'good',
      mainKpi: '88% coverage', summary: 'Formation artifacts are connected to graduate outcomes and board evidence.',
      kpis: [{ label: 'Domains active', value: '8' }, { label: 'Evidence items', value: '56' }, { label: 'Board-ready', value: 'Yes' }, { label: 'Monthly gaps', value: '1' }],
      details: ['Christ-centered identity, wisdom, service, and calling domains are strongly represented', 'Senior commissioning adds evidence for vocation/calling', 'Board report can exclude sensitive care data', 'One compassion/community artifact needs upload'],
      primaryActionLabel: 'Open Portrait Alignment', backActionLabel: 'Mission Evidence',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '8:05 AM' },
    { key: 'church-relations', icon: 'CR', title: 'Church & Pastor Relations', status: 'Watch', statusTone: 'warn',
      mainKpi: '18 active partners', summary: 'Church partner directory tracks pastors, youth pastors, campus tours, and follow-ups.',
      kpis: [{ label: 'Church partners', value: '18' }, { label: 'Pastor contacts', value: '42' }, { label: 'Tours pending', value: '2' }, { label: 'Follow-ups', value: '5' }],
      details: ['Pastor luncheon follow-up due Friday', 'Two youth pastors requested campus tours', 'Three churches invited to chapel speaker rotation', 'Partner notes connect church outreach to family support'],
      primaryActionLabel: 'Open Church Partners', backActionLabel: 'Pastor Follow-Up',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '7:55 AM' },
    { key: 'christian-education-sunday', icon: 'ES', title: 'Christian Education Sundays', status: 'Watch', statusTone: 'warn',
      mainKpi: '6 churches scheduled', summary: 'Church-facing campaign promotes Christian education through speakers and materials.',
      kpis: [{ label: 'Churches', value: '6' }, { label: 'Bulletin insert', value: 'Draft' }, { label: 'Student testimony', value: 'Review' }, { label: 'Thank-you queue', value: '0' }],
      details: ['Campaign theme selected', 'School story packet in review', 'Student testimony requires parent permission', 'Admissions follow-up list will route to enrollment team'],
      primaryActionLabel: 'Open Campaign', backActionLabel: 'Materials Checklist',
      primaryActionHref: '/spiritual-life', backActionHref: '/communications', lastUpdated: '7:50 AM' },
    { key: 'student-leadership', icon: 'SL', title: 'Student Spiritual Leadership', status: 'Stable', statusTone: 'good',
      mainKpi: '34 active leaders', summary: 'Student leaders are tracked across chapel, worship, peer mentoring, service, and prayer roles.',
      kpis: [{ label: 'Active leaders', value: '34' }, { label: 'Training pending', value: '8' }, { label: 'Commissioning', value: 'May' }, { label: 'Mentors', value: '12' }],
      details: ['Worship team, tech team, scripture readers, and peer mentors are active', 'Leadership summit roster is ready', 'Parent permission needed for two testimony speakers', 'Service captains assigned for outreach week'],
      primaryActionLabel: 'Open Leadership Pipeline', backActionLabel: 'Leadership Events',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '7:45 AM' },
    { key: 'calling-pathways', icon: 'CP', title: 'Christian College & Calling Pathways', status: 'Stable', statusTone: 'good',
      mainKpi: 'College day planned', summary: 'Calling pathway events connect formation to Christian college, missions, ministry, and vocation.',
      kpis: [{ label: 'Partners', value: '9' }, { label: 'Student interests', value: '47' }, { label: 'Parent info', value: 'Ready' }, { label: 'Alumni panel', value: 'Scheduled' }],
      details: ['Christian College Info Day confirmed', 'Missions gap-year partner invited', 'Senior Calling Week linked to commissioning', 'Parent follow-up packet is ready'],
      primaryActionLabel: 'Open Calling Pathways', backActionLabel: 'College Day Plan',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '7:40 AM' },
    { key: 'family-staff', icon: 'FS', title: 'Family & Staff Formation', status: 'Stable', statusTone: 'good',
      mainKpi: 'Resources on schedule', summary: 'Family discipleship and staff formation resources reinforce the same worldview priorities.',
      kpis: [{ label: 'Family guides', value: '3' }, { label: 'Staff devotions', value: '5' }, { label: 'Parent night', value: 'Planned' }, { label: 'Worldview PD', value: '82%' }],
      details: ['Friday family guide reinforces chapel theme', 'Staff devotion schedule is current', 'Parent worldview night planned with church partner', 'New teacher formation onboarding remains active'],
      primaryActionLabel: 'Open Formation Resources', backActionLabel: 'Staff Formation',
      primaryActionHref: '/spiritual-life', backActionHref: '/communications', lastUpdated: '7:35 AM' },
    { key: 'evidence', icon: 'EV', title: 'Formation Evidence & Reports', status: 'Stable', statusTone: 'good',
      mainKpi: 'Board report ready', summary: 'Mission-health evidence rolls chapel, devotions, Portrait, worldview, service, and outreach into reports.',
      kpis: [{ label: 'Evidence items', value: '96' }, { label: 'Exports ready', value: '3' }, { label: 'Sensitive excluded', value: 'Yes' }, { label: 'Accreditation', value: 'Ready' }],
      details: ['Board mission-health report excludes pastoral note details', 'Accreditation evidence includes chapel, devotions, service, and worldview artifacts', 'Church engagement report includes pastor relations and Christian Education Sundays', 'Speaker vetting report available'],
      primaryActionLabel: 'Open Evidence Center', backActionLabel: 'Board Report',
      primaryActionHref: '/spiritual-life', backActionHref: '/spiritual-life', lastUpdated: '7:30 AM' },
  ],

  trendPanels: [
    { kicker: 'Chapel attendance trend', title: 'Chapel attendance % by month', chip: 'Above target', trend: CHAPEL_TREND },
    { kicker: 'Service hours trend', title: 'Cumulative service hours YTD', chip: '+112 this week', trend: SERVICE_TREND },
    { kicker: 'Formation coverage trend', title: 'Portrait and worldview evidence coverage', chip: 'Improving', trend: FORMATION_TREND },
  ],

  activityKicker: 'Spiritual life activity',
  activityTitle: 'Recent formation events',
  activities: [
    'Daily grade-level devotions delivered and archived by scripture and worldview priority.',
    'Pastor luncheon follow-up created two campus tour tasks.',
    'Christian Education Sunday packet moved to final review.',
    'Student leadership summit roster confirmed for chapel, worship, peer mentor, and service roles.',
    'Christian College Info Day parent packet drafted for review.',
    'Board mission-health report refreshed with Portrait of the Graduate evidence.',
  ],

  quickActions: [
    { title: 'Devotion Publishing', eyebrow: 'Quick action', description: 'Review and publish grade-level, staff, and family devotions.', actionLabel: 'Open Devotions', href: '/spiritual-life', allowedRoles: ['spiritualLife'] },
    { title: 'Spiritual Care', eyebrow: 'Quick action', description: 'Review prayer requests, care cases, sensitive follow-ups, and referral boundaries.', actionLabel: 'Open Care Queue', href: '/spiritual-life', allowedRoles: ['spiritualLife'] },
    { title: 'Church Partners', eyebrow: 'Quick action', description: 'Manage pastor contacts, pastor luncheons, church tours, and Christian Education Sundays.', actionLabel: 'Open Church Relations', href: '/spiritual-life', allowedRoles: ['spiritualLife'] },
    { title: 'Student Leaders', eyebrow: 'Quick action', description: 'Manage worship team, chapel team, peer mentors, service captains, and leadership events.', actionLabel: 'Open Student Leaders', href: '/spiritual-life', allowedRoles: ['spiritualLife'] },
    { title: 'Mission Evidence', eyebrow: 'Quick action', description: 'Prepare board and accreditation evidence without exposing sensitive pastoral data.', actionLabel: 'Open Evidence Center', href: '/spiritual-life', allowedRoles: ['spiritualLife'] },
  ],

  statusTitle: 'Spiritual Life & Biblical Formation workspace status',
  statusKicker: 'System health',
  statuses: [
    { label: 'Chapel Schedule', state: 'Confirmed' },
    { label: 'Devotion Pipeline', state: 'Review gated' },
    { label: 'Spiritual Care Boundary', state: 'Configured' },
    { label: 'Church Partner CRM', state: 'Active' },
    { label: 'Portrait Alignment', state: 'Mapped' },
    { label: 'Worldview Priorities', state: 'Active' },
    { label: 'Formation Evidence', state: 'Board-ready' },
  ],
};
