import { LIVE_NOTE } from './_baseData.js';

const ACADEMIC_AVG_TREND = [
  { month: 'Sep', value: 88 },
  { month: 'Oct', value: 89 },
  { month: 'Nov', value: 90 },
  { month: 'Dec', value: 88 },
  { month: 'Jan', value: 91 },
  { month: 'Feb', value: 91 },
  { month: 'Mar', value: 91 },
];

const ASSIGNMENT_COMPLETION_TREND = [
  { month: 'Sep', value: 92 },
  { month: 'Oct', value: 94 },
  { month: 'Nov', value: 91 },
  { month: 'Dec', value: 93 },
  { month: 'Jan', value: 95 },
  { month: 'Feb', value: 96 },
  { month: 'Mar', value: 95 },
];

export default {
  key: 'student',
  activePath: '/student',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 2,
  user: {
    initials: 'AM',
    name: 'Alex Martinez',
    role: 'Student â€” Grade 10',
  },
  dashboardTitle: 'Student Dashboard',
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Alex!',
  subtitle: 'Heritage Christian Academy',
  note: LIVE_NOTE,
  dataSource: 'live_api',
  apiEndpoint: '/api/v1/dashboards/student/summary/',
  liveDataKey: 'student',

  metrics: [
    { label: 'Current Average', value: '91.2%', detail: 'Up 1.2 points since last month.', accent: 'blue' },
    { label: 'Missing Work', value: '1', detail: 'History reflection due tonight at 11:59 PM.', accent: 'gold' },
    { label: 'Service Hours', value: '14 / 20', detail: '6 hours remaining to meet the annual requirement.', accent: 'navy' },
    { label: 'Attendance Rate', value: '96%', detail: 'Two absences this semester â€” both excused.', accent: 'emerald' },
  ],

  priorities: [
    { title: 'History reflection due tonight', detail: 'Submit to class assignment portal by 11:59 PM â€” no extensions available.', state: 'Due today', tone: 'warn' },
    { title: 'Complete math practice set', detail: 'Units 4â€“6 practice problems assigned for tomorrow\'s review.', state: 'Due tomorrow', tone: 'warn' },
    { title: 'Schedule service hours verification', detail: 'Book a 10-minute meeting with Dr. Reyes to confirm your current hours count.', state: 'Ready', tone: 'good' },
  ],
  prioritiesTitle: 'Today\'s student agenda',

  alerts: [
    { title: 'Biology quiz result posted â€” 84%', detail: 'Quiz returned with teacher feedback. Review annotations before the unit test on Friday.', tone: 'good' },
    { title: 'Advisory attendance note from Mr. Chen', detail: 'Please see the note posted to your advisory profile regarding last Monday\'s absence.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'assignments',
      icon: 'AW',
      title: 'Assignments',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '1 assignment due today',
      summary: 'History reflection is due tonight. Math practice set due tomorrow.',
      kpis: [
        { label: 'Due today', value: '1' },
        { label: 'Due this week', value: '4' },
        { label: 'Missing', value: '1' },
        { label: 'Completed this month', value: '18' },
      ],
      details: [
        'History reflection: due 11:59 PM tonight',
        'Math practice set (Units 4â€“6): due tomorrow',
        'English narrative draft: due Thursday',
        'Bio lab worksheet: due Friday before class',
      ],
      primaryActionLabel: 'Open Assignments',
      backActionLabel: 'View Graded Work',
      primaryActionHref: '/academics/student-work',
      backActionHref: '/academics/student-work',
      lastUpdated: '8:40 AM',
    },
    {
      key: 'grades',
      icon: 'GR',
      title: 'Grades & GPA',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '91.2% â€” 3.5 GPA',
      summary: 'Strong semester performance. Biology is the lowest course â€” focus there for finals.',
      kpis: [
        { label: 'Current average', value: '91.2%' },
        { label: 'Estimated GPA', value: '3.5' },
        { label: 'Highest class', value: 'English â€” 97%' },
        { label: 'Lowest class', value: 'Biology â€” 84%' },
      ],
      details: [
        'English: 97% â€” above semester benchmark',
        'History: 93% â€” strong performance',
        'Math: 91% â€” on target for semester goal',
        'Biology: 84% â€” review quiz feedback before unit test',
      ],
      primaryActionLabel: 'Open Gradebook',
      backActionLabel: 'View Transcript',
      primaryActionHref: '/gradebook',
      backActionHref: '/transcript',
      lastUpdated: '8:32 AM',
    },
    {
      key: 'attendance',
      icon: 'AT',
      title: 'Attendance',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '96% attendance rate',
      summary: 'Two excused absences this semester. Advisory note requires acknowledgment.',
      kpis: [
        { label: 'Attendance rate', value: '96%' },
        { label: 'Excused absences', value: '2' },
        { label: 'Unexcused absences', value: '0' },
        { label: 'Late arrivals', value: '1' },
      ],
      details: [
        'Advisory attendance note posted from Mr. Chen',
        '2 excused absences â€” both fully documented',
        'Rate of 96% exceeds required school minimum of 93%',
        'Attendance history available in student profile',
      ],
      primaryActionLabel: 'View Attendance',
      backActionLabel: 'Full History',
      primaryActionHref: '/student-life',
      backActionHref: '/student-life',
      lastUpdated: '8:22 AM',
    },
    {
      key: 'schedule',
      icon: 'SC',
      title: 'My Schedule',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '6 periods today',
      summary: 'Full schedule active. Lunch period at 12:20 PM. No schedule changes today.',
      kpis: [
        { label: 'Class periods', value: '6' },
        { label: 'Study hall', value: 'Period 5' },
        { label: 'Lunch', value: '12:20 PM' },
        { label: 'Dismissal', value: '3:05 PM' },
      ],
      details: [
        'Period 1: English 10 â€” Room 214, Mr. Chen',
        'Period 2: Biology â€” Room 108, Ms. Davis',
        'Period 3: History â€” Room 201, Mr. Wang',
        'Period 4: Math â€” Room 115, Mrs. Lopez',
        'Period 5: Study Hall â€” Library',
        'Period 6: P.E. â€” Gymnasium',
      ],
      primaryActionLabel: 'View Full Schedule',
      backActionLabel: 'Course Details',
      primaryActionHref: '/classrooms',
      backActionHref: '/classrooms',
      lastUpdated: '7:58 AM',
    },
    {
      key: 'service-hours',
      icon: 'SH',
      title: 'Service Hours',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '14 of 20 hours completed',
      summary: '6 hours remaining. Deadline is May 30. Schedule verification meeting with Dr. Reyes.',
      kpis: [
        { label: 'Hours completed', value: '14' },
        { label: 'Hours remaining', value: '6' },
        { label: 'Deadline', value: 'May 30' },
        { label: 'Verification status', value: 'Pending' },
      ],
      details: [
        '6 hours still needed to meet annual requirement',
        'Dr. Reyes must verify and sign off by May 30',
        'Upcoming opportunity: food pantry volunteer â€” May 11',
        'Second opportunity: campus cleanup day â€” May 18',
      ],
      primaryActionLabel: 'Log Service Hours',
      backActionLabel: 'View History',
      primaryActionHref: '/my-service-hours',
      backActionHref: '/my-service-hours',
      lastUpdated: '8:00 AM',
    },
    {
      key: 'communications',
      icon: 'CO',
      title: 'School Communications',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '1 advisory note unread',
      summary: 'Advisory note from Mr. Chen awaiting your acknowledgment.',
      kpis: [
        { label: 'Unread messages', value: '1' },
        { label: 'School announcements', value: '3' },
        { label: 'Teacher messages', value: '1' },
        { label: 'School bulletin', value: 'Posted today' },
      ],
      details: [
        'Advisory note from Mr. Chen â€” attendance record',
        'Student life announcement: spirit week May 12â€“16',
        'Principal newsletter posted this morning',
        'Reminder: chapel Wednesday 9:00 AM, all students',
      ],
      primaryActionLabel: 'Open Communications',
      backActionLabel: 'School Announcements',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:09 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Academic average trend',
      title: 'Grade average across all courses â€” by month',
      chip: 'Trending upward',
      trend: ACADEMIC_AVG_TREND,
    },
    {
      kicker: 'Assignment completion',
      title: 'Assignments submitted on time â€” semester',
      chip: 'Consistent above 91%',
      trend: ASSIGNMENT_COMPLETION_TREND,
    },
  ],

  activityKicker: 'Recent activity',
  activityTitle: 'Your recent school activity',
  activities: [
    'Biology quiz score of 84% posted â€” feedback attached.',
    'History reflection assignment due tonight â€” not yet submitted.',
    'Math practice set (Units 4â€“6) posted to portal.',
    'Advisory attendance note from Mr. Chen posted to profile.',
    'Weekly school bulletin published this morning.',
  ],

  quickActions: [
    {
      title: 'Open Assignments',
      eyebrow: 'Quick action',
      description: 'Review and submit outstanding work for your classes.',
      actionLabel: 'Open Assignments',
      href: '/academics/student-work',
      allowedRoles: ['student'],
    },
    {
      title: 'View Gradebook',
      eyebrow: 'Quick action',
      description: 'Check grades and feedback across all enrolled courses.',
      actionLabel: 'View Gradebook',
      href: '/gradebook',
      allowedRoles: ['student'],
    },
    {
      title: 'Check Attendance',
      eyebrow: 'Quick action',
      description: 'View your attendance record and any outstanding notes.',
      actionLabel: 'Check Attendance',
      href: '/student-life',
      allowedRoles: ['student'],
    },
    {
      title: 'Log Service Hours',
      eyebrow: 'Quick action',
      description: 'Submit completed community service hours for verification.',
      actionLabel: 'Log Hours',
      href: '/service-hours',
      allowedRoles: ['student'],
    },
  ],

  statusTitle: 'Student portal status',
  statusKicker: 'System health',
  statuses: [
    { label: 'Gradebook Sync', state: 'Current' },
    { label: 'Attendance System', state: 'Recorded' },
    { label: 'Assignment Portal', state: 'Open' },
    { label: 'Service Hours Tracker', state: 'Active' },
  ],
};
