import { BASE_NOTE } from './_baseData.js';

const GRADE_COMPLETION_TREND = [
  { month: 'Sep', value: 84 },
  { month: 'Oct', value: 87 },
  { month: 'Nov', value: 89 },
  { month: 'Dec', value: 91 },
  { month: 'Jan', value: 90 },
  { month: 'Feb', value: 93 },
  { month: 'Mar', value: 94 },
];

const CLASS_ATTENDANCE_TREND = [
  { month: 'Sep', value: 94 },
  { month: 'Oct', value: 95 },
  { month: 'Nov', value: 96 },
  { month: 'Dec', value: 95 },
  { month: 'Jan', value: 96 },
  { month: 'Feb', value: 97 },
  { month: 'Mar', value: 97 },
];

export default {
  key: 'teacher',
  activePath: '/teacher',
  schoolName: 'Heritage Christian Academy',
  updatesCount: 3,
  user: {
    initials: 'DC',
    name: 'David Chen',
    role: 'Teacher — English & History',
  },
  dashboardTitle: 'Teacher Dashboard',
  eyebrow: 'CROWN Launch Preview',
  title: 'Good morning, Mr. Chen!',
  subtitle: 'Heritage Christian Academy',
  note: BASE_NOTE,

  metrics: [
    { label: 'Classes Today', value: '5', detail: 'Full teaching schedule active this period.', accent: 'blue' },
    { label: 'Attendance Posted', value: '4 / 5', detail: 'Period 3 submission still pending.', accent: 'gold' },
    { label: 'Assignments to Grade', value: '23', detail: '12 English compositions due end of day.', accent: 'navy' },
    { label: 'Parent Messages', value: '3', detail: 'Unread in your teacher inbox this morning.', accent: 'emerald' },
  ],

  priorities: [
    { title: 'Submit Period 3 attendance', detail: 'Homeroom sync incomplete — front office needs this before 10 AM.', state: 'Due now', tone: 'warn' },
    { title: 'Grade English composition queue', detail: '12 papers submitted yesterday afternoon awaiting feedback.', state: 'Due 3 PM', tone: 'warn' },
    { title: 'Reply to parent inquiry', detail: 'Mrs. Ramirez asked about the semester project rubric.', state: 'Today', tone: 'warn' },
  ],
  prioritiesTitle: 'Teaching execution queue',

  alerts: [
    { title: 'At-risk threshold: 2 students', detail: '2 students dropped below 70% average — flag for counselor review this week.', tone: 'warn' },
    { title: 'Missing work escalation', detail: '4 students have 3 or more missing assignments — contact families per policy.', tone: 'warn' },
  ],

  commandModules: [
    {
      key: 'gradebook',
      icon: 'GB',
      title: 'Gradebook',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '23 items pending grade',
      summary: 'English compositions and history quizzes need scoring before end of day.',
      kpis: [
        { label: 'Assignments pending', value: '23' },
        { label: 'At-risk students (<70%)', value: '2' },
        { label: 'Class average', value: '88.4%' },
        { label: 'Missing work flagged', value: '7' },
      ],
      details: [
        '12 English compositions submitted since Tuesday',
        '11 History quiz responses queued for review',
        '2 students require counselor notification this week',
        'Report card deadline: Friday 5 PM',
      ],
      primaryActionLabel: 'Open Gradebook',
      backActionLabel: 'Review At-Risk Students',
      primaryActionHref: '/gradebook',
      backActionHref: '/academics/teacher-grading',
      lastUpdated: '8:44 AM',
    },
    {
      key: 'attendance',
      icon: 'AT',
      title: 'Attendance',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '4 of 5 periods submitted',
      summary: 'Period 3 attendance pending — front office needs sync before morning closeout.',
      kpis: [
        { label: 'Students present', value: '124' },
        { label: 'Students absent', value: '3' },
        { label: 'Late arrivals', value: '2' },
        { label: 'Periods pending', value: '1' },
      ],
      details: [
        'Period 3 (10:05 AM) submission outstanding',
        '3 absent students — family notifications auto-queued',
        '2 late arrivals logged, no follow-up required',
        'Front office requires Period 3 sync by 10:00 AM',
      ],
      primaryActionLabel: 'Submit Attendance',
      backActionLabel: 'View Full Log',
      primaryActionHref: '/teacher/attendance',
      backActionHref: '/teacher/attendance',
      lastUpdated: '8:38 AM',
    },
    {
      key: 'schedule',
      icon: 'SC',
      title: 'Schedule & Classrooms',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '5 class periods today',
      summary: 'Full schedule running on time. No room conflicts or coverage gaps today.',
      kpis: [
        { label: 'Class periods today', value: '5' },
        { label: 'Total students', value: '127' },
        { label: 'Prep period', value: 'Period 4' },
        { label: 'Advisory', value: '7:50 AM' },
      ],
      details: [
        'Period 1: English 8A — Room 214',
        'Period 2: History 8B — Room 214',
        'Period 3: English 8B — Room 214',
        'Period 5: History 8A — Room 214',
        'Period 6: Advisory — Room 214',
      ],
      primaryActionLabel: 'View Schedule',
      backActionLabel: 'Open Classrooms',
      primaryActionHref: '/classrooms',
      backActionHref: '/classrooms',
      lastUpdated: '7:55 AM',
    },
    {
      key: 'communications',
      icon: 'CO',
      title: 'Parent Communications',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '3 unread messages',
      summary: 'Parent inquiries require replies this morning before class begins.',
      kpis: [
        { label: 'Unread parent messages', value: '3' },
        { label: 'Sent this week', value: '6' },
        { label: 'Staff announcements', value: '2' },
        { label: 'Bulletin reads today', value: '14' },
      ],
      details: [
        'Mrs. Ramirez: project rubric clarification request',
        'Mr. and Mrs. Tran: grade concern for Period 2',
        'Anonymous concern forwarded from front office',
        '2 staff announcements from principal unread',
      ],
      primaryActionLabel: 'Open Communications',
      backActionLabel: 'Reply to Parents',
      primaryActionHref: '/communications',
      backActionHref: '/communications',
      lastUpdated: '8:20 AM',
    },
    {
      key: 'assessments',
      icon: 'AS',
      title: 'Assessments',
      status: 'Stable',
      statusTone: 'good',
      mainKpi: '2 quizzes posted this week',
      summary: 'Quiz results are processing. Next assessment scheduled for Thursday.',
      kpis: [
        { label: 'Active assessments', value: '2' },
        { label: 'Graded assessments', value: '4' },
        { label: 'Average test score', value: '84.2%' },
        { label: 'Next assessment', value: 'Thu, May 8' },
      ],
      details: [
        'History quiz results available for review',
        'English vocabulary test graded and returned',
        'Thursday essay assessment instructions posted',
        'Extra credit submission window closes Friday',
      ],
      primaryActionLabel: 'Review Assessments',
      backActionLabel: 'Grade Quiz Results',
      primaryActionHref: '/academics/teacher-grading',
      backActionHref: '/academics/teacher-grading',
      lastUpdated: '8:10 AM',
    },
    {
      key: 'student-progress',
      icon: 'SP',
      title: 'Student Progress',
      status: 'Watch',
      statusTone: 'warn',
      mainKpi: '18 students below benchmark',
      summary: 'Select students need academic support or enrichment intervention this week.',
      kpis: [
        { label: 'Meeting benchmark', value: '109' },
        { label: 'Below benchmark', value: '18' },
        { label: 'Counselor referrals', value: '2' },
        { label: 'Enrichment candidates', value: '6' },
      ],
      details: [
        '18 students tracking below semester progress target',
        '2 referrals queued for counseling review',
        '6 high-achievers flagged for enrichment program',
        'Progress reports ready to distribute this week',
      ],
      primaryActionLabel: 'View Student Progress',
      backActionLabel: 'Open Academic Support',
      primaryActionHref: '/academics',
      backActionHref: '/academics/teacher-grading',
      lastUpdated: '8:05 AM',
    },
  ],

  trendPanels: [
    {
      kicker: 'Grade completion trend',
      title: 'Assignment grading pace across the semester',
      chip: 'Updated this morning',
      trend: GRADE_COMPLETION_TREND,
    },
    {
      kicker: 'Attendance trend',
      title: 'Section attendance rate — last 7 months',
      chip: 'Stable above 94%',
      trend: CLASS_ATTENDANCE_TREND,
    },
  ],

  activityKicker: 'Classroom activity',
  activityTitle: 'Recent classroom events',
  activities: [
    'English 8A essays submitted — 92% on-time completion.',
    'Period 1 attendance posted and synced to SIS.',
    'Parent portal reading assignment confirmed for Mrs. Tran.',
    'History quiz scores processed for both sections.',
    'Thursday assessment instructions published to class feed.',
  ],

  quickActions: [
    {
      title: 'Open Gradebook',
      eyebrow: 'Quick action',
      description: 'Review and post outstanding assignment grades for all sections.',
      actionLabel: 'Open Gradebook',
      href: '/gradebook',
      allowedRoles: ['teacher'],
    },
    {
      title: 'Submit Attendance',
      eyebrow: 'Quick action',
      description: 'Post remaining period attendance — Period 3 still pending.',
      actionLabel: 'Submit Attendance',
      href: '/teacher/attendance',
      allowedRoles: ['teacher'],
    },
    {
      title: 'Grade Assignments',
      eyebrow: 'Quick action',
      description: 'Open teacher grading queue for submitted student work.',
      actionLabel: 'Grade Now',
      href: '/academics/teacher-grading',
      allowedRoles: ['teacher'],
    },
    {
      title: 'Message Parents',
      eyebrow: 'Quick action',
      description: 'Respond to parent inquiries and send class updates.',
      actionLabel: 'Open Communications',
      href: '/communications',
      allowedRoles: ['teacher'],
    },
  ],

  statusTitle: 'Teacher workspace status',
  statusKicker: 'System health',
  statuses: [
    { label: 'Gradebook Sync', state: 'Up to date' },
    { label: 'Attendance System', state: 'Accepting entries' },
    { label: 'Class Roster', state: 'Current' },
    { label: 'Parent Portal', state: 'Online' },
  ],
};
